/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "AmberMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_AmberMRTranslator : public AmberMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Amber_mrContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *Nmr_restraintContext_cls = NULL;
    PyObject *Noesy_volume_restraintContext_cls = NULL;
    PyObject *Chemical_shift_restraintContext_cls = NULL;
    PyObject *Pcs_restraintContext_cls = NULL;
    PyObject *Dipolar_coupling_restraintContext_cls = NULL;
    PyObject *Csa_restraintContext_cls = NULL;
    PyObject *Restraint_statementContext_cls = NULL;
    PyObject *Restraint_factorContext_cls = NULL;
    PyObject *Noeexp_statementContext_cls = NULL;
    PyObject *Noeexp_factorContext_cls = NULL;
    PyObject *Shf_statementContext_cls = NULL;
    PyObject *Shf_factorContext_cls = NULL;
    PyObject *Pcshf_statementContext_cls = NULL;
    PyObject *Pcshf_factorContext_cls = NULL;
    PyObject *Align_statementContext_cls = NULL;
    PyObject *Align_factorContext_cls = NULL;
    PyObject *Csa_statementContext_cls = NULL;
    PyObject *Csa_factorContext_cls = NULL;
    PyObject *Distance_rst_func_callContext_cls = NULL;
    PyObject *Angle_rst_func_callContext_cls = NULL;
    PyObject *Plane_point_angle_rst_func_callContext_cls = NULL;
    PyObject *Plane_plane_angle_rst_func_callContext_cls = NULL;
    PyObject *Torsion_rst_func_callContext_cls = NULL;
    PyObject *Coordinate2_rst_func_callContext_cls = NULL;
    PyObject *Coordinate3_rst_func_callContext_cls = NULL;
    PyObject *Coordinate4_rst_func_callContext_cls = NULL;
    PyObject *Restraint_func_exprContext_cls = NULL;
    PyObject *Plane_rst_func_callContext_cls = NULL;
    PyObject *Com_rst_func_callContext_cls = NULL;
    PyObject *Unambig_atom_name_mappingContext_cls = NULL;
    PyObject *Mapping_listContext_cls = NULL;
    PyObject *Ambig_atom_name_mappingContext_cls = NULL;
    PyObject *Ambig_listContext_cls = NULL;

    public:
    SA_AmberMRTranslator(speedy_antlr::Translator *translator);
    ~SA_AmberMRTranslator();
    antlrcpp::Any visitAmber_mr(AmberMRParser::Amber_mrContext *ctx);

    antlrcpp::Any visitComment(AmberMRParser::CommentContext *ctx);

    antlrcpp::Any visitNmr_restraint(AmberMRParser::Nmr_restraintContext *ctx);

    antlrcpp::Any visitNoesy_volume_restraint(AmberMRParser::Noesy_volume_restraintContext *ctx);

    antlrcpp::Any visitChemical_shift_restraint(AmberMRParser::Chemical_shift_restraintContext *ctx);

    antlrcpp::Any visitPcs_restraint(AmberMRParser::Pcs_restraintContext *ctx);

    antlrcpp::Any visitDipolar_coupling_restraint(AmberMRParser::Dipolar_coupling_restraintContext *ctx);

    antlrcpp::Any visitCsa_restraint(AmberMRParser::Csa_restraintContext *ctx);

    antlrcpp::Any visitRestraint_statement(AmberMRParser::Restraint_statementContext *ctx);

    antlrcpp::Any visitRestraint_factor(AmberMRParser::Restraint_factorContext *ctx);

    antlrcpp::Any visitNoeexp_statement(AmberMRParser::Noeexp_statementContext *ctx);

    antlrcpp::Any visitNoeexp_factor(AmberMRParser::Noeexp_factorContext *ctx);

    antlrcpp::Any visitShf_statement(AmberMRParser::Shf_statementContext *ctx);

    antlrcpp::Any visitShf_factor(AmberMRParser::Shf_factorContext *ctx);

    antlrcpp::Any visitPcshf_statement(AmberMRParser::Pcshf_statementContext *ctx);

    antlrcpp::Any visitPcshf_factor(AmberMRParser::Pcshf_factorContext *ctx);

    antlrcpp::Any visitAlign_statement(AmberMRParser::Align_statementContext *ctx);

    antlrcpp::Any visitAlign_factor(AmberMRParser::Align_factorContext *ctx);

    antlrcpp::Any visitCsa_statement(AmberMRParser::Csa_statementContext *ctx);

    antlrcpp::Any visitCsa_factor(AmberMRParser::Csa_factorContext *ctx);

    antlrcpp::Any visitDistance_rst_func_call(AmberMRParser::Distance_rst_func_callContext *ctx);

    antlrcpp::Any visitAngle_rst_func_call(AmberMRParser::Angle_rst_func_callContext *ctx);

    antlrcpp::Any visitPlane_point_angle_rst_func_call(AmberMRParser::Plane_point_angle_rst_func_callContext *ctx);

    antlrcpp::Any visitPlane_plane_angle_rst_func_call(AmberMRParser::Plane_plane_angle_rst_func_callContext *ctx);

    antlrcpp::Any visitTorsion_rst_func_call(AmberMRParser::Torsion_rst_func_callContext *ctx);

    antlrcpp::Any visitCoordinate2_rst_func_call(AmberMRParser::Coordinate2_rst_func_callContext *ctx);

    antlrcpp::Any visitCoordinate3_rst_func_call(AmberMRParser::Coordinate3_rst_func_callContext *ctx);

    antlrcpp::Any visitCoordinate4_rst_func_call(AmberMRParser::Coordinate4_rst_func_callContext *ctx);

    antlrcpp::Any visitRestraint_func_expr(AmberMRParser::Restraint_func_exprContext *ctx);

    antlrcpp::Any visitPlane_rst_func_call(AmberMRParser::Plane_rst_func_callContext *ctx);

    antlrcpp::Any visitCom_rst_func_call(AmberMRParser::Com_rst_func_callContext *ctx);

    antlrcpp::Any visitUnambig_atom_name_mapping(AmberMRParser::Unambig_atom_name_mappingContext *ctx);

    antlrcpp::Any visitMapping_list(AmberMRParser::Mapping_listContext *ctx);

    antlrcpp::Any visitAmbig_atom_name_mapping(AmberMRParser::Ambig_atom_name_mappingContext *ctx);

    antlrcpp::Any visitAmbig_list(AmberMRParser::Ambig_listContext *ctx);

};