/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_ariamr_translator.h"


SA_AriaMRTranslator::SA_AriaMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_AriaMRTranslator::~SA_AriaMRTranslator() {
    Py_XDECREF(Aria_mrContext_cls);
    Py_XDECREF(Distance_restraintsContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
    Py_XDECREF(ContributionContext_cls);
    Py_XDECREF(Atom_pairContext_cls);
    Py_XDECREF(Atom_selectionContext_cls);
    Py_XDECREF(Old_distance_restraintsContext_cls);
    Py_XDECREF(Old_distance_restraintContext_cls);
    Py_XDECREF(P_rowContext_cls);
    Py_XDECREF(A_rowContext_cls);
    Py_XDECREF(C_rowContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Number_cContext_cls);
}


antlrcpp::Any SA_AriaMRTranslator::visitAria_mr(AriaMRParser::Aria_mrContext *ctx){
    if(!Aria_mrContext_cls) Aria_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Aria_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Aria_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitDistance_restraints(AriaMRParser::Distance_restraintsContext *ctx){
    if(!Distance_restraintsContext_cls) Distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitDistance_restraint(AriaMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitContribution(AriaMRParser::ContributionContext *ctx){
    if(!ContributionContext_cls) ContributionContext_cls = PyObject_GetAttrString(translator->parser_cls, "ContributionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ContributionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitAtom_pair(AriaMRParser::Atom_pairContext *ctx){
    if(!Atom_pairContext_cls) Atom_pairContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_pairContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_pairContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitAtom_selection(AriaMRParser::Atom_selectionContext *ctx){
    if(!Atom_selectionContext_cls) Atom_selectionContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_selectionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_selectionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitOld_distance_restraints(AriaMRParser::Old_distance_restraintsContext *ctx){
    if(!Old_distance_restraintsContext_cls) Old_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Old_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Old_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitOld_distance_restraint(AriaMRParser::Old_distance_restraintContext *ctx){
    if(!Old_distance_restraintContext_cls) Old_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Old_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Old_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitP_row(AriaMRParser::P_rowContext *ctx){
    if(!P_rowContext_cls) P_rowContext_cls = PyObject_GetAttrString(translator->parser_cls, "P_rowContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, P_rowContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitA_row(AriaMRParser::A_rowContext *ctx){
    if(!A_rowContext_cls) A_rowContext_cls = PyObject_GetAttrString(translator->parser_cls, "A_rowContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, A_rowContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitC_row(AriaMRParser::C_rowContext *ctx){
    if(!C_rowContext_cls) C_rowContext_cls = PyObject_GetAttrString(translator->parser_cls, "C_rowContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, C_rowContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitNumber(AriaMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AriaMRTranslator::visitNumber_c(AriaMRParser::Number_cContext *ctx){
    if(!Number_cContext_cls) Number_cContext_cls = PyObject_GetAttrString(translator->parser_cls, "Number_cContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Number_cContext_cls);
    return py_ctx;
}
