/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_ambermr_translator.h"


SA_AmberMRTranslator::SA_AmberMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_AmberMRTranslator::~SA_AmberMRTranslator() {
    Py_XDECREF(Amber_mrContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(Nmr_restraintContext_cls);
    Py_XDECREF(Noesy_volume_restraintContext_cls);
    Py_XDECREF(Chemical_shift_restraintContext_cls);
    Py_XDECREF(Pcs_restraintContext_cls);
    Py_XDECREF(Dipolar_coupling_restraintContext_cls);
    Py_XDECREF(Csa_restraintContext_cls);
    Py_XDECREF(Restraint_statementContext_cls);
    Py_XDECREF(Restraint_factorContext_cls);
    Py_XDECREF(Noeexp_statementContext_cls);
    Py_XDECREF(Noeexp_factorContext_cls);
    Py_XDECREF(Shf_statementContext_cls);
    Py_XDECREF(Shf_factorContext_cls);
    Py_XDECREF(Pcshf_statementContext_cls);
    Py_XDECREF(Pcshf_factorContext_cls);
    Py_XDECREF(Align_statementContext_cls);
    Py_XDECREF(Align_factorContext_cls);
    Py_XDECREF(Csa_statementContext_cls);
    Py_XDECREF(Csa_factorContext_cls);
    Py_XDECREF(Distance_rst_func_callContext_cls);
    Py_XDECREF(Angle_rst_func_callContext_cls);
    Py_XDECREF(Plane_point_angle_rst_func_callContext_cls);
    Py_XDECREF(Plane_plane_angle_rst_func_callContext_cls);
    Py_XDECREF(Torsion_rst_func_callContext_cls);
    Py_XDECREF(Coordinate2_rst_func_callContext_cls);
    Py_XDECREF(Coordinate3_rst_func_callContext_cls);
    Py_XDECREF(Coordinate4_rst_func_callContext_cls);
    Py_XDECREF(Restraint_func_exprContext_cls);
    Py_XDECREF(Plane_rst_func_callContext_cls);
    Py_XDECREF(Com_rst_func_callContext_cls);
    Py_XDECREF(Unambig_atom_name_mappingContext_cls);
    Py_XDECREF(Mapping_listContext_cls);
    Py_XDECREF(Ambig_atom_name_mappingContext_cls);
    Py_XDECREF(Ambig_listContext_cls);
}


antlrcpp::Any SA_AmberMRTranslator::visitAmber_mr(AmberMRParser::Amber_mrContext *ctx){
    if(!Amber_mrContext_cls) Amber_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Amber_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Amber_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitComment(AmberMRParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitNmr_restraint(AmberMRParser::Nmr_restraintContext *ctx){
    if(!Nmr_restraintContext_cls) Nmr_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nmr_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nmr_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitNoesy_volume_restraint(AmberMRParser::Noesy_volume_restraintContext *ctx){
    if(!Noesy_volume_restraintContext_cls) Noesy_volume_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Noesy_volume_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Noesy_volume_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitChemical_shift_restraint(AmberMRParser::Chemical_shift_restraintContext *ctx){
    if(!Chemical_shift_restraintContext_cls) Chemical_shift_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shift_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shift_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPcs_restraint(AmberMRParser::Pcs_restraintContext *ctx){
    if(!Pcs_restraintContext_cls) Pcs_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcs_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcs_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitDipolar_coupling_restraint(AmberMRParser::Dipolar_coupling_restraintContext *ctx){
    if(!Dipolar_coupling_restraintContext_cls) Dipolar_coupling_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dipolar_coupling_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dipolar_coupling_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCsa_restraint(AmberMRParser::Csa_restraintContext *ctx){
    if(!Csa_restraintContext_cls) Csa_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Csa_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Csa_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitRestraint_statement(AmberMRParser::Restraint_statementContext *ctx){
    if(!Restraint_statementContext_cls) Restraint_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Restraint_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Restraint_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitRestraint_factor(AmberMRParser::Restraint_factorContext *ctx){
    if(!Restraint_factorContext_cls) Restraint_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Restraint_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Restraint_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitNoeexp_statement(AmberMRParser::Noeexp_statementContext *ctx){
    if(!Noeexp_statementContext_cls) Noeexp_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Noeexp_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Noeexp_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitNoeexp_factor(AmberMRParser::Noeexp_factorContext *ctx){
    if(!Noeexp_factorContext_cls) Noeexp_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Noeexp_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Noeexp_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitShf_statement(AmberMRParser::Shf_statementContext *ctx){
    if(!Shf_statementContext_cls) Shf_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Shf_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Shf_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitShf_factor(AmberMRParser::Shf_factorContext *ctx){
    if(!Shf_factorContext_cls) Shf_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Shf_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Shf_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPcshf_statement(AmberMRParser::Pcshf_statementContext *ctx){
    if(!Pcshf_statementContext_cls) Pcshf_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcshf_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcshf_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPcshf_factor(AmberMRParser::Pcshf_factorContext *ctx){
    if(!Pcshf_factorContext_cls) Pcshf_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcshf_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcshf_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitAlign_statement(AmberMRParser::Align_statementContext *ctx){
    if(!Align_statementContext_cls) Align_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Align_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Align_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitAlign_factor(AmberMRParser::Align_factorContext *ctx){
    if(!Align_factorContext_cls) Align_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Align_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Align_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCsa_statement(AmberMRParser::Csa_statementContext *ctx){
    if(!Csa_statementContext_cls) Csa_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Csa_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Csa_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCsa_factor(AmberMRParser::Csa_factorContext *ctx){
    if(!Csa_factorContext_cls) Csa_factorContext_cls = PyObject_GetAttrString(translator->parser_cls, "Csa_factorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Csa_factorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitDistance_rst_func_call(AmberMRParser::Distance_rst_func_callContext *ctx){
    if(!Distance_rst_func_callContext_cls) Distance_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitAngle_rst_func_call(AmberMRParser::Angle_rst_func_callContext *ctx){
    if(!Angle_rst_func_callContext_cls) Angle_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPlane_point_angle_rst_func_call(AmberMRParser::Plane_point_angle_rst_func_callContext *ctx){
    if(!Plane_point_angle_rst_func_callContext_cls) Plane_point_angle_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Plane_point_angle_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Plane_point_angle_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPlane_plane_angle_rst_func_call(AmberMRParser::Plane_plane_angle_rst_func_callContext *ctx){
    if(!Plane_plane_angle_rst_func_callContext_cls) Plane_plane_angle_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Plane_plane_angle_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Plane_plane_angle_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitTorsion_rst_func_call(AmberMRParser::Torsion_rst_func_callContext *ctx){
    if(!Torsion_rst_func_callContext_cls) Torsion_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCoordinate2_rst_func_call(AmberMRParser::Coordinate2_rst_func_callContext *ctx){
    if(!Coordinate2_rst_func_callContext_cls) Coordinate2_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coordinate2_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coordinate2_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCoordinate3_rst_func_call(AmberMRParser::Coordinate3_rst_func_callContext *ctx){
    if(!Coordinate3_rst_func_callContext_cls) Coordinate3_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coordinate3_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coordinate3_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCoordinate4_rst_func_call(AmberMRParser::Coordinate4_rst_func_callContext *ctx){
    if(!Coordinate4_rst_func_callContext_cls) Coordinate4_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coordinate4_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coordinate4_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitRestraint_func_expr(AmberMRParser::Restraint_func_exprContext *ctx){
    if(!Restraint_func_exprContext_cls) Restraint_func_exprContext_cls = PyObject_GetAttrString(translator->parser_cls, "Restraint_func_exprContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Restraint_func_exprContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitPlane_rst_func_call(AmberMRParser::Plane_rst_func_callContext *ctx){
    if(!Plane_rst_func_callContext_cls) Plane_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Plane_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Plane_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitCom_rst_func_call(AmberMRParser::Com_rst_func_callContext *ctx){
    if(!Com_rst_func_callContext_cls) Com_rst_func_callContext_cls = PyObject_GetAttrString(translator->parser_cls, "Com_rst_func_callContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Com_rst_func_callContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitUnambig_atom_name_mapping(AmberMRParser::Unambig_atom_name_mappingContext *ctx){
    if(!Unambig_atom_name_mappingContext_cls) Unambig_atom_name_mappingContext_cls = PyObject_GetAttrString(translator->parser_cls, "Unambig_atom_name_mappingContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Unambig_atom_name_mappingContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitMapping_list(AmberMRParser::Mapping_listContext *ctx){
    if(!Mapping_listContext_cls) Mapping_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Mapping_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Mapping_listContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitAmbig_atom_name_mapping(AmberMRParser::Ambig_atom_name_mappingContext *ctx){
    if(!Ambig_atom_name_mappingContext_cls) Ambig_atom_name_mappingContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ambig_atom_name_mappingContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ambig_atom_name_mappingContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberMRTranslator::visitAmbig_list(AmberMRParser::Ambig_listContext *ctx){
    if(!Ambig_listContext_cls) Ambig_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ambig_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ambig_listContext_cls);
    return py_ctx;
}
