/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_amberpt_translator.h"


SA_AmberPTTranslator::SA_AmberPTTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_AmberPTTranslator::~SA_AmberPTTranslator() {
    Py_XDECREF(Amber_ptContext_cls);
    Py_XDECREF(Version_statementContext_cls);
    Py_XDECREF(Amber_atom_type_statementContext_cls);
    Py_XDECREF(Angle_equil_value_statementContext_cls);
    Py_XDECREF(Angle_force_constant_statementContext_cls);
    Py_XDECREF(Angles_inc_hydrogen_statementContext_cls);
    Py_XDECREF(Angles_without_hydrogen_statementContext_cls);
    Py_XDECREF(Atomic_number_statementContext_cls);
    Py_XDECREF(Atom_name_statementContext_cls);
    Py_XDECREF(Atom_type_index_statementContext_cls);
    Py_XDECREF(Atoms_per_molecule_statementContext_cls);
    Py_XDECREF(Bond_equil_value_statementContext_cls);
    Py_XDECREF(Bond_force_constant_statementContext_cls);
    Py_XDECREF(Bonds_inc_hydrogen_statementContext_cls);
    Py_XDECREF(Bonds_without_hydrogen_statementContext_cls);
    Py_XDECREF(Box_dimensions_statementContext_cls);
    Py_XDECREF(Cap_info_statementContext_cls);
    Py_XDECREF(Cap_info2_statementContext_cls);
    Py_XDECREF(Charge_statementContext_cls);
    Py_XDECREF(Cmap_count_statementContext_cls);
    Py_XDECREF(Cmap_resolution_statementContext_cls);
    Py_XDECREF(Cmap_parameter_statementContext_cls);
    Py_XDECREF(Cmap_index_statementContext_cls);
    Py_XDECREF(Dihedral_force_constant_statementContext_cls);
    Py_XDECREF(Dihedral_periodicity_statementContext_cls);
    Py_XDECREF(Dihedral_phase_statementContext_cls);
    Py_XDECREF(Dihedrals_inc_hydrogen_statementContext_cls);
    Py_XDECREF(Dihedrals_without_hydrogen_statementContext_cls);
    Py_XDECREF(Excluded_atoms_list_statementContext_cls);
    Py_XDECREF(Hbcut_statementContext_cls);
    Py_XDECREF(Hbond_acoef_statementContext_cls);
    Py_XDECREF(Hbond_bcoef_statementContext_cls);
    Py_XDECREF(Ipol_statementContext_cls);
    Py_XDECREF(Irotat_statementContext_cls);
    Py_XDECREF(Join_array_statementContext_cls);
    Py_XDECREF(Lennard_jones_acoef_statementContext_cls);
    Py_XDECREF(Lennard_jones_bcoef_statementContext_cls);
    Py_XDECREF(Mass_statementContext_cls);
    Py_XDECREF(Nonbonded_parm_index_statementContext_cls);
    Py_XDECREF(Number_excluded_atoms_statementContext_cls);
    Py_XDECREF(Pointers_statementContext_cls);
    Py_XDECREF(Polarizability_statementContext_cls);
    Py_XDECREF(Radii_statementContext_cls);
    Py_XDECREF(Radius_set_statementContext_cls);
    Py_XDECREF(Residue_label_statementContext_cls);
    Py_XDECREF(Residue_pointer_statementContext_cls);
    Py_XDECREF(Scee_scale_factor_statementContext_cls);
    Py_XDECREF(Scnb_scale_factor_statementContext_cls);
    Py_XDECREF(Screen_statementContext_cls);
    Py_XDECREF(Solty_statementContext_cls);
    Py_XDECREF(Solvent_pointers_statementContext_cls);
    Py_XDECREF(Title_statementContext_cls);
    Py_XDECREF(Tree_chain_classification_statementContext_cls);
    Py_XDECREF(Format_functionContext_cls);
}


antlrcpp::Any SA_AmberPTTranslator::visitAmber_pt(AmberPTParser::Amber_ptContext *ctx){
    if(!Amber_ptContext_cls) Amber_ptContext_cls = PyObject_GetAttrString(translator->parser_cls, "Amber_ptContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Amber_ptContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitVersion_statement(AmberPTParser::Version_statementContext *ctx){
    if(!Version_statementContext_cls) Version_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Version_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Version_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAmber_atom_type_statement(AmberPTParser::Amber_atom_type_statementContext *ctx){
    if(!Amber_atom_type_statementContext_cls) Amber_atom_type_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Amber_atom_type_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Amber_atom_type_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAngle_equil_value_statement(AmberPTParser::Angle_equil_value_statementContext *ctx){
    if(!Angle_equil_value_statementContext_cls) Angle_equil_value_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_equil_value_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_equil_value_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAngle_force_constant_statement(AmberPTParser::Angle_force_constant_statementContext *ctx){
    if(!Angle_force_constant_statementContext_cls) Angle_force_constant_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_force_constant_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_force_constant_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAngles_inc_hydrogen_statement(AmberPTParser::Angles_inc_hydrogen_statementContext *ctx){
    if(!Angles_inc_hydrogen_statementContext_cls) Angles_inc_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angles_inc_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angles_inc_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAngles_without_hydrogen_statement(AmberPTParser::Angles_without_hydrogen_statementContext *ctx){
    if(!Angles_without_hydrogen_statementContext_cls) Angles_without_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angles_without_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angles_without_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAtomic_number_statement(AmberPTParser::Atomic_number_statementContext *ctx){
    if(!Atomic_number_statementContext_cls) Atomic_number_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atomic_number_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atomic_number_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAtom_name_statement(AmberPTParser::Atom_name_statementContext *ctx){
    if(!Atom_name_statementContext_cls) Atom_name_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_name_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_name_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAtom_type_index_statement(AmberPTParser::Atom_type_index_statementContext *ctx){
    if(!Atom_type_index_statementContext_cls) Atom_type_index_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_type_index_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_type_index_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitAtoms_per_molecule_statement(AmberPTParser::Atoms_per_molecule_statementContext *ctx){
    if(!Atoms_per_molecule_statementContext_cls) Atoms_per_molecule_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atoms_per_molecule_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atoms_per_molecule_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitBond_equil_value_statement(AmberPTParser::Bond_equil_value_statementContext *ctx){
    if(!Bond_equil_value_statementContext_cls) Bond_equil_value_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bond_equil_value_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bond_equil_value_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitBond_force_constant_statement(AmberPTParser::Bond_force_constant_statementContext *ctx){
    if(!Bond_force_constant_statementContext_cls) Bond_force_constant_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bond_force_constant_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bond_force_constant_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitBonds_inc_hydrogen_statement(AmberPTParser::Bonds_inc_hydrogen_statementContext *ctx){
    if(!Bonds_inc_hydrogen_statementContext_cls) Bonds_inc_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bonds_inc_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bonds_inc_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitBonds_without_hydrogen_statement(AmberPTParser::Bonds_without_hydrogen_statementContext *ctx){
    if(!Bonds_without_hydrogen_statementContext_cls) Bonds_without_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bonds_without_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bonds_without_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitBox_dimensions_statement(AmberPTParser::Box_dimensions_statementContext *ctx){
    if(!Box_dimensions_statementContext_cls) Box_dimensions_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Box_dimensions_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Box_dimensions_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCap_info_statement(AmberPTParser::Cap_info_statementContext *ctx){
    if(!Cap_info_statementContext_cls) Cap_info_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cap_info_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cap_info_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCap_info2_statement(AmberPTParser::Cap_info2_statementContext *ctx){
    if(!Cap_info2_statementContext_cls) Cap_info2_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cap_info2_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cap_info2_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCharge_statement(AmberPTParser::Charge_statementContext *ctx){
    if(!Charge_statementContext_cls) Charge_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Charge_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Charge_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCmap_count_statement(AmberPTParser::Cmap_count_statementContext *ctx){
    if(!Cmap_count_statementContext_cls) Cmap_count_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cmap_count_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cmap_count_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCmap_resolution_statement(AmberPTParser::Cmap_resolution_statementContext *ctx){
    if(!Cmap_resolution_statementContext_cls) Cmap_resolution_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cmap_resolution_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cmap_resolution_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCmap_parameter_statement(AmberPTParser::Cmap_parameter_statementContext *ctx){
    if(!Cmap_parameter_statementContext_cls) Cmap_parameter_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cmap_parameter_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cmap_parameter_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitCmap_index_statement(AmberPTParser::Cmap_index_statementContext *ctx){
    if(!Cmap_index_statementContext_cls) Cmap_index_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cmap_index_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cmap_index_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitDihedral_force_constant_statement(AmberPTParser::Dihedral_force_constant_statementContext *ctx){
    if(!Dihedral_force_constant_statementContext_cls) Dihedral_force_constant_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_force_constant_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_force_constant_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitDihedral_periodicity_statement(AmberPTParser::Dihedral_periodicity_statementContext *ctx){
    if(!Dihedral_periodicity_statementContext_cls) Dihedral_periodicity_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_periodicity_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_periodicity_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitDihedral_phase_statement(AmberPTParser::Dihedral_phase_statementContext *ctx){
    if(!Dihedral_phase_statementContext_cls) Dihedral_phase_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_phase_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_phase_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitDihedrals_inc_hydrogen_statement(AmberPTParser::Dihedrals_inc_hydrogen_statementContext *ctx){
    if(!Dihedrals_inc_hydrogen_statementContext_cls) Dihedrals_inc_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedrals_inc_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedrals_inc_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitDihedrals_without_hydrogen_statement(AmberPTParser::Dihedrals_without_hydrogen_statementContext *ctx){
    if(!Dihedrals_without_hydrogen_statementContext_cls) Dihedrals_without_hydrogen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedrals_without_hydrogen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedrals_without_hydrogen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitExcluded_atoms_list_statement(AmberPTParser::Excluded_atoms_list_statementContext *ctx){
    if(!Excluded_atoms_list_statementContext_cls) Excluded_atoms_list_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Excluded_atoms_list_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Excluded_atoms_list_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitHbcut_statement(AmberPTParser::Hbcut_statementContext *ctx){
    if(!Hbcut_statementContext_cls) Hbcut_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Hbcut_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Hbcut_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitHbond_acoef_statement(AmberPTParser::Hbond_acoef_statementContext *ctx){
    if(!Hbond_acoef_statementContext_cls) Hbond_acoef_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Hbond_acoef_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Hbond_acoef_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitHbond_bcoef_statement(AmberPTParser::Hbond_bcoef_statementContext *ctx){
    if(!Hbond_bcoef_statementContext_cls) Hbond_bcoef_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Hbond_bcoef_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Hbond_bcoef_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitIpol_statement(AmberPTParser::Ipol_statementContext *ctx){
    if(!Ipol_statementContext_cls) Ipol_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ipol_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ipol_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitIrotat_statement(AmberPTParser::Irotat_statementContext *ctx){
    if(!Irotat_statementContext_cls) Irotat_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Irotat_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Irotat_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitJoin_array_statement(AmberPTParser::Join_array_statementContext *ctx){
    if(!Join_array_statementContext_cls) Join_array_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Join_array_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Join_array_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitLennard_jones_acoef_statement(AmberPTParser::Lennard_jones_acoef_statementContext *ctx){
    if(!Lennard_jones_acoef_statementContext_cls) Lennard_jones_acoef_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Lennard_jones_acoef_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Lennard_jones_acoef_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitLennard_jones_bcoef_statement(AmberPTParser::Lennard_jones_bcoef_statementContext *ctx){
    if(!Lennard_jones_bcoef_statementContext_cls) Lennard_jones_bcoef_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Lennard_jones_bcoef_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Lennard_jones_bcoef_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitMass_statement(AmberPTParser::Mass_statementContext *ctx){
    if(!Mass_statementContext_cls) Mass_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Mass_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Mass_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitNonbonded_parm_index_statement(AmberPTParser::Nonbonded_parm_index_statementContext *ctx){
    if(!Nonbonded_parm_index_statementContext_cls) Nonbonded_parm_index_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nonbonded_parm_index_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nonbonded_parm_index_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitNumber_excluded_atoms_statement(AmberPTParser::Number_excluded_atoms_statementContext *ctx){
    if(!Number_excluded_atoms_statementContext_cls) Number_excluded_atoms_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Number_excluded_atoms_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Number_excluded_atoms_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitPointers_statement(AmberPTParser::Pointers_statementContext *ctx){
    if(!Pointers_statementContext_cls) Pointers_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pointers_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pointers_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitPolarizability_statement(AmberPTParser::Polarizability_statementContext *ctx){
    if(!Polarizability_statementContext_cls) Polarizability_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Polarizability_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Polarizability_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitRadii_statement(AmberPTParser::Radii_statementContext *ctx){
    if(!Radii_statementContext_cls) Radii_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Radii_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Radii_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitRadius_set_statement(AmberPTParser::Radius_set_statementContext *ctx){
    if(!Radius_set_statementContext_cls) Radius_set_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Radius_set_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Radius_set_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitResidue_label_statement(AmberPTParser::Residue_label_statementContext *ctx){
    if(!Residue_label_statementContext_cls) Residue_label_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Residue_label_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Residue_label_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitResidue_pointer_statement(AmberPTParser::Residue_pointer_statementContext *ctx){
    if(!Residue_pointer_statementContext_cls) Residue_pointer_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Residue_pointer_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Residue_pointer_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitScee_scale_factor_statement(AmberPTParser::Scee_scale_factor_statementContext *ctx){
    if(!Scee_scale_factor_statementContext_cls) Scee_scale_factor_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Scee_scale_factor_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Scee_scale_factor_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitScnb_scale_factor_statement(AmberPTParser::Scnb_scale_factor_statementContext *ctx){
    if(!Scnb_scale_factor_statementContext_cls) Scnb_scale_factor_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Scnb_scale_factor_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Scnb_scale_factor_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitScreen_statement(AmberPTParser::Screen_statementContext *ctx){
    if(!Screen_statementContext_cls) Screen_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Screen_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Screen_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitSolty_statement(AmberPTParser::Solty_statementContext *ctx){
    if(!Solty_statementContext_cls) Solty_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Solty_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Solty_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitSolvent_pointers_statement(AmberPTParser::Solvent_pointers_statementContext *ctx){
    if(!Solvent_pointers_statementContext_cls) Solvent_pointers_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Solvent_pointers_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Solvent_pointers_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitTitle_statement(AmberPTParser::Title_statementContext *ctx){
    if(!Title_statementContext_cls) Title_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Title_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Title_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitTree_chain_classification_statement(AmberPTParser::Tree_chain_classification_statementContext *ctx){
    if(!Tree_chain_classification_statementContext_cls) Tree_chain_classification_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tree_chain_classification_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tree_chain_classification_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_AmberPTTranslator::visitFormat_function(AmberPTParser::Format_functionContext *ctx){
    if(!Format_functionContext_cls) Format_functionContext_cls = PyObject_GetAttrString(translator->parser_cls, "Format_functionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Format_functionContext_cls);
    return py_ctx;
}
