/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "AmberPTParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_AmberPTTranslator : public AmberPTParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Amber_ptContext_cls = NULL;
    PyObject *Version_statementContext_cls = NULL;
    PyObject *Amber_atom_type_statementContext_cls = NULL;
    PyObject *Angle_equil_value_statementContext_cls = NULL;
    PyObject *Angle_force_constant_statementContext_cls = NULL;
    PyObject *Angles_inc_hydrogen_statementContext_cls = NULL;
    PyObject *Angles_without_hydrogen_statementContext_cls = NULL;
    PyObject *Atomic_number_statementContext_cls = NULL;
    PyObject *Atom_name_statementContext_cls = NULL;
    PyObject *Atom_type_index_statementContext_cls = NULL;
    PyObject *Atoms_per_molecule_statementContext_cls = NULL;
    PyObject *Bond_equil_value_statementContext_cls = NULL;
    PyObject *Bond_force_constant_statementContext_cls = NULL;
    PyObject *Bonds_inc_hydrogen_statementContext_cls = NULL;
    PyObject *Bonds_without_hydrogen_statementContext_cls = NULL;
    PyObject *Box_dimensions_statementContext_cls = NULL;
    PyObject *Cap_info_statementContext_cls = NULL;
    PyObject *Cap_info2_statementContext_cls = NULL;
    PyObject *Charge_statementContext_cls = NULL;
    PyObject *Cmap_count_statementContext_cls = NULL;
    PyObject *Cmap_resolution_statementContext_cls = NULL;
    PyObject *Cmap_parameter_statementContext_cls = NULL;
    PyObject *Cmap_index_statementContext_cls = NULL;
    PyObject *Dihedral_force_constant_statementContext_cls = NULL;
    PyObject *Dihedral_periodicity_statementContext_cls = NULL;
    PyObject *Dihedral_phase_statementContext_cls = NULL;
    PyObject *Dihedrals_inc_hydrogen_statementContext_cls = NULL;
    PyObject *Dihedrals_without_hydrogen_statementContext_cls = NULL;
    PyObject *Excluded_atoms_list_statementContext_cls = NULL;
    PyObject *Hbcut_statementContext_cls = NULL;
    PyObject *Hbond_acoef_statementContext_cls = NULL;
    PyObject *Hbond_bcoef_statementContext_cls = NULL;
    PyObject *Ipol_statementContext_cls = NULL;
    PyObject *Irotat_statementContext_cls = NULL;
    PyObject *Join_array_statementContext_cls = NULL;
    PyObject *Lennard_jones_acoef_statementContext_cls = NULL;
    PyObject *Lennard_jones_bcoef_statementContext_cls = NULL;
    PyObject *Mass_statementContext_cls = NULL;
    PyObject *Nonbonded_parm_index_statementContext_cls = NULL;
    PyObject *Number_excluded_atoms_statementContext_cls = NULL;
    PyObject *Pointers_statementContext_cls = NULL;
    PyObject *Polarizability_statementContext_cls = NULL;
    PyObject *Radii_statementContext_cls = NULL;
    PyObject *Radius_set_statementContext_cls = NULL;
    PyObject *Residue_label_statementContext_cls = NULL;
    PyObject *Residue_pointer_statementContext_cls = NULL;
    PyObject *Scee_scale_factor_statementContext_cls = NULL;
    PyObject *Scnb_scale_factor_statementContext_cls = NULL;
    PyObject *Screen_statementContext_cls = NULL;
    PyObject *Solty_statementContext_cls = NULL;
    PyObject *Solvent_pointers_statementContext_cls = NULL;
    PyObject *Title_statementContext_cls = NULL;
    PyObject *Tree_chain_classification_statementContext_cls = NULL;
    PyObject *Format_functionContext_cls = NULL;

    public:
    SA_AmberPTTranslator(speedy_antlr::Translator *translator);
    ~SA_AmberPTTranslator();
    antlrcpp::Any visitAmber_pt(AmberPTParser::Amber_ptContext *ctx);

    antlrcpp::Any visitVersion_statement(AmberPTParser::Version_statementContext *ctx);

    antlrcpp::Any visitAmber_atom_type_statement(AmberPTParser::Amber_atom_type_statementContext *ctx);

    antlrcpp::Any visitAngle_equil_value_statement(AmberPTParser::Angle_equil_value_statementContext *ctx);

    antlrcpp::Any visitAngle_force_constant_statement(AmberPTParser::Angle_force_constant_statementContext *ctx);

    antlrcpp::Any visitAngles_inc_hydrogen_statement(AmberPTParser::Angles_inc_hydrogen_statementContext *ctx);

    antlrcpp::Any visitAngles_without_hydrogen_statement(AmberPTParser::Angles_without_hydrogen_statementContext *ctx);

    antlrcpp::Any visitAtomic_number_statement(AmberPTParser::Atomic_number_statementContext *ctx);

    antlrcpp::Any visitAtom_name_statement(AmberPTParser::Atom_name_statementContext *ctx);

    antlrcpp::Any visitAtom_type_index_statement(AmberPTParser::Atom_type_index_statementContext *ctx);

    antlrcpp::Any visitAtoms_per_molecule_statement(AmberPTParser::Atoms_per_molecule_statementContext *ctx);

    antlrcpp::Any visitBond_equil_value_statement(AmberPTParser::Bond_equil_value_statementContext *ctx);

    antlrcpp::Any visitBond_force_constant_statement(AmberPTParser::Bond_force_constant_statementContext *ctx);

    antlrcpp::Any visitBonds_inc_hydrogen_statement(AmberPTParser::Bonds_inc_hydrogen_statementContext *ctx);

    antlrcpp::Any visitBonds_without_hydrogen_statement(AmberPTParser::Bonds_without_hydrogen_statementContext *ctx);

    antlrcpp::Any visitBox_dimensions_statement(AmberPTParser::Box_dimensions_statementContext *ctx);

    antlrcpp::Any visitCap_info_statement(AmberPTParser::Cap_info_statementContext *ctx);

    antlrcpp::Any visitCap_info2_statement(AmberPTParser::Cap_info2_statementContext *ctx);

    antlrcpp::Any visitCharge_statement(AmberPTParser::Charge_statementContext *ctx);

    antlrcpp::Any visitCmap_count_statement(AmberPTParser::Cmap_count_statementContext *ctx);

    antlrcpp::Any visitCmap_resolution_statement(AmberPTParser::Cmap_resolution_statementContext *ctx);

    antlrcpp::Any visitCmap_parameter_statement(AmberPTParser::Cmap_parameter_statementContext *ctx);

    antlrcpp::Any visitCmap_index_statement(AmberPTParser::Cmap_index_statementContext *ctx);

    antlrcpp::Any visitDihedral_force_constant_statement(AmberPTParser::Dihedral_force_constant_statementContext *ctx);

    antlrcpp::Any visitDihedral_periodicity_statement(AmberPTParser::Dihedral_periodicity_statementContext *ctx);

    antlrcpp::Any visitDihedral_phase_statement(AmberPTParser::Dihedral_phase_statementContext *ctx);

    antlrcpp::Any visitDihedrals_inc_hydrogen_statement(AmberPTParser::Dihedrals_inc_hydrogen_statementContext *ctx);

    antlrcpp::Any visitDihedrals_without_hydrogen_statement(AmberPTParser::Dihedrals_without_hydrogen_statementContext *ctx);

    antlrcpp::Any visitExcluded_atoms_list_statement(AmberPTParser::Excluded_atoms_list_statementContext *ctx);

    antlrcpp::Any visitHbcut_statement(AmberPTParser::Hbcut_statementContext *ctx);

    antlrcpp::Any visitHbond_acoef_statement(AmberPTParser::Hbond_acoef_statementContext *ctx);

    antlrcpp::Any visitHbond_bcoef_statement(AmberPTParser::Hbond_bcoef_statementContext *ctx);

    antlrcpp::Any visitIpol_statement(AmberPTParser::Ipol_statementContext *ctx);

    antlrcpp::Any visitIrotat_statement(AmberPTParser::Irotat_statementContext *ctx);

    antlrcpp::Any visitJoin_array_statement(AmberPTParser::Join_array_statementContext *ctx);

    antlrcpp::Any visitLennard_jones_acoef_statement(AmberPTParser::Lennard_jones_acoef_statementContext *ctx);

    antlrcpp::Any visitLennard_jones_bcoef_statement(AmberPTParser::Lennard_jones_bcoef_statementContext *ctx);

    antlrcpp::Any visitMass_statement(AmberPTParser::Mass_statementContext *ctx);

    antlrcpp::Any visitNonbonded_parm_index_statement(AmberPTParser::Nonbonded_parm_index_statementContext *ctx);

    antlrcpp::Any visitNumber_excluded_atoms_statement(AmberPTParser::Number_excluded_atoms_statementContext *ctx);

    antlrcpp::Any visitPointers_statement(AmberPTParser::Pointers_statementContext *ctx);

    antlrcpp::Any visitPolarizability_statement(AmberPTParser::Polarizability_statementContext *ctx);

    antlrcpp::Any visitRadii_statement(AmberPTParser::Radii_statementContext *ctx);

    antlrcpp::Any visitRadius_set_statement(AmberPTParser::Radius_set_statementContext *ctx);

    antlrcpp::Any visitResidue_label_statement(AmberPTParser::Residue_label_statementContext *ctx);

    antlrcpp::Any visitResidue_pointer_statement(AmberPTParser::Residue_pointer_statementContext *ctx);

    antlrcpp::Any visitScee_scale_factor_statement(AmberPTParser::Scee_scale_factor_statementContext *ctx);

    antlrcpp::Any visitScnb_scale_factor_statement(AmberPTParser::Scnb_scale_factor_statementContext *ctx);

    antlrcpp::Any visitScreen_statement(AmberPTParser::Screen_statementContext *ctx);

    antlrcpp::Any visitSolty_statement(AmberPTParser::Solty_statementContext *ctx);

    antlrcpp::Any visitSolvent_pointers_statement(AmberPTParser::Solvent_pointers_statementContext *ctx);

    antlrcpp::Any visitTitle_statement(AmberPTParser::Title_statementContext *ctx);

    antlrcpp::Any visitTree_chain_classification_statement(AmberPTParser::Tree_chain_classification_statementContext *ctx);

    antlrcpp::Any visitFormat_function(AmberPTParser::Format_functionContext *ctx);

};