/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_barepk_translator.h"


SA_BarePKTranslator::SA_BarePKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_BarePKTranslator::~SA_BarePKTranslator() {
    Py_XDECREF(Bare_pkContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Peak_list_wo_chain_2dContext_cls);
    Py_XDECREF(Peak_wo_chain_2dContext_cls);
    Py_XDECREF(Peak_list_wo_chain_3dContext_cls);
    Py_XDECREF(Peak_wo_chain_3dContext_cls);
    Py_XDECREF(Peak_list_wo_chain_4dContext_cls);
    Py_XDECREF(Peak_wo_chain_4dContext_cls);
    Py_XDECREF(Row_format_2dContext_cls);
    Py_XDECREF(Row_format_3dContext_cls);
    Py_XDECREF(Row_format_4dContext_cls);
    Py_XDECREF(Rev_row_format_2dContext_cls);
    Py_XDECREF(Rev_row_format_3dContext_cls);
    Py_XDECREF(Rev_row_format_4dContext_cls);
    Py_XDECREF(Row_format_wo_label_2dContext_cls);
    Py_XDECREF(Row_format_wo_label_3dContext_cls);
    Py_XDECREF(Row_format_wo_label_4dContext_cls);
    Py_XDECREF(Peak_list_row_2dContext_cls);
    Py_XDECREF(Peak_list_row_3dContext_cls);
    Py_XDECREF(Peak_list_row_4dContext_cls);
    Py_XDECREF(PositionContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_BarePKTranslator::visitBare_pk(BarePKParser::Bare_pkContext *ctx){
    if(!Bare_pkContext_cls) Bare_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bare_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bare_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_2d(BarePKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_2d(BarePKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_3d(BarePKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_3d(BarePKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_4d(BarePKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_4d(BarePKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_wo_chain_2d(BarePKParser::Peak_list_wo_chain_2dContext *ctx){
    if(!Peak_list_wo_chain_2dContext_cls) Peak_list_wo_chain_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_chain_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_chain_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_wo_chain_2d(BarePKParser::Peak_wo_chain_2dContext *ctx){
    if(!Peak_wo_chain_2dContext_cls) Peak_wo_chain_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_chain_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_chain_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_wo_chain_3d(BarePKParser::Peak_list_wo_chain_3dContext *ctx){
    if(!Peak_list_wo_chain_3dContext_cls) Peak_list_wo_chain_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_chain_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_chain_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_wo_chain_3d(BarePKParser::Peak_wo_chain_3dContext *ctx){
    if(!Peak_wo_chain_3dContext_cls) Peak_wo_chain_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_chain_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_chain_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_wo_chain_4d(BarePKParser::Peak_list_wo_chain_4dContext *ctx){
    if(!Peak_list_wo_chain_4dContext_cls) Peak_list_wo_chain_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_chain_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_chain_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_wo_chain_4d(BarePKParser::Peak_wo_chain_4dContext *ctx){
    if(!Peak_wo_chain_4dContext_cls) Peak_wo_chain_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_chain_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_chain_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_2d(BarePKParser::Row_format_2dContext *ctx){
    if(!Row_format_2dContext_cls) Row_format_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_3d(BarePKParser::Row_format_3dContext *ctx){
    if(!Row_format_3dContext_cls) Row_format_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_4d(BarePKParser::Row_format_4dContext *ctx){
    if(!Row_format_4dContext_cls) Row_format_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRev_row_format_2d(BarePKParser::Rev_row_format_2dContext *ctx){
    if(!Rev_row_format_2dContext_cls) Rev_row_format_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rev_row_format_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rev_row_format_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRev_row_format_3d(BarePKParser::Rev_row_format_3dContext *ctx){
    if(!Rev_row_format_3dContext_cls) Rev_row_format_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rev_row_format_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rev_row_format_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRev_row_format_4d(BarePKParser::Rev_row_format_4dContext *ctx){
    if(!Rev_row_format_4dContext_cls) Rev_row_format_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rev_row_format_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rev_row_format_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_wo_label_2d(BarePKParser::Row_format_wo_label_2dContext *ctx){
    if(!Row_format_wo_label_2dContext_cls) Row_format_wo_label_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_wo_label_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_wo_label_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_wo_label_3d(BarePKParser::Row_format_wo_label_3dContext *ctx){
    if(!Row_format_wo_label_3dContext_cls) Row_format_wo_label_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_wo_label_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_wo_label_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitRow_format_wo_label_4d(BarePKParser::Row_format_wo_label_4dContext *ctx){
    if(!Row_format_wo_label_4dContext_cls) Row_format_wo_label_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Row_format_wo_label_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Row_format_wo_label_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_row_2d(BarePKParser::Peak_list_row_2dContext *ctx){
    if(!Peak_list_row_2dContext_cls) Peak_list_row_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_row_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_row_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_row_3d(BarePKParser::Peak_list_row_3dContext *ctx){
    if(!Peak_list_row_3dContext_cls) Peak_list_row_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_row_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_row_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPeak_list_row_4d(BarePKParser::Peak_list_row_4dContext *ctx){
    if(!Peak_list_row_4dContext_cls) Peak_list_row_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_row_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_row_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitPosition(BarePKParser::PositionContext *ctx){
    if(!PositionContext_cls) PositionContext_cls = PyObject_GetAttrString(translator->parser_cls, "PositionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PositionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePKTranslator::visitNumber(BarePKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
