/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "BareMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_BareMRTranslator : public BareMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Bare_mrContext_cls = NULL;
    PyObject *Mr_row_formatContext_cls = NULL;
    PyObject *HeaderContext_cls = NULL;
    PyObject *Mr_row_listContext_cls = NULL;
    PyObject *AnyContext_cls = NULL;
    PyObject *Column_nameContext_cls = NULL;

    public:
    SA_BareMRTranslator(speedy_antlr::Translator *translator);
    ~SA_BareMRTranslator();
    antlrcpp::Any visitBare_mr(BareMRParser::Bare_mrContext *ctx);

    antlrcpp::Any visitMr_row_format(BareMRParser::Mr_row_formatContext *ctx);

    antlrcpp::Any visitHeader(BareMRParser::HeaderContext *ctx);

    antlrcpp::Any visitMr_row_list(BareMRParser::Mr_row_listContext *ctx);

    antlrcpp::Any visitAny(BareMRParser::AnyContext *ctx);

    antlrcpp::Any visitColumn_name(BareMRParser::Column_nameContext *ctx);

};