/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "BarePKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_BarePKTranslator : public BarePKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Bare_pkContext_cls = NULL;
    PyObject *Peak_list_2dContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_list_3dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_list_4dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *Peak_list_wo_chain_2dContext_cls = NULL;
    PyObject *Peak_wo_chain_2dContext_cls = NULL;
    PyObject *Peak_list_wo_chain_3dContext_cls = NULL;
    PyObject *Peak_wo_chain_3dContext_cls = NULL;
    PyObject *Peak_list_wo_chain_4dContext_cls = NULL;
    PyObject *Peak_wo_chain_4dContext_cls = NULL;
    PyObject *Row_format_2dContext_cls = NULL;
    PyObject *Row_format_3dContext_cls = NULL;
    PyObject *Row_format_4dContext_cls = NULL;
    PyObject *Rev_row_format_2dContext_cls = NULL;
    PyObject *Rev_row_format_3dContext_cls = NULL;
    PyObject *Rev_row_format_4dContext_cls = NULL;
    PyObject *Row_format_wo_label_2dContext_cls = NULL;
    PyObject *Row_format_wo_label_3dContext_cls = NULL;
    PyObject *Row_format_wo_label_4dContext_cls = NULL;
    PyObject *Peak_list_row_2dContext_cls = NULL;
    PyObject *Peak_list_row_3dContext_cls = NULL;
    PyObject *Peak_list_row_4dContext_cls = NULL;
    PyObject *PositionContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_BarePKTranslator(speedy_antlr::Translator *translator);
    ~SA_BarePKTranslator();
    antlrcpp::Any visitBare_pk(BarePKParser::Bare_pkContext *ctx);

    antlrcpp::Any visitPeak_list_2d(BarePKParser::Peak_list_2dContext *ctx);

    antlrcpp::Any visitPeak_2d(BarePKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_list_3d(BarePKParser::Peak_list_3dContext *ctx);

    antlrcpp::Any visitPeak_3d(BarePKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_list_4d(BarePKParser::Peak_list_4dContext *ctx);

    antlrcpp::Any visitPeak_4d(BarePKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_chain_2d(BarePKParser::Peak_list_wo_chain_2dContext *ctx);

    antlrcpp::Any visitPeak_wo_chain_2d(BarePKParser::Peak_wo_chain_2dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_chain_3d(BarePKParser::Peak_list_wo_chain_3dContext *ctx);

    antlrcpp::Any visitPeak_wo_chain_3d(BarePKParser::Peak_wo_chain_3dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_chain_4d(BarePKParser::Peak_list_wo_chain_4dContext *ctx);

    antlrcpp::Any visitPeak_wo_chain_4d(BarePKParser::Peak_wo_chain_4dContext *ctx);

    antlrcpp::Any visitRow_format_2d(BarePKParser::Row_format_2dContext *ctx);

    antlrcpp::Any visitRow_format_3d(BarePKParser::Row_format_3dContext *ctx);

    antlrcpp::Any visitRow_format_4d(BarePKParser::Row_format_4dContext *ctx);

    antlrcpp::Any visitRev_row_format_2d(BarePKParser::Rev_row_format_2dContext *ctx);

    antlrcpp::Any visitRev_row_format_3d(BarePKParser::Rev_row_format_3dContext *ctx);

    antlrcpp::Any visitRev_row_format_4d(BarePKParser::Rev_row_format_4dContext *ctx);

    antlrcpp::Any visitRow_format_wo_label_2d(BarePKParser::Row_format_wo_label_2dContext *ctx);

    antlrcpp::Any visitRow_format_wo_label_3d(BarePKParser::Row_format_wo_label_3dContext *ctx);

    antlrcpp::Any visitRow_format_wo_label_4d(BarePKParser::Row_format_wo_label_4dContext *ctx);

    antlrcpp::Any visitPeak_list_row_2d(BarePKParser::Peak_list_row_2dContext *ctx);

    antlrcpp::Any visitPeak_list_row_3d(BarePKParser::Peak_list_row_3dContext *ctx);

    antlrcpp::Any visitPeak_list_row_4d(BarePKParser::Peak_list_row_4dContext *ctx);

    antlrcpp::Any visitPosition(BarePKParser::PositionContext *ctx);

    antlrcpp::Any visitNumber(BarePKParser::NumberContext *ctx);

};