/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_baremr_translator.h"


SA_BareMRTranslator::SA_BareMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_BareMRTranslator::~SA_BareMRTranslator() {
    Py_XDECREF(Bare_mrContext_cls);
    Py_XDECREF(Mr_row_formatContext_cls);
    Py_XDECREF(HeaderContext_cls);
    Py_XDECREF(Mr_row_listContext_cls);
    Py_XDECREF(AnyContext_cls);
    Py_XDECREF(Column_nameContext_cls);
}


antlrcpp::Any SA_BareMRTranslator::visitBare_mr(BareMRParser::Bare_mrContext *ctx){
    if(!Bare_mrContext_cls) Bare_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bare_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bare_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BareMRTranslator::visitMr_row_format(BareMRParser::Mr_row_formatContext *ctx){
    if(!Mr_row_formatContext_cls) Mr_row_formatContext_cls = PyObject_GetAttrString(translator->parser_cls, "Mr_row_formatContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Mr_row_formatContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BareMRTranslator::visitHeader(BareMRParser::HeaderContext *ctx){
    if(!HeaderContext_cls) HeaderContext_cls = PyObject_GetAttrString(translator->parser_cls, "HeaderContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, HeaderContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BareMRTranslator::visitMr_row_list(BareMRParser::Mr_row_listContext *ctx){
    if(!Mr_row_listContext_cls) Mr_row_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Mr_row_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Mr_row_listContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BareMRTranslator::visitAny(BareMRParser::AnyContext *ctx){
    if(!AnyContext_cls) AnyContext_cls = PyObject_GetAttrString(translator->parser_cls, "AnyContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AnyContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BareMRTranslator::visitColumn_name(BareMRParser::Column_nameContext *ctx){
    if(!Column_nameContext_cls) Column_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Column_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Column_nameContext_cls);
    return py_ctx;
}
