/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_barepdb_translator.h"


SA_BarePDBTranslator::SA_BarePDBTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_BarePDBTranslator::~SA_BarePDBTranslator() {
    Py_XDECREF(Bare_pdbContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(CoordinatesContext_cls);
    Py_XDECREF(Atom_coordinateContext_cls);
    Py_XDECREF(Atom_numContext_cls);
    Py_XDECREF(Atom_nameContext_cls);
    Py_XDECREF(XyzContext_cls);
    Py_XDECREF(X_yzContext_cls);
    Py_XDECREF(Xy_zContext_cls);
    Py_XDECREF(X_y_zContext_cls);
    Py_XDECREF(UndefinedContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(TerminalContext_cls);
    Py_XDECREF(EndContext_cls);
}


antlrcpp::Any SA_BarePDBTranslator::visitBare_pdb(BarePDBParser::Bare_pdbContext *ctx){
    if(!Bare_pdbContext_cls) Bare_pdbContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bare_pdbContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bare_pdbContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitComment(BarePDBParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitCoordinates(BarePDBParser::CoordinatesContext *ctx){
    if(!CoordinatesContext_cls) CoordinatesContext_cls = PyObject_GetAttrString(translator->parser_cls, "CoordinatesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CoordinatesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitAtom_coordinate(BarePDBParser::Atom_coordinateContext *ctx){
    if(!Atom_coordinateContext_cls) Atom_coordinateContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_coordinateContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_coordinateContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitAtom_num(BarePDBParser::Atom_numContext *ctx){
    if(!Atom_numContext_cls) Atom_numContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_numContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_numContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitAtom_name(BarePDBParser::Atom_nameContext *ctx){
    if(!Atom_nameContext_cls) Atom_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_nameContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitXyz(BarePDBParser::XyzContext *ctx){
    if(!XyzContext_cls) XyzContext_cls = PyObject_GetAttrString(translator->parser_cls, "XyzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, XyzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitX_yz(BarePDBParser::X_yzContext *ctx){
    if(!X_yzContext_cls) X_yzContext_cls = PyObject_GetAttrString(translator->parser_cls, "X_yzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, X_yzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitXy_z(BarePDBParser::Xy_zContext *ctx){
    if(!Xy_zContext_cls) Xy_zContext_cls = PyObject_GetAttrString(translator->parser_cls, "Xy_zContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Xy_zContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitX_y_z(BarePDBParser::X_y_zContext *ctx){
    if(!X_y_zContext_cls) X_y_zContext_cls = PyObject_GetAttrString(translator->parser_cls, "X_y_zContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, X_y_zContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitUndefined(BarePDBParser::UndefinedContext *ctx){
    if(!UndefinedContext_cls) UndefinedContext_cls = PyObject_GetAttrString(translator->parser_cls, "UndefinedContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, UndefinedContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitNumber(BarePDBParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitTerminal(BarePDBParser::TerminalContext *ctx){
    if(!TerminalContext_cls) TerminalContext_cls = PyObject_GetAttrString(translator->parser_cls, "TerminalContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, TerminalContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_BarePDBTranslator::visitEnd(BarePDBParser::EndContext *ctx){
    if(!EndContext_cls) EndContext_cls = PyObject_GetAttrString(translator->parser_cls, "EndContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, EndContext_cls);
    return py_ctx;
}
