/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "BiosymMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_BiosymMRTranslator : public BiosymMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Biosym_mrContext_cls = NULL;
    PyObject *Distance_restraintsContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;
    PyObject *Distance_constraintsContext_cls = NULL;
    PyObject *Distance_constraintContext_cls = NULL;
    PyObject *Dihedral_angle_restraintsContext_cls = NULL;
    PyObject *Dihedral_angle_restraintContext_cls = NULL;
    PyObject *Dihedral_angle_constraintsContext_cls = NULL;
    PyObject *Dihedral_angle_constraintContext_cls = NULL;
    PyObject *Chirality_constraintsContext_cls = NULL;
    PyObject *Chirality_constraintContext_cls = NULL;
    PyObject *Prochirality_constraintsContext_cls = NULL;
    PyObject *Prochirality_constraintContext_cls = NULL;
    PyObject *Mixing_timeContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Ins_distance_restraintsContext_cls = NULL;
    PyObject *Ins_distance_restraintContext_cls = NULL;
    PyObject *Decl_createContext_cls = NULL;
    PyObject *Decl_functionContext_cls = NULL;
    PyObject *Decl_targetContext_cls = NULL;

    public:
    SA_BiosymMRTranslator(speedy_antlr::Translator *translator);
    ~SA_BiosymMRTranslator();
    antlrcpp::Any visitBiosym_mr(BiosymMRParser::Biosym_mrContext *ctx);

    antlrcpp::Any visitDistance_restraints(BiosymMRParser::Distance_restraintsContext *ctx);

    antlrcpp::Any visitDistance_restraint(BiosymMRParser::Distance_restraintContext *ctx);

    antlrcpp::Any visitDistance_constraints(BiosymMRParser::Distance_constraintsContext *ctx);

    antlrcpp::Any visitDistance_constraint(BiosymMRParser::Distance_constraintContext *ctx);

    antlrcpp::Any visitDihedral_angle_restraints(BiosymMRParser::Dihedral_angle_restraintsContext *ctx);

    antlrcpp::Any visitDihedral_angle_restraint(BiosymMRParser::Dihedral_angle_restraintContext *ctx);

    antlrcpp::Any visitDihedral_angle_constraints(BiosymMRParser::Dihedral_angle_constraintsContext *ctx);

    antlrcpp::Any visitDihedral_angle_constraint(BiosymMRParser::Dihedral_angle_constraintContext *ctx);

    antlrcpp::Any visitChirality_constraints(BiosymMRParser::Chirality_constraintsContext *ctx);

    antlrcpp::Any visitChirality_constraint(BiosymMRParser::Chirality_constraintContext *ctx);

    antlrcpp::Any visitProchirality_constraints(BiosymMRParser::Prochirality_constraintsContext *ctx);

    antlrcpp::Any visitProchirality_constraint(BiosymMRParser::Prochirality_constraintContext *ctx);

    antlrcpp::Any visitMixing_time(BiosymMRParser::Mixing_timeContext *ctx);

    antlrcpp::Any visitNumber(BiosymMRParser::NumberContext *ctx);

    antlrcpp::Any visitIns_distance_restraints(BiosymMRParser::Ins_distance_restraintsContext *ctx);

    antlrcpp::Any visitIns_distance_restraint(BiosymMRParser::Ins_distance_restraintContext *ctx);

    antlrcpp::Any visitDecl_create(BiosymMRParser::Decl_createContext *ctx);

    antlrcpp::Any visitDecl_function(BiosymMRParser::Decl_functionContext *ctx);

    antlrcpp::Any visitDecl_target(BiosymMRParser::Decl_targetContext *ctx);

};