/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "CnsMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_CnsMRTranslator : public CnsMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Cns_mrContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;
    PyObject *Dihedral_angle_restraintContext_cls = NULL;
    PyObject *Plane_restraintContext_cls = NULL;
    PyObject *Harmonic_restraintContext_cls = NULL;
    PyObject *Rdc_restraintContext_cls = NULL;
    PyObject *Coupling_restraintContext_cls = NULL;
    PyObject *Carbon_shift_restraintContext_cls = NULL;
    PyObject *Proton_shift_restraintContext_cls = NULL;
    PyObject *Conformation_db_restraintContext_cls = NULL;
    PyObject *Diffusion_anisotropy_restraintContext_cls = NULL;
    PyObject *One_bond_coupling_restraintContext_cls = NULL;
    PyObject *Angle_db_restraintContext_cls = NULL;
    PyObject *Noe_statementContext_cls = NULL;
    PyObject *Noe_assignContext_cls = NULL;
    PyObject *Predict_statementContext_cls = NULL;
    PyObject *Noe_annotationContext_cls = NULL;
    PyObject *Dihedral_statementContext_cls = NULL;
    PyObject *Dihedral_assignContext_cls = NULL;
    PyObject *Plane_statementContext_cls = NULL;
    PyObject *Plane_groupContext_cls = NULL;
    PyObject *Group_statementContext_cls = NULL;
    PyObject *Harmonic_statementContext_cls = NULL;
    PyObject *Harmonic_assignContext_cls = NULL;
    PyObject *Sani_statementContext_cls = NULL;
    PyObject *Sani_assignContext_cls = NULL;
    PyObject *Coupling_statementContext_cls = NULL;
    PyObject *Coup_assignContext_cls = NULL;
    PyObject *Carbon_shift_statementContext_cls = NULL;
    PyObject *Carbon_shift_assignContext_cls = NULL;
    PyObject *Carbon_shift_rcoilContext_cls = NULL;
    PyObject *Proton_shift_statementContext_cls = NULL;
    PyObject *ObservedContext_cls = NULL;
    PyObject *Proton_shift_rcoilContext_cls = NULL;
    PyObject *Proton_shift_anisotropyContext_cls = NULL;
    PyObject *Proton_shift_amidesContext_cls = NULL;
    PyObject *Proton_shift_carbonsContext_cls = NULL;
    PyObject *Proton_shift_nitrogensContext_cls = NULL;
    PyObject *Proton_shift_oxygensContext_cls = NULL;
    PyObject *Proton_shift_ring_atomsContext_cls = NULL;
    PyObject *Proton_shift_alphas_and_amidesContext_cls = NULL;
    PyObject *Conformation_statementContext_cls = NULL;
    PyObject *Conf_assignContext_cls = NULL;
    PyObject *Diffusion_statementContext_cls = NULL;
    PyObject *Dani_assignContext_cls = NULL;
    PyObject *One_bond_coupling_statementContext_cls = NULL;
    PyObject *One_bond_assignContext_cls = NULL;
    PyObject *Angle_db_statementContext_cls = NULL;
    PyObject *Angle_db_assignContext_cls = NULL;
    PyObject *Ncs_restraintContext_cls = NULL;
    PyObject *Ncs_statementContext_cls = NULL;
    PyObject *Ncs_group_statementContext_cls = NULL;
    PyObject *SelectionContext_cls = NULL;
    PyObject *Selection_expressionContext_cls = NULL;
    PyObject *TermContext_cls = NULL;
    PyObject *FactorContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Number_fContext_cls = NULL;
    PyObject *Number_sContext_cls = NULL;
    PyObject *Number_aContext_cls = NULL;
    PyObject *ClassificationContext_cls = NULL;
    PyObject *Class_nameContext_cls = NULL;
    PyObject *Flag_statementContext_cls = NULL;
    PyObject *Vector_statementContext_cls = NULL;
    PyObject *Vector_modeContext_cls = NULL;
    PyObject *Vector_expressionContext_cls = NULL;
    PyObject *Vector_operationContext_cls = NULL;
    PyObject *VflcContext_cls = NULL;
    PyObject *Vector_func_callContext_cls = NULL;
    PyObject *Vector_show_propertyContext_cls = NULL;
    PyObject *Evaluate_statementContext_cls = NULL;
    PyObject *Evaluate_operationContext_cls = NULL;
    PyObject *Patch_statementContext_cls = NULL;
    PyObject *Parameter_settingContext_cls = NULL;
    PyObject *Parameter_statementContext_cls = NULL;
    PyObject *Noe_assign_loopContext_cls = NULL;
    PyObject *Dihedral_assign_loopContext_cls = NULL;
    PyObject *Sani_assign_loopContext_cls = NULL;
    PyObject *Coup_assign_loopContext_cls = NULL;
    PyObject *Carbon_shift_assign_loopContext_cls = NULL;
    PyObject *Plane_group_loopContext_cls = NULL;

    public:
    SA_CnsMRTranslator(speedy_antlr::Translator *translator);
    ~SA_CnsMRTranslator();
    antlrcpp::Any visitCns_mr(CnsMRParser::Cns_mrContext *ctx);

    antlrcpp::Any visitDistance_restraint(CnsMRParser::Distance_restraintContext *ctx);

    antlrcpp::Any visitDihedral_angle_restraint(CnsMRParser::Dihedral_angle_restraintContext *ctx);

    antlrcpp::Any visitPlane_restraint(CnsMRParser::Plane_restraintContext *ctx);

    antlrcpp::Any visitHarmonic_restraint(CnsMRParser::Harmonic_restraintContext *ctx);

    antlrcpp::Any visitRdc_restraint(CnsMRParser::Rdc_restraintContext *ctx);

    antlrcpp::Any visitCoupling_restraint(CnsMRParser::Coupling_restraintContext *ctx);

    antlrcpp::Any visitCarbon_shift_restraint(CnsMRParser::Carbon_shift_restraintContext *ctx);

    antlrcpp::Any visitProton_shift_restraint(CnsMRParser::Proton_shift_restraintContext *ctx);

    antlrcpp::Any visitConformation_db_restraint(CnsMRParser::Conformation_db_restraintContext *ctx);

    antlrcpp::Any visitDiffusion_anisotropy_restraint(CnsMRParser::Diffusion_anisotropy_restraintContext *ctx);

    antlrcpp::Any visitOne_bond_coupling_restraint(CnsMRParser::One_bond_coupling_restraintContext *ctx);

    antlrcpp::Any visitAngle_db_restraint(CnsMRParser::Angle_db_restraintContext *ctx);

    antlrcpp::Any visitNoe_statement(CnsMRParser::Noe_statementContext *ctx);

    antlrcpp::Any visitNoe_assign(CnsMRParser::Noe_assignContext *ctx);

    antlrcpp::Any visitPredict_statement(CnsMRParser::Predict_statementContext *ctx);

    antlrcpp::Any visitNoe_annotation(CnsMRParser::Noe_annotationContext *ctx);

    antlrcpp::Any visitDihedral_statement(CnsMRParser::Dihedral_statementContext *ctx);

    antlrcpp::Any visitDihedral_assign(CnsMRParser::Dihedral_assignContext *ctx);

    antlrcpp::Any visitPlane_statement(CnsMRParser::Plane_statementContext *ctx);

    antlrcpp::Any visitPlane_group(CnsMRParser::Plane_groupContext *ctx);

    antlrcpp::Any visitGroup_statement(CnsMRParser::Group_statementContext *ctx);

    antlrcpp::Any visitHarmonic_statement(CnsMRParser::Harmonic_statementContext *ctx);

    antlrcpp::Any visitHarmonic_assign(CnsMRParser::Harmonic_assignContext *ctx);

    antlrcpp::Any visitSani_statement(CnsMRParser::Sani_statementContext *ctx);

    antlrcpp::Any visitSani_assign(CnsMRParser::Sani_assignContext *ctx);

    antlrcpp::Any visitCoupling_statement(CnsMRParser::Coupling_statementContext *ctx);

    antlrcpp::Any visitCoup_assign(CnsMRParser::Coup_assignContext *ctx);

    antlrcpp::Any visitCarbon_shift_statement(CnsMRParser::Carbon_shift_statementContext *ctx);

    antlrcpp::Any visitCarbon_shift_assign(CnsMRParser::Carbon_shift_assignContext *ctx);

    antlrcpp::Any visitCarbon_shift_rcoil(CnsMRParser::Carbon_shift_rcoilContext *ctx);

    antlrcpp::Any visitProton_shift_statement(CnsMRParser::Proton_shift_statementContext *ctx);

    antlrcpp::Any visitObserved(CnsMRParser::ObservedContext *ctx);

    antlrcpp::Any visitProton_shift_rcoil(CnsMRParser::Proton_shift_rcoilContext *ctx);

    antlrcpp::Any visitProton_shift_anisotropy(CnsMRParser::Proton_shift_anisotropyContext *ctx);

    antlrcpp::Any visitProton_shift_amides(CnsMRParser::Proton_shift_amidesContext *ctx);

    antlrcpp::Any visitProton_shift_carbons(CnsMRParser::Proton_shift_carbonsContext *ctx);

    antlrcpp::Any visitProton_shift_nitrogens(CnsMRParser::Proton_shift_nitrogensContext *ctx);

    antlrcpp::Any visitProton_shift_oxygens(CnsMRParser::Proton_shift_oxygensContext *ctx);

    antlrcpp::Any visitProton_shift_ring_atoms(CnsMRParser::Proton_shift_ring_atomsContext *ctx);

    antlrcpp::Any visitProton_shift_alphas_and_amides(CnsMRParser::Proton_shift_alphas_and_amidesContext *ctx);

    antlrcpp::Any visitConformation_statement(CnsMRParser::Conformation_statementContext *ctx);

    antlrcpp::Any visitConf_assign(CnsMRParser::Conf_assignContext *ctx);

    antlrcpp::Any visitDiffusion_statement(CnsMRParser::Diffusion_statementContext *ctx);

    antlrcpp::Any visitDani_assign(CnsMRParser::Dani_assignContext *ctx);

    antlrcpp::Any visitOne_bond_coupling_statement(CnsMRParser::One_bond_coupling_statementContext *ctx);

    antlrcpp::Any visitOne_bond_assign(CnsMRParser::One_bond_assignContext *ctx);

    antlrcpp::Any visitAngle_db_statement(CnsMRParser::Angle_db_statementContext *ctx);

    antlrcpp::Any visitAngle_db_assign(CnsMRParser::Angle_db_assignContext *ctx);

    antlrcpp::Any visitNcs_restraint(CnsMRParser::Ncs_restraintContext *ctx);

    antlrcpp::Any visitNcs_statement(CnsMRParser::Ncs_statementContext *ctx);

    antlrcpp::Any visitNcs_group_statement(CnsMRParser::Ncs_group_statementContext *ctx);

    antlrcpp::Any visitSelection(CnsMRParser::SelectionContext *ctx);

    antlrcpp::Any visitSelection_expression(CnsMRParser::Selection_expressionContext *ctx);

    antlrcpp::Any visitTerm(CnsMRParser::TermContext *ctx);

    antlrcpp::Any visitFactor(CnsMRParser::FactorContext *ctx);

    antlrcpp::Any visitNumber(CnsMRParser::NumberContext *ctx);

    antlrcpp::Any visitNumber_f(CnsMRParser::Number_fContext *ctx);

    antlrcpp::Any visitNumber_s(CnsMRParser::Number_sContext *ctx);

    antlrcpp::Any visitNumber_a(CnsMRParser::Number_aContext *ctx);

    antlrcpp::Any visitClassification(CnsMRParser::ClassificationContext *ctx);

    antlrcpp::Any visitClass_name(CnsMRParser::Class_nameContext *ctx);

    antlrcpp::Any visitFlag_statement(CnsMRParser::Flag_statementContext *ctx);

    antlrcpp::Any visitVector_statement(CnsMRParser::Vector_statementContext *ctx);

    antlrcpp::Any visitVector_mode(CnsMRParser::Vector_modeContext *ctx);

    antlrcpp::Any visitVector_expression(CnsMRParser::Vector_expressionContext *ctx);

    antlrcpp::Any visitVector_operation(CnsMRParser::Vector_operationContext *ctx);

    antlrcpp::Any visitVflc(CnsMRParser::VflcContext *ctx);

    antlrcpp::Any visitVector_func_call(CnsMRParser::Vector_func_callContext *ctx);

    antlrcpp::Any visitVector_show_property(CnsMRParser::Vector_show_propertyContext *ctx);

    antlrcpp::Any visitEvaluate_statement(CnsMRParser::Evaluate_statementContext *ctx);

    antlrcpp::Any visitEvaluate_operation(CnsMRParser::Evaluate_operationContext *ctx);

    antlrcpp::Any visitPatch_statement(CnsMRParser::Patch_statementContext *ctx);

    antlrcpp::Any visitParameter_setting(CnsMRParser::Parameter_settingContext *ctx);

    antlrcpp::Any visitParameter_statement(CnsMRParser::Parameter_statementContext *ctx);

    antlrcpp::Any visitNoe_assign_loop(CnsMRParser::Noe_assign_loopContext *ctx);

    antlrcpp::Any visitDihedral_assign_loop(CnsMRParser::Dihedral_assign_loopContext *ctx);

    antlrcpp::Any visitSani_assign_loop(CnsMRParser::Sani_assign_loopContext *ctx);

    antlrcpp::Any visitCoup_assign_loop(CnsMRParser::Coup_assign_loopContext *ctx);

    antlrcpp::Any visitCarbon_shift_assign_loop(CnsMRParser::Carbon_shift_assign_loopContext *ctx);

    antlrcpp::Any visitPlane_group_loop(CnsMRParser::Plane_group_loopContext *ctx);

};