/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "CharmmCRDParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_CharmmCRDTranslator : public CharmmCRDParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Charmm_crdContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *CoordinatesContext_cls = NULL;
    PyObject *Atom_coordinateContext_cls = NULL;

    public:
    SA_CharmmCRDTranslator(speedy_antlr::Translator *translator);
    ~SA_CharmmCRDTranslator();
    antlrcpp::Any visitCharmm_crd(CharmmCRDParser::Charmm_crdContext *ctx);

    antlrcpp::Any visitComment(CharmmCRDParser::CommentContext *ctx);

    antlrcpp::Any visitCoordinates(CharmmCRDParser::CoordinatesContext *ctx);

    antlrcpp::Any visitAtom_coordinate(CharmmCRDParser::Atom_coordinateContext *ctx);

};