/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "CcpnPKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_CcpnPKTranslator : public CcpnPKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Ccpn_pkContext_cls = NULL;
    PyObject *Peak_list_2dContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_list_3dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_list_4dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *Peak_list_wo_assign_2dContext_cls = NULL;
    PyObject *Peak_wo_assign_2dContext_cls = NULL;
    PyObject *Peak_list_wo_assign_3dContext_cls = NULL;
    PyObject *Peak_wo_assign_3dContext_cls = NULL;
    PyObject *Peak_list_wo_assign_4dContext_cls = NULL;
    PyObject *Peak_wo_assign_4dContext_cls = NULL;
    PyObject *PositionContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *NoteContext_cls = NULL;

    public:
    SA_CcpnPKTranslator(speedy_antlr::Translator *translator);
    ~SA_CcpnPKTranslator();
    antlrcpp::Any visitCcpn_pk(CcpnPKParser::Ccpn_pkContext *ctx);

    antlrcpp::Any visitPeak_list_2d(CcpnPKParser::Peak_list_2dContext *ctx);

    antlrcpp::Any visitPeak_2d(CcpnPKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_list_3d(CcpnPKParser::Peak_list_3dContext *ctx);

    antlrcpp::Any visitPeak_3d(CcpnPKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_list_4d(CcpnPKParser::Peak_list_4dContext *ctx);

    antlrcpp::Any visitPeak_4d(CcpnPKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_assign_2d(CcpnPKParser::Peak_list_wo_assign_2dContext *ctx);

    antlrcpp::Any visitPeak_wo_assign_2d(CcpnPKParser::Peak_wo_assign_2dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_assign_3d(CcpnPKParser::Peak_list_wo_assign_3dContext *ctx);

    antlrcpp::Any visitPeak_wo_assign_3d(CcpnPKParser::Peak_wo_assign_3dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_assign_4d(CcpnPKParser::Peak_list_wo_assign_4dContext *ctx);

    antlrcpp::Any visitPeak_wo_assign_4d(CcpnPKParser::Peak_wo_assign_4dContext *ctx);

    antlrcpp::Any visitPosition(CcpnPKParser::PositionContext *ctx);

    antlrcpp::Any visitNumber(CcpnPKParser::NumberContext *ctx);

    antlrcpp::Any visitNote(CcpnPKParser::NoteContext *ctx);

};