/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_cyanamr_translator.h"


SA_CyanaMRTranslator::SA_CyanaMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_CyanaMRTranslator::~SA_CyanaMRTranslator() {
    Py_XDECREF(Cyana_mrContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(Distance_restraintsContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
    Py_XDECREF(Torsion_angle_restraintsContext_cls);
    Py_XDECREF(Torsion_angle_restraintContext_cls);
    Py_XDECREF(Rdc_restraintsContext_cls);
    Py_XDECREF(Rdc_parameterContext_cls);
    Py_XDECREF(Rdc_restraintContext_cls);
    Py_XDECREF(Pcs_restraintsContext_cls);
    Py_XDECREF(Pcs_parameterContext_cls);
    Py_XDECREF(Pcs_restraintContext_cls);
    Py_XDECREF(Fixres_distance_restraintsContext_cls);
    Py_XDECREF(Fixres_distance_restraintContext_cls);
    Py_XDECREF(Fixresw_distance_restraintsContext_cls);
    Py_XDECREF(Fixresw_distance_restraintContext_cls);
    Py_XDECREF(Fixresw2_distance_restraintsContext_cls);
    Py_XDECREF(Fixresw2_distance_restraintContext_cls);
    Py_XDECREF(Fixatm_distance_restraintsContext_cls);
    Py_XDECREF(Fixatm_distance_restraintContext_cls);
    Py_XDECREF(Fixatmw_distance_restraintsContext_cls);
    Py_XDECREF(Fixatmw_distance_restraintContext_cls);
    Py_XDECREF(Fixatmw2_distance_restraintsContext_cls);
    Py_XDECREF(Fixatmw2_distance_restraintContext_cls);
    Py_XDECREF(Qconvr_distance_restraintsContext_cls);
    Py_XDECREF(Qconvr_distance_restraintContext_cls);
    Py_XDECREF(Distance_w_chain_restraintsContext_cls);
    Py_XDECREF(Distance_w_chain_restraintContext_cls);
    Py_XDECREF(Distance_w_chain2_restraintsContext_cls);
    Py_XDECREF(Distance_w_chain2_restraintContext_cls);
    Py_XDECREF(Distance_w_chain3_restraintsContext_cls);
    Py_XDECREF(Distance_w_chain3_restraintContext_cls);
    Py_XDECREF(Torsion_angle_w_chain_restraintsContext_cls);
    Py_XDECREF(Torsion_angle_w_chain_restraintContext_cls);
    Py_XDECREF(Cco_restraintsContext_cls);
    Py_XDECREF(Cco_restraintContext_cls);
    Py_XDECREF(Ssbond_macroContext_cls);
    Py_XDECREF(Hbond_macroContext_cls);
    Py_XDECREF(Link_statementContext_cls);
    Py_XDECREF(Stereoassign_macroContext_cls);
    Py_XDECREF(Declare_variableContext_cls);
    Py_XDECREF(Set_variableContext_cls);
    Py_XDECREF(Unset_variableContext_cls);
    Py_XDECREF(Print_macroContext_cls);
    Py_XDECREF(Unambig_atom_name_mappingContext_cls);
    Py_XDECREF(Mapping_listContext_cls);
    Py_XDECREF(Ambig_atom_name_mappingContext_cls);
    Py_XDECREF(Ambig_listContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Gen_res_numContext_cls);
    Py_XDECREF(Gen_simple_nameContext_cls);
    Py_XDECREF(Gen_atom_nameContext_cls);
}


antlrcpp::Any SA_CyanaMRTranslator::visitCyana_mr(CyanaMRParser::Cyana_mrContext *ctx){
    if(!Cyana_mrContext_cls) Cyana_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cyana_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cyana_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitComment(CyanaMRParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_restraints(CyanaMRParser::Distance_restraintsContext *ctx){
    if(!Distance_restraintsContext_cls) Distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_restraint(CyanaMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitTorsion_angle_restraints(CyanaMRParser::Torsion_angle_restraintsContext *ctx){
    if(!Torsion_angle_restraintsContext_cls) Torsion_angle_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitTorsion_angle_restraint(CyanaMRParser::Torsion_angle_restraintContext *ctx){
    if(!Torsion_angle_restraintContext_cls) Torsion_angle_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitRdc_restraints(CyanaMRParser::Rdc_restraintsContext *ctx){
    if(!Rdc_restraintsContext_cls) Rdc_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitRdc_parameter(CyanaMRParser::Rdc_parameterContext *ctx){
    if(!Rdc_parameterContext_cls) Rdc_parameterContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_parameterContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_parameterContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitRdc_restraint(CyanaMRParser::Rdc_restraintContext *ctx){
    if(!Rdc_restraintContext_cls) Rdc_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitPcs_restraints(CyanaMRParser::Pcs_restraintsContext *ctx){
    if(!Pcs_restraintsContext_cls) Pcs_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcs_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcs_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitPcs_parameter(CyanaMRParser::Pcs_parameterContext *ctx){
    if(!Pcs_parameterContext_cls) Pcs_parameterContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcs_parameterContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcs_parameterContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitPcs_restraint(CyanaMRParser::Pcs_restraintContext *ctx){
    if(!Pcs_restraintContext_cls) Pcs_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pcs_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pcs_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixres_distance_restraints(CyanaMRParser::Fixres_distance_restraintsContext *ctx){
    if(!Fixres_distance_restraintsContext_cls) Fixres_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixres_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixres_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixres_distance_restraint(CyanaMRParser::Fixres_distance_restraintContext *ctx){
    if(!Fixres_distance_restraintContext_cls) Fixres_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixres_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixres_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixresw_distance_restraints(CyanaMRParser::Fixresw_distance_restraintsContext *ctx){
    if(!Fixresw_distance_restraintsContext_cls) Fixresw_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixresw_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixresw_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixresw_distance_restraint(CyanaMRParser::Fixresw_distance_restraintContext *ctx){
    if(!Fixresw_distance_restraintContext_cls) Fixresw_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixresw_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixresw_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixresw2_distance_restraints(CyanaMRParser::Fixresw2_distance_restraintsContext *ctx){
    if(!Fixresw2_distance_restraintsContext_cls) Fixresw2_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixresw2_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixresw2_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixresw2_distance_restraint(CyanaMRParser::Fixresw2_distance_restraintContext *ctx){
    if(!Fixresw2_distance_restraintContext_cls) Fixresw2_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixresw2_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixresw2_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatm_distance_restraints(CyanaMRParser::Fixatm_distance_restraintsContext *ctx){
    if(!Fixatm_distance_restraintsContext_cls) Fixatm_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatm_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatm_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatm_distance_restraint(CyanaMRParser::Fixatm_distance_restraintContext *ctx){
    if(!Fixatm_distance_restraintContext_cls) Fixatm_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatm_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatm_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatmw_distance_restraints(CyanaMRParser::Fixatmw_distance_restraintsContext *ctx){
    if(!Fixatmw_distance_restraintsContext_cls) Fixatmw_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatmw_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatmw_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatmw_distance_restraint(CyanaMRParser::Fixatmw_distance_restraintContext *ctx){
    if(!Fixatmw_distance_restraintContext_cls) Fixatmw_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatmw_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatmw_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatmw2_distance_restraints(CyanaMRParser::Fixatmw2_distance_restraintsContext *ctx){
    if(!Fixatmw2_distance_restraintsContext_cls) Fixatmw2_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatmw2_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatmw2_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitFixatmw2_distance_restraint(CyanaMRParser::Fixatmw2_distance_restraintContext *ctx){
    if(!Fixatmw2_distance_restraintContext_cls) Fixatmw2_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fixatmw2_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fixatmw2_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitQconvr_distance_restraints(CyanaMRParser::Qconvr_distance_restraintsContext *ctx){
    if(!Qconvr_distance_restraintsContext_cls) Qconvr_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Qconvr_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Qconvr_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitQconvr_distance_restraint(CyanaMRParser::Qconvr_distance_restraintContext *ctx){
    if(!Qconvr_distance_restraintContext_cls) Qconvr_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Qconvr_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Qconvr_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain_restraints(CyanaMRParser::Distance_w_chain_restraintsContext *ctx){
    if(!Distance_w_chain_restraintsContext_cls) Distance_w_chain_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain_restraint(CyanaMRParser::Distance_w_chain_restraintContext *ctx){
    if(!Distance_w_chain_restraintContext_cls) Distance_w_chain_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain2_restraints(CyanaMRParser::Distance_w_chain2_restraintsContext *ctx){
    if(!Distance_w_chain2_restraintsContext_cls) Distance_w_chain2_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain2_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain2_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain2_restraint(CyanaMRParser::Distance_w_chain2_restraintContext *ctx){
    if(!Distance_w_chain2_restraintContext_cls) Distance_w_chain2_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain2_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain2_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain3_restraints(CyanaMRParser::Distance_w_chain3_restraintsContext *ctx){
    if(!Distance_w_chain3_restraintsContext_cls) Distance_w_chain3_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain3_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain3_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDistance_w_chain3_restraint(CyanaMRParser::Distance_w_chain3_restraintContext *ctx){
    if(!Distance_w_chain3_restraintContext_cls) Distance_w_chain3_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_w_chain3_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_w_chain3_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitTorsion_angle_w_chain_restraints(CyanaMRParser::Torsion_angle_w_chain_restraintsContext *ctx){
    if(!Torsion_angle_w_chain_restraintsContext_cls) Torsion_angle_w_chain_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_w_chain_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_w_chain_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitTorsion_angle_w_chain_restraint(CyanaMRParser::Torsion_angle_w_chain_restraintContext *ctx){
    if(!Torsion_angle_w_chain_restraintContext_cls) Torsion_angle_w_chain_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_w_chain_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_w_chain_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitCco_restraints(CyanaMRParser::Cco_restraintsContext *ctx){
    if(!Cco_restraintsContext_cls) Cco_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cco_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cco_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitCco_restraint(CyanaMRParser::Cco_restraintContext *ctx){
    if(!Cco_restraintContext_cls) Cco_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cco_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cco_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitSsbond_macro(CyanaMRParser::Ssbond_macroContext *ctx){
    if(!Ssbond_macroContext_cls) Ssbond_macroContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ssbond_macroContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ssbond_macroContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitHbond_macro(CyanaMRParser::Hbond_macroContext *ctx){
    if(!Hbond_macroContext_cls) Hbond_macroContext_cls = PyObject_GetAttrString(translator->parser_cls, "Hbond_macroContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Hbond_macroContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitLink_statement(CyanaMRParser::Link_statementContext *ctx){
    if(!Link_statementContext_cls) Link_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Link_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Link_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitStereoassign_macro(CyanaMRParser::Stereoassign_macroContext *ctx){
    if(!Stereoassign_macroContext_cls) Stereoassign_macroContext_cls = PyObject_GetAttrString(translator->parser_cls, "Stereoassign_macroContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Stereoassign_macroContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitDeclare_variable(CyanaMRParser::Declare_variableContext *ctx){
    if(!Declare_variableContext_cls) Declare_variableContext_cls = PyObject_GetAttrString(translator->parser_cls, "Declare_variableContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Declare_variableContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitSet_variable(CyanaMRParser::Set_variableContext *ctx){
    if(!Set_variableContext_cls) Set_variableContext_cls = PyObject_GetAttrString(translator->parser_cls, "Set_variableContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Set_variableContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitUnset_variable(CyanaMRParser::Unset_variableContext *ctx){
    if(!Unset_variableContext_cls) Unset_variableContext_cls = PyObject_GetAttrString(translator->parser_cls, "Unset_variableContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Unset_variableContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitPrint_macro(CyanaMRParser::Print_macroContext *ctx){
    if(!Print_macroContext_cls) Print_macroContext_cls = PyObject_GetAttrString(translator->parser_cls, "Print_macroContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Print_macroContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitUnambig_atom_name_mapping(CyanaMRParser::Unambig_atom_name_mappingContext *ctx){
    if(!Unambig_atom_name_mappingContext_cls) Unambig_atom_name_mappingContext_cls = PyObject_GetAttrString(translator->parser_cls, "Unambig_atom_name_mappingContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Unambig_atom_name_mappingContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitMapping_list(CyanaMRParser::Mapping_listContext *ctx){
    if(!Mapping_listContext_cls) Mapping_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Mapping_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Mapping_listContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitAmbig_atom_name_mapping(CyanaMRParser::Ambig_atom_name_mappingContext *ctx){
    if(!Ambig_atom_name_mappingContext_cls) Ambig_atom_name_mappingContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ambig_atom_name_mappingContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ambig_atom_name_mappingContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitAmbig_list(CyanaMRParser::Ambig_listContext *ctx){
    if(!Ambig_listContext_cls) Ambig_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ambig_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ambig_listContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitNumber(CyanaMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitGen_res_num(CyanaMRParser::Gen_res_numContext *ctx){
    if(!Gen_res_numContext_cls) Gen_res_numContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gen_res_numContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gen_res_numContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitGen_simple_name(CyanaMRParser::Gen_simple_nameContext *ctx){
    if(!Gen_simple_nameContext_cls) Gen_simple_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gen_simple_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gen_simple_nameContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CyanaMRTranslator::visitGen_atom_name(CyanaMRParser::Gen_atom_nameContext *ctx){
    if(!Gen_atom_nameContext_cls) Gen_atom_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gen_atom_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gen_atom_nameContext_cls);
    return py_ctx;
}
