/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_ccpnpk_translator.h"


SA_CcpnPKTranslator::SA_CcpnPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_CcpnPKTranslator::~SA_CcpnPKTranslator() {
    Py_XDECREF(Ccpn_pkContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Peak_list_wo_assign_2dContext_cls);
    Py_XDECREF(Peak_wo_assign_2dContext_cls);
    Py_XDECREF(Peak_list_wo_assign_3dContext_cls);
    Py_XDECREF(Peak_wo_assign_3dContext_cls);
    Py_XDECREF(Peak_list_wo_assign_4dContext_cls);
    Py_XDECREF(Peak_wo_assign_4dContext_cls);
    Py_XDECREF(PositionContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(NoteContext_cls);
}


antlrcpp::Any SA_CcpnPKTranslator::visitCcpn_pk(CcpnPKParser::Ccpn_pkContext *ctx){
    if(!Ccpn_pkContext_cls) Ccpn_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ccpn_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ccpn_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_2d(CcpnPKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_2d(CcpnPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_3d(CcpnPKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_3d(CcpnPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_4d(CcpnPKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_4d(CcpnPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_wo_assign_2d(CcpnPKParser::Peak_list_wo_assign_2dContext *ctx){
    if(!Peak_list_wo_assign_2dContext_cls) Peak_list_wo_assign_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_assign_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_assign_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_wo_assign_2d(CcpnPKParser::Peak_wo_assign_2dContext *ctx){
    if(!Peak_wo_assign_2dContext_cls) Peak_wo_assign_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_assign_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_assign_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_wo_assign_3d(CcpnPKParser::Peak_list_wo_assign_3dContext *ctx){
    if(!Peak_list_wo_assign_3dContext_cls) Peak_list_wo_assign_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_assign_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_assign_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_wo_assign_3d(CcpnPKParser::Peak_wo_assign_3dContext *ctx){
    if(!Peak_wo_assign_3dContext_cls) Peak_wo_assign_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_assign_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_assign_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_list_wo_assign_4d(CcpnPKParser::Peak_list_wo_assign_4dContext *ctx){
    if(!Peak_list_wo_assign_4dContext_cls) Peak_list_wo_assign_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_assign_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_assign_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPeak_wo_assign_4d(CcpnPKParser::Peak_wo_assign_4dContext *ctx){
    if(!Peak_wo_assign_4dContext_cls) Peak_wo_assign_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_assign_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_assign_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitPosition(CcpnPKParser::PositionContext *ctx){
    if(!PositionContext_cls) PositionContext_cls = PyObject_GetAttrString(translator->parser_cls, "PositionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PositionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitNumber(CcpnPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_CcpnPKTranslator::visitNote(CcpnPKParser::NoteContext *ctx){
    if(!NoteContext_cls) NoteContext_cls = PyObject_GetAttrString(translator->parser_cls, "NoteContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NoteContext_cls);
    return py_ctx;
}
