/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "CharmmMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_CharmmMRTranslator : public CharmmMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Charmm_mrContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;
    PyObject *Point_distance_restraintContext_cls = NULL;
    PyObject *Dihedral_angle_restraintContext_cls = NULL;
    PyObject *Harmonic_restraintContext_cls = NULL;
    PyObject *Manipulate_internal_coordinateContext_cls = NULL;
    PyObject *Droplet_potentialContext_cls = NULL;
    PyObject *Fix_atom_constraintContext_cls = NULL;
    PyObject *Center_of_mass_constraintContext_cls = NULL;
    PyObject *Fix_bond_or_angle_constraintContext_cls = NULL;
    PyObject *Restrained_distanceContext_cls = NULL;
    PyObject *External_forceContext_cls = NULL;
    PyObject *Rmsd_restraintContext_cls = NULL;
    PyObject *Gyration_restraintContext_cls = NULL;
    PyObject *Distance_matrix_restraintContext_cls = NULL;
    PyObject *Noe_statementContext_cls = NULL;
    PyObject *Noe_assignContext_cls = NULL;
    PyObject *Pnoe_statementContext_cls = NULL;
    PyObject *Pnoe_assignContext_cls = NULL;
    PyObject *Dihedral_statementContext_cls = NULL;
    PyObject *Dihedral_assignContext_cls = NULL;
    PyObject *Harmonic_statementContext_cls = NULL;
    PyObject *Absolute_specContext_cls = NULL;
    PyObject *Force_const_specContext_cls = NULL;
    PyObject *Bestfit_specContext_cls = NULL;
    PyObject *Coordinate_specContext_cls = NULL;
    PyObject *Ic_statementContext_cls = NULL;
    PyObject *Droplet_statementContext_cls = NULL;
    PyObject *Fix_atom_statementContext_cls = NULL;
    PyObject *Center_of_mass_statementContext_cls = NULL;
    PyObject *Fix_bond_or_angle_statementContext_cls = NULL;
    PyObject *Shake_optContext_cls = NULL;
    PyObject *Fast_optContext_cls = NULL;
    PyObject *Restrained_distance_statementContext_cls = NULL;
    PyObject *External_force_statementContext_cls = NULL;
    PyObject *Rmsd_statementContext_cls = NULL;
    PyObject *Rmsd_orient_specContext_cls = NULL;
    PyObject *Rmsd_force_const_specContext_cls = NULL;
    PyObject *Rmsd_coordinate_specContext_cls = NULL;
    PyObject *Gyration_statementContext_cls = NULL;
    PyObject *Distance_matrix_statementContext_cls = NULL;
    PyObject *SelectionContext_cls = NULL;
    PyObject *Selection_expressionContext_cls = NULL;
    PyObject *TermContext_cls = NULL;
    PyObject *FactorContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Number_fContext_cls = NULL;
    PyObject *Number_sContext_cls = NULL;
    PyObject *Set_statementContext_cls = NULL;

    public:
    SA_CharmmMRTranslator(speedy_antlr::Translator *translator);
    ~SA_CharmmMRTranslator();
    antlrcpp::Any visitCharmm_mr(CharmmMRParser::Charmm_mrContext *ctx);

    antlrcpp::Any visitComment(CharmmMRParser::CommentContext *ctx);

    antlrcpp::Any visitDistance_restraint(CharmmMRParser::Distance_restraintContext *ctx);

    antlrcpp::Any visitPoint_distance_restraint(CharmmMRParser::Point_distance_restraintContext *ctx);

    antlrcpp::Any visitDihedral_angle_restraint(CharmmMRParser::Dihedral_angle_restraintContext *ctx);

    antlrcpp::Any visitHarmonic_restraint(CharmmMRParser::Harmonic_restraintContext *ctx);

    antlrcpp::Any visitManipulate_internal_coordinate(CharmmMRParser::Manipulate_internal_coordinateContext *ctx);

    antlrcpp::Any visitDroplet_potential(CharmmMRParser::Droplet_potentialContext *ctx);

    antlrcpp::Any visitFix_atom_constraint(CharmmMRParser::Fix_atom_constraintContext *ctx);

    antlrcpp::Any visitCenter_of_mass_constraint(CharmmMRParser::Center_of_mass_constraintContext *ctx);

    antlrcpp::Any visitFix_bond_or_angle_constraint(CharmmMRParser::Fix_bond_or_angle_constraintContext *ctx);

    antlrcpp::Any visitRestrained_distance(CharmmMRParser::Restrained_distanceContext *ctx);

    antlrcpp::Any visitExternal_force(CharmmMRParser::External_forceContext *ctx);

    antlrcpp::Any visitRmsd_restraint(CharmmMRParser::Rmsd_restraintContext *ctx);

    antlrcpp::Any visitGyration_restraint(CharmmMRParser::Gyration_restraintContext *ctx);

    antlrcpp::Any visitDistance_matrix_restraint(CharmmMRParser::Distance_matrix_restraintContext *ctx);

    antlrcpp::Any visitNoe_statement(CharmmMRParser::Noe_statementContext *ctx);

    antlrcpp::Any visitNoe_assign(CharmmMRParser::Noe_assignContext *ctx);

    antlrcpp::Any visitPnoe_statement(CharmmMRParser::Pnoe_statementContext *ctx);

    antlrcpp::Any visitPnoe_assign(CharmmMRParser::Pnoe_assignContext *ctx);

    antlrcpp::Any visitDihedral_statement(CharmmMRParser::Dihedral_statementContext *ctx);

    antlrcpp::Any visitDihedral_assign(CharmmMRParser::Dihedral_assignContext *ctx);

    antlrcpp::Any visitHarmonic_statement(CharmmMRParser::Harmonic_statementContext *ctx);

    antlrcpp::Any visitAbsolute_spec(CharmmMRParser::Absolute_specContext *ctx);

    antlrcpp::Any visitForce_const_spec(CharmmMRParser::Force_const_specContext *ctx);

    antlrcpp::Any visitBestfit_spec(CharmmMRParser::Bestfit_specContext *ctx);

    antlrcpp::Any visitCoordinate_spec(CharmmMRParser::Coordinate_specContext *ctx);

    antlrcpp::Any visitIc_statement(CharmmMRParser::Ic_statementContext *ctx);

    antlrcpp::Any visitDroplet_statement(CharmmMRParser::Droplet_statementContext *ctx);

    antlrcpp::Any visitFix_atom_statement(CharmmMRParser::Fix_atom_statementContext *ctx);

    antlrcpp::Any visitCenter_of_mass_statement(CharmmMRParser::Center_of_mass_statementContext *ctx);

    antlrcpp::Any visitFix_bond_or_angle_statement(CharmmMRParser::Fix_bond_or_angle_statementContext *ctx);

    antlrcpp::Any visitShake_opt(CharmmMRParser::Shake_optContext *ctx);

    antlrcpp::Any visitFast_opt(CharmmMRParser::Fast_optContext *ctx);

    antlrcpp::Any visitRestrained_distance_statement(CharmmMRParser::Restrained_distance_statementContext *ctx);

    antlrcpp::Any visitExternal_force_statement(CharmmMRParser::External_force_statementContext *ctx);

    antlrcpp::Any visitRmsd_statement(CharmmMRParser::Rmsd_statementContext *ctx);

    antlrcpp::Any visitRmsd_orient_spec(CharmmMRParser::Rmsd_orient_specContext *ctx);

    antlrcpp::Any visitRmsd_force_const_spec(CharmmMRParser::Rmsd_force_const_specContext *ctx);

    antlrcpp::Any visitRmsd_coordinate_spec(CharmmMRParser::Rmsd_coordinate_specContext *ctx);

    antlrcpp::Any visitGyration_statement(CharmmMRParser::Gyration_statementContext *ctx);

    antlrcpp::Any visitDistance_matrix_statement(CharmmMRParser::Distance_matrix_statementContext *ctx);

    antlrcpp::Any visitSelection(CharmmMRParser::SelectionContext *ctx);

    antlrcpp::Any visitSelection_expression(CharmmMRParser::Selection_expressionContext *ctx);

    antlrcpp::Any visitTerm(CharmmMRParser::TermContext *ctx);

    antlrcpp::Any visitFactor(CharmmMRParser::FactorContext *ctx);

    antlrcpp::Any visitNumber(CharmmMRParser::NumberContext *ctx);

    antlrcpp::Any visitNumber_f(CharmmMRParser::Number_fContext *ctx);

    antlrcpp::Any visitNumber_s(CharmmMRParser::Number_sContext *ctx);

    antlrcpp::Any visitSet_statement(CharmmMRParser::Set_statementContext *ctx);

};