/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "CyanaMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_CyanaMRTranslator : public CyanaMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Cyana_mrContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *Distance_restraintsContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;
    PyObject *Torsion_angle_restraintsContext_cls = NULL;
    PyObject *Torsion_angle_restraintContext_cls = NULL;
    PyObject *Rdc_restraintsContext_cls = NULL;
    PyObject *Rdc_parameterContext_cls = NULL;
    PyObject *Rdc_restraintContext_cls = NULL;
    PyObject *Pcs_restraintsContext_cls = NULL;
    PyObject *Pcs_parameterContext_cls = NULL;
    PyObject *Pcs_restraintContext_cls = NULL;
    PyObject *Fixres_distance_restraintsContext_cls = NULL;
    PyObject *Fixres_distance_restraintContext_cls = NULL;
    PyObject *Fixresw_distance_restraintsContext_cls = NULL;
    PyObject *Fixresw_distance_restraintContext_cls = NULL;
    PyObject *Fixresw2_distance_restraintsContext_cls = NULL;
    PyObject *Fixresw2_distance_restraintContext_cls = NULL;
    PyObject *Fixatm_distance_restraintsContext_cls = NULL;
    PyObject *Fixatm_distance_restraintContext_cls = NULL;
    PyObject *Fixatmw_distance_restraintsContext_cls = NULL;
    PyObject *Fixatmw_distance_restraintContext_cls = NULL;
    PyObject *Fixatmw2_distance_restraintsContext_cls = NULL;
    PyObject *Fixatmw2_distance_restraintContext_cls = NULL;
    PyObject *Qconvr_distance_restraintsContext_cls = NULL;
    PyObject *Qconvr_distance_restraintContext_cls = NULL;
    PyObject *Distance_w_chain_restraintsContext_cls = NULL;
    PyObject *Distance_w_chain_restraintContext_cls = NULL;
    PyObject *Distance_w_chain2_restraintsContext_cls = NULL;
    PyObject *Distance_w_chain2_restraintContext_cls = NULL;
    PyObject *Distance_w_chain3_restraintsContext_cls = NULL;
    PyObject *Distance_w_chain3_restraintContext_cls = NULL;
    PyObject *Torsion_angle_w_chain_restraintsContext_cls = NULL;
    PyObject *Torsion_angle_w_chain_restraintContext_cls = NULL;
    PyObject *Cco_restraintsContext_cls = NULL;
    PyObject *Cco_restraintContext_cls = NULL;
    PyObject *Ssbond_macroContext_cls = NULL;
    PyObject *Hbond_macroContext_cls = NULL;
    PyObject *Link_statementContext_cls = NULL;
    PyObject *Stereoassign_macroContext_cls = NULL;
    PyObject *Declare_variableContext_cls = NULL;
    PyObject *Set_variableContext_cls = NULL;
    PyObject *Unset_variableContext_cls = NULL;
    PyObject *Print_macroContext_cls = NULL;
    PyObject *Unambig_atom_name_mappingContext_cls = NULL;
    PyObject *Mapping_listContext_cls = NULL;
    PyObject *Ambig_atom_name_mappingContext_cls = NULL;
    PyObject *Ambig_listContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Gen_res_numContext_cls = NULL;
    PyObject *Gen_simple_nameContext_cls = NULL;
    PyObject *Gen_atom_nameContext_cls = NULL;

    public:
    SA_CyanaMRTranslator(speedy_antlr::Translator *translator);
    ~SA_CyanaMRTranslator();
    antlrcpp::Any visitCyana_mr(CyanaMRParser::Cyana_mrContext *ctx);

    antlrcpp::Any visitComment(CyanaMRParser::CommentContext *ctx);

    antlrcpp::Any visitDistance_restraints(CyanaMRParser::Distance_restraintsContext *ctx);

    antlrcpp::Any visitDistance_restraint(CyanaMRParser::Distance_restraintContext *ctx);

    antlrcpp::Any visitTorsion_angle_restraints(CyanaMRParser::Torsion_angle_restraintsContext *ctx);

    antlrcpp::Any visitTorsion_angle_restraint(CyanaMRParser::Torsion_angle_restraintContext *ctx);

    antlrcpp::Any visitRdc_restraints(CyanaMRParser::Rdc_restraintsContext *ctx);

    antlrcpp::Any visitRdc_parameter(CyanaMRParser::Rdc_parameterContext *ctx);

    antlrcpp::Any visitRdc_restraint(CyanaMRParser::Rdc_restraintContext *ctx);

    antlrcpp::Any visitPcs_restraints(CyanaMRParser::Pcs_restraintsContext *ctx);

    antlrcpp::Any visitPcs_parameter(CyanaMRParser::Pcs_parameterContext *ctx);

    antlrcpp::Any visitPcs_restraint(CyanaMRParser::Pcs_restraintContext *ctx);

    antlrcpp::Any visitFixres_distance_restraints(CyanaMRParser::Fixres_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixres_distance_restraint(CyanaMRParser::Fixres_distance_restraintContext *ctx);

    antlrcpp::Any visitFixresw_distance_restraints(CyanaMRParser::Fixresw_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixresw_distance_restraint(CyanaMRParser::Fixresw_distance_restraintContext *ctx);

    antlrcpp::Any visitFixresw2_distance_restraints(CyanaMRParser::Fixresw2_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixresw2_distance_restraint(CyanaMRParser::Fixresw2_distance_restraintContext *ctx);

    antlrcpp::Any visitFixatm_distance_restraints(CyanaMRParser::Fixatm_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixatm_distance_restraint(CyanaMRParser::Fixatm_distance_restraintContext *ctx);

    antlrcpp::Any visitFixatmw_distance_restraints(CyanaMRParser::Fixatmw_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixatmw_distance_restraint(CyanaMRParser::Fixatmw_distance_restraintContext *ctx);

    antlrcpp::Any visitFixatmw2_distance_restraints(CyanaMRParser::Fixatmw2_distance_restraintsContext *ctx);

    antlrcpp::Any visitFixatmw2_distance_restraint(CyanaMRParser::Fixatmw2_distance_restraintContext *ctx);

    antlrcpp::Any visitQconvr_distance_restraints(CyanaMRParser::Qconvr_distance_restraintsContext *ctx);

    antlrcpp::Any visitQconvr_distance_restraint(CyanaMRParser::Qconvr_distance_restraintContext *ctx);

    antlrcpp::Any visitDistance_w_chain_restraints(CyanaMRParser::Distance_w_chain_restraintsContext *ctx);

    antlrcpp::Any visitDistance_w_chain_restraint(CyanaMRParser::Distance_w_chain_restraintContext *ctx);

    antlrcpp::Any visitDistance_w_chain2_restraints(CyanaMRParser::Distance_w_chain2_restraintsContext *ctx);

    antlrcpp::Any visitDistance_w_chain2_restraint(CyanaMRParser::Distance_w_chain2_restraintContext *ctx);

    antlrcpp::Any visitDistance_w_chain3_restraints(CyanaMRParser::Distance_w_chain3_restraintsContext *ctx);

    antlrcpp::Any visitDistance_w_chain3_restraint(CyanaMRParser::Distance_w_chain3_restraintContext *ctx);

    antlrcpp::Any visitTorsion_angle_w_chain_restraints(CyanaMRParser::Torsion_angle_w_chain_restraintsContext *ctx);

    antlrcpp::Any visitTorsion_angle_w_chain_restraint(CyanaMRParser::Torsion_angle_w_chain_restraintContext *ctx);

    antlrcpp::Any visitCco_restraints(CyanaMRParser::Cco_restraintsContext *ctx);

    antlrcpp::Any visitCco_restraint(CyanaMRParser::Cco_restraintContext *ctx);

    antlrcpp::Any visitSsbond_macro(CyanaMRParser::Ssbond_macroContext *ctx);

    antlrcpp::Any visitHbond_macro(CyanaMRParser::Hbond_macroContext *ctx);

    antlrcpp::Any visitLink_statement(CyanaMRParser::Link_statementContext *ctx);

    antlrcpp::Any visitStereoassign_macro(CyanaMRParser::Stereoassign_macroContext *ctx);

    antlrcpp::Any visitDeclare_variable(CyanaMRParser::Declare_variableContext *ctx);

    antlrcpp::Any visitSet_variable(CyanaMRParser::Set_variableContext *ctx);

    antlrcpp::Any visitUnset_variable(CyanaMRParser::Unset_variableContext *ctx);

    antlrcpp::Any visitPrint_macro(CyanaMRParser::Print_macroContext *ctx);

    antlrcpp::Any visitUnambig_atom_name_mapping(CyanaMRParser::Unambig_atom_name_mappingContext *ctx);

    antlrcpp::Any visitMapping_list(CyanaMRParser::Mapping_listContext *ctx);

    antlrcpp::Any visitAmbig_atom_name_mapping(CyanaMRParser::Ambig_atom_name_mappingContext *ctx);

    antlrcpp::Any visitAmbig_list(CyanaMRParser::Ambig_listContext *ctx);

    antlrcpp::Any visitNumber(CyanaMRParser::NumberContext *ctx);

    antlrcpp::Any visitGen_res_num(CyanaMRParser::Gen_res_numContext *ctx);

    antlrcpp::Any visitGen_simple_name(CyanaMRParser::Gen_simple_nameContext *ctx);

    antlrcpp::Any visitGen_atom_name(CyanaMRParser::Gen_atom_nameContext *ctx);

};