/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_dynamomr_translator.h"


SA_DynamoMRTranslator::SA_DynamoMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_DynamoMRTranslator::~SA_DynamoMRTranslator() {
    Py_XDECREF(Dynamo_mrContext_cls);
    Py_XDECREF(SequenceContext_cls);
    Py_XDECREF(Distance_restraintsContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
    Py_XDECREF(Distance_restraints_sw_segidContext_cls);
    Py_XDECREF(Distance_restraint_sw_segidContext_cls);
    Py_XDECREF(Distance_restraints_ew_segidContext_cls);
    Py_XDECREF(Distance_restraint_ew_segidContext_cls);
    Py_XDECREF(Torsion_angle_restraintsContext_cls);
    Py_XDECREF(Torsion_angle_restraintContext_cls);
    Py_XDECREF(Torsion_angle_restraints_sw_segidContext_cls);
    Py_XDECREF(Torsion_angle_restraint_sw_segidContext_cls);
    Py_XDECREF(Torsion_angle_restraints_ew_segidContext_cls);
    Py_XDECREF(Torsion_angle_restraint_ew_segidContext_cls);
    Py_XDECREF(Rdc_restraintsContext_cls);
    Py_XDECREF(Rdc_restraintContext_cls);
    Py_XDECREF(Rdc_restraints_sw_segidContext_cls);
    Py_XDECREF(Rdc_restraint_sw_segidContext_cls);
    Py_XDECREF(Rdc_restraints_ew_segidContext_cls);
    Py_XDECREF(Rdc_restraint_ew_segidContext_cls);
    Py_XDECREF(Pales_meta_outputsContext_cls);
    Py_XDECREF(Pales_rdc_outputsContext_cls);
    Py_XDECREF(Pales_rdc_outputContext_cls);
    Py_XDECREF(Coupling_restraintsContext_cls);
    Py_XDECREF(Coupling_restraintContext_cls);
    Py_XDECREF(Coupling_restraints_sw_segidContext_cls);
    Py_XDECREF(Coupling_restraint_sw_segidContext_cls);
    Py_XDECREF(Coupling_restraints_ew_segidContext_cls);
    Py_XDECREF(Coupling_restraint_ew_segidContext_cls);
    Py_XDECREF(Talos_restraintsContext_cls);
    Py_XDECREF(Talos_restraintContext_cls);
    Py_XDECREF(Talos_restraints_wo_s2Context_cls);
    Py_XDECREF(Talos_restraint_wo_s2Context_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_DynamoMRTranslator::visitDynamo_mr(DynamoMRParser::Dynamo_mrContext *ctx){
    if(!Dynamo_mrContext_cls) Dynamo_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dynamo_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dynamo_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitSequence(DynamoMRParser::SequenceContext *ctx){
    if(!SequenceContext_cls) SequenceContext_cls = PyObject_GetAttrString(translator->parser_cls, "SequenceContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SequenceContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraints(DynamoMRParser::Distance_restraintsContext *ctx){
    if(!Distance_restraintsContext_cls) Distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraint(DynamoMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraints_sw_segid(DynamoMRParser::Distance_restraints_sw_segidContext *ctx){
    if(!Distance_restraints_sw_segidContext_cls) Distance_restraints_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraints_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraints_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraint_sw_segid(DynamoMRParser::Distance_restraint_sw_segidContext *ctx){
    if(!Distance_restraint_sw_segidContext_cls) Distance_restraint_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraint_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraint_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraints_ew_segid(DynamoMRParser::Distance_restraints_ew_segidContext *ctx){
    if(!Distance_restraints_ew_segidContext_cls) Distance_restraints_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraints_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraints_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitDistance_restraint_ew_segid(DynamoMRParser::Distance_restraint_ew_segidContext *ctx){
    if(!Distance_restraint_ew_segidContext_cls) Distance_restraint_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraint_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraint_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraints(DynamoMRParser::Torsion_angle_restraintsContext *ctx){
    if(!Torsion_angle_restraintsContext_cls) Torsion_angle_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraint(DynamoMRParser::Torsion_angle_restraintContext *ctx){
    if(!Torsion_angle_restraintContext_cls) Torsion_angle_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraints_sw_segid(DynamoMRParser::Torsion_angle_restraints_sw_segidContext *ctx){
    if(!Torsion_angle_restraints_sw_segidContext_cls) Torsion_angle_restraints_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraints_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraints_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraint_sw_segid(DynamoMRParser::Torsion_angle_restraint_sw_segidContext *ctx){
    if(!Torsion_angle_restraint_sw_segidContext_cls) Torsion_angle_restraint_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraint_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraint_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraints_ew_segid(DynamoMRParser::Torsion_angle_restraints_ew_segidContext *ctx){
    if(!Torsion_angle_restraints_ew_segidContext_cls) Torsion_angle_restraints_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraints_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraints_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTorsion_angle_restraint_ew_segid(DynamoMRParser::Torsion_angle_restraint_ew_segidContext *ctx){
    if(!Torsion_angle_restraint_ew_segidContext_cls) Torsion_angle_restraint_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Torsion_angle_restraint_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Torsion_angle_restraint_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraints(DynamoMRParser::Rdc_restraintsContext *ctx){
    if(!Rdc_restraintsContext_cls) Rdc_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraint(DynamoMRParser::Rdc_restraintContext *ctx){
    if(!Rdc_restraintContext_cls) Rdc_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraints_sw_segid(DynamoMRParser::Rdc_restraints_sw_segidContext *ctx){
    if(!Rdc_restraints_sw_segidContext_cls) Rdc_restraints_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraints_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraints_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraint_sw_segid(DynamoMRParser::Rdc_restraint_sw_segidContext *ctx){
    if(!Rdc_restraint_sw_segidContext_cls) Rdc_restraint_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraint_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraint_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraints_ew_segid(DynamoMRParser::Rdc_restraints_ew_segidContext *ctx){
    if(!Rdc_restraints_ew_segidContext_cls) Rdc_restraints_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraints_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraints_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitRdc_restraint_ew_segid(DynamoMRParser::Rdc_restraint_ew_segidContext *ctx){
    if(!Rdc_restraint_ew_segidContext_cls) Rdc_restraint_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraint_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraint_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitPales_meta_outputs(DynamoMRParser::Pales_meta_outputsContext *ctx){
    if(!Pales_meta_outputsContext_cls) Pales_meta_outputsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pales_meta_outputsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pales_meta_outputsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitPales_rdc_outputs(DynamoMRParser::Pales_rdc_outputsContext *ctx){
    if(!Pales_rdc_outputsContext_cls) Pales_rdc_outputsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pales_rdc_outputsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pales_rdc_outputsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitPales_rdc_output(DynamoMRParser::Pales_rdc_outputContext *ctx){
    if(!Pales_rdc_outputContext_cls) Pales_rdc_outputContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pales_rdc_outputContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pales_rdc_outputContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraints(DynamoMRParser::Coupling_restraintsContext *ctx){
    if(!Coupling_restraintsContext_cls) Coupling_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraint(DynamoMRParser::Coupling_restraintContext *ctx){
    if(!Coupling_restraintContext_cls) Coupling_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraints_sw_segid(DynamoMRParser::Coupling_restraints_sw_segidContext *ctx){
    if(!Coupling_restraints_sw_segidContext_cls) Coupling_restraints_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraints_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraints_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraint_sw_segid(DynamoMRParser::Coupling_restraint_sw_segidContext *ctx){
    if(!Coupling_restraint_sw_segidContext_cls) Coupling_restraint_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraint_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraint_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraints_ew_segid(DynamoMRParser::Coupling_restraints_ew_segidContext *ctx){
    if(!Coupling_restraints_ew_segidContext_cls) Coupling_restraints_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraints_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraints_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitCoupling_restraint_ew_segid(DynamoMRParser::Coupling_restraint_ew_segidContext *ctx){
    if(!Coupling_restraint_ew_segidContext_cls) Coupling_restraint_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coupling_restraint_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coupling_restraint_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTalos_restraints(DynamoMRParser::Talos_restraintsContext *ctx){
    if(!Talos_restraintsContext_cls) Talos_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Talos_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Talos_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTalos_restraint(DynamoMRParser::Talos_restraintContext *ctx){
    if(!Talos_restraintContext_cls) Talos_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Talos_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Talos_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTalos_restraints_wo_s2(DynamoMRParser::Talos_restraints_wo_s2Context *ctx){
    if(!Talos_restraints_wo_s2Context_cls) Talos_restraints_wo_s2Context_cls = PyObject_GetAttrString(translator->parser_cls, "Talos_restraints_wo_s2Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Talos_restraints_wo_s2Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitTalos_restraint_wo_s2(DynamoMRParser::Talos_restraint_wo_s2Context *ctx){
    if(!Talos_restraint_wo_s2Context_cls) Talos_restraint_wo_s2Context_cls = PyObject_GetAttrString(translator->parser_cls, "Talos_restraint_wo_s2Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Talos_restraint_wo_s2Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_DynamoMRTranslator::visitNumber(DynamoMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
