/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_gromacspt_translator.h"


SA_GromacsPTTranslator::SA_GromacsPTTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_GromacsPTTranslator::~SA_GromacsPTTranslator() {
    Py_XDECREF(Gromacs_ptContext_cls);
    Py_XDECREF(Default_statementContext_cls);
    Py_XDECREF(Moleculetype_statementContext_cls);
    Py_XDECREF(MoleculetypeContext_cls);
    Py_XDECREF(Atomtypes_statementContext_cls);
    Py_XDECREF(AtomtypesContext_cls);
    Py_XDECREF(Pairtypes_statementContext_cls);
    Py_XDECREF(PairtypesContext_cls);
    Py_XDECREF(Bondtypes_statementContext_cls);
    Py_XDECREF(BondtypesContext_cls);
    Py_XDECREF(Angletypes_statementContext_cls);
    Py_XDECREF(AngletypesContext_cls);
    Py_XDECREF(Dihedraltypes_statementContext_cls);
    Py_XDECREF(DihedraltypesContext_cls);
    Py_XDECREF(Constrainttypes_statementContext_cls);
    Py_XDECREF(ConstrainttypesContext_cls);
    Py_XDECREF(Nonbonded_params_statementContext_cls);
    Py_XDECREF(Nonbonded_paramsContext_cls);
    Py_XDECREF(Atoms_statementContext_cls);
    Py_XDECREF(AtomsContext_cls);
    Py_XDECREF(Bonds_statementContext_cls);
    Py_XDECREF(BondsContext_cls);
    Py_XDECREF(Pairs_statementContext_cls);
    Py_XDECREF(PairsContext_cls);
    Py_XDECREF(Pairs_nb_statementContext_cls);
    Py_XDECREF(Pairs_nbContext_cls);
    Py_XDECREF(Angles_statementContext_cls);
    Py_XDECREF(AnglesContext_cls);
    Py_XDECREF(Dihedrals_statementContext_cls);
    Py_XDECREF(DihedralsContext_cls);
    Py_XDECREF(Exclusions_statementContext_cls);
    Py_XDECREF(ExclusionsContext_cls);
    Py_XDECREF(Constraints_statementContext_cls);
    Py_XDECREF(ConstraintsContext_cls);
    Py_XDECREF(Settles_statementContext_cls);
    Py_XDECREF(SettlesContext_cls);
    Py_XDECREF(Virtual_sites1_statementContext_cls);
    Py_XDECREF(Virtual_sites1Context_cls);
    Py_XDECREF(Virtual_sites2_statementContext_cls);
    Py_XDECREF(Virtual_sites2Context_cls);
    Py_XDECREF(Virtual_sites3_statementContext_cls);
    Py_XDECREF(Virtual_sites3Context_cls);
    Py_XDECREF(Virtual_sites4_statementContext_cls);
    Py_XDECREF(Virtual_sites4Context_cls);
    Py_XDECREF(Virtual_sitesn_statementContext_cls);
    Py_XDECREF(Virtual_sitesnContext_cls);
    Py_XDECREF(System_statementContext_cls);
    Py_XDECREF(Molecules_statementContext_cls);
    Py_XDECREF(MoleculesContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Position_restraintsContext_cls);
    Py_XDECREF(Position_restraintContext_cls);
}


antlrcpp::Any SA_GromacsPTTranslator::visitGromacs_pt(GromacsPTParser::Gromacs_ptContext *ctx){
    if(!Gromacs_ptContext_cls) Gromacs_ptContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gromacs_ptContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gromacs_ptContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitDefault_statement(GromacsPTParser::Default_statementContext *ctx){
    if(!Default_statementContext_cls) Default_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Default_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Default_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitMoleculetype_statement(GromacsPTParser::Moleculetype_statementContext *ctx){
    if(!Moleculetype_statementContext_cls) Moleculetype_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Moleculetype_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Moleculetype_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitMoleculetype(GromacsPTParser::MoleculetypeContext *ctx){
    if(!MoleculetypeContext_cls) MoleculetypeContext_cls = PyObject_GetAttrString(translator->parser_cls, "MoleculetypeContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, MoleculetypeContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAtomtypes_statement(GromacsPTParser::Atomtypes_statementContext *ctx){
    if(!Atomtypes_statementContext_cls) Atomtypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atomtypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atomtypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAtomtypes(GromacsPTParser::AtomtypesContext *ctx){
    if(!AtomtypesContext_cls) AtomtypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "AtomtypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AtomtypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairtypes_statement(GromacsPTParser::Pairtypes_statementContext *ctx){
    if(!Pairtypes_statementContext_cls) Pairtypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pairtypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pairtypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairtypes(GromacsPTParser::PairtypesContext *ctx){
    if(!PairtypesContext_cls) PairtypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "PairtypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PairtypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitBondtypes_statement(GromacsPTParser::Bondtypes_statementContext *ctx){
    if(!Bondtypes_statementContext_cls) Bondtypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bondtypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bondtypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitBondtypes(GromacsPTParser::BondtypesContext *ctx){
    if(!BondtypesContext_cls) BondtypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "BondtypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, BondtypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAngletypes_statement(GromacsPTParser::Angletypes_statementContext *ctx){
    if(!Angletypes_statementContext_cls) Angletypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angletypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angletypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAngletypes(GromacsPTParser::AngletypesContext *ctx){
    if(!AngletypesContext_cls) AngletypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "AngletypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AngletypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitDihedraltypes_statement(GromacsPTParser::Dihedraltypes_statementContext *ctx){
    if(!Dihedraltypes_statementContext_cls) Dihedraltypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedraltypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedraltypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitDihedraltypes(GromacsPTParser::DihedraltypesContext *ctx){
    if(!DihedraltypesContext_cls) DihedraltypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "DihedraltypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, DihedraltypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitConstrainttypes_statement(GromacsPTParser::Constrainttypes_statementContext *ctx){
    if(!Constrainttypes_statementContext_cls) Constrainttypes_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Constrainttypes_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Constrainttypes_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitConstrainttypes(GromacsPTParser::ConstrainttypesContext *ctx){
    if(!ConstrainttypesContext_cls) ConstrainttypesContext_cls = PyObject_GetAttrString(translator->parser_cls, "ConstrainttypesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ConstrainttypesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitNonbonded_params_statement(GromacsPTParser::Nonbonded_params_statementContext *ctx){
    if(!Nonbonded_params_statementContext_cls) Nonbonded_params_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nonbonded_params_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nonbonded_params_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitNonbonded_params(GromacsPTParser::Nonbonded_paramsContext *ctx){
    if(!Nonbonded_paramsContext_cls) Nonbonded_paramsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nonbonded_paramsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nonbonded_paramsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAtoms_statement(GromacsPTParser::Atoms_statementContext *ctx){
    if(!Atoms_statementContext_cls) Atoms_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atoms_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atoms_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAtoms(GromacsPTParser::AtomsContext *ctx){
    if(!AtomsContext_cls) AtomsContext_cls = PyObject_GetAttrString(translator->parser_cls, "AtomsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AtomsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitBonds_statement(GromacsPTParser::Bonds_statementContext *ctx){
    if(!Bonds_statementContext_cls) Bonds_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Bonds_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Bonds_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitBonds(GromacsPTParser::BondsContext *ctx){
    if(!BondsContext_cls) BondsContext_cls = PyObject_GetAttrString(translator->parser_cls, "BondsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, BondsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairs_statement(GromacsPTParser::Pairs_statementContext *ctx){
    if(!Pairs_statementContext_cls) Pairs_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pairs_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pairs_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairs(GromacsPTParser::PairsContext *ctx){
    if(!PairsContext_cls) PairsContext_cls = PyObject_GetAttrString(translator->parser_cls, "PairsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PairsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairs_nb_statement(GromacsPTParser::Pairs_nb_statementContext *ctx){
    if(!Pairs_nb_statementContext_cls) Pairs_nb_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pairs_nb_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pairs_nb_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPairs_nb(GromacsPTParser::Pairs_nbContext *ctx){
    if(!Pairs_nbContext_cls) Pairs_nbContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pairs_nbContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pairs_nbContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAngles_statement(GromacsPTParser::Angles_statementContext *ctx){
    if(!Angles_statementContext_cls) Angles_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angles_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angles_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitAngles(GromacsPTParser::AnglesContext *ctx){
    if(!AnglesContext_cls) AnglesContext_cls = PyObject_GetAttrString(translator->parser_cls, "AnglesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AnglesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitDihedrals_statement(GromacsPTParser::Dihedrals_statementContext *ctx){
    if(!Dihedrals_statementContext_cls) Dihedrals_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedrals_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedrals_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitDihedrals(GromacsPTParser::DihedralsContext *ctx){
    if(!DihedralsContext_cls) DihedralsContext_cls = PyObject_GetAttrString(translator->parser_cls, "DihedralsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, DihedralsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitExclusions_statement(GromacsPTParser::Exclusions_statementContext *ctx){
    if(!Exclusions_statementContext_cls) Exclusions_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Exclusions_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Exclusions_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitExclusions(GromacsPTParser::ExclusionsContext *ctx){
    if(!ExclusionsContext_cls) ExclusionsContext_cls = PyObject_GetAttrString(translator->parser_cls, "ExclusionsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ExclusionsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitConstraints_statement(GromacsPTParser::Constraints_statementContext *ctx){
    if(!Constraints_statementContext_cls) Constraints_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Constraints_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Constraints_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitConstraints(GromacsPTParser::ConstraintsContext *ctx){
    if(!ConstraintsContext_cls) ConstraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "ConstraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ConstraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitSettles_statement(GromacsPTParser::Settles_statementContext *ctx){
    if(!Settles_statementContext_cls) Settles_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Settles_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Settles_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitSettles(GromacsPTParser::SettlesContext *ctx){
    if(!SettlesContext_cls) SettlesContext_cls = PyObject_GetAttrString(translator->parser_cls, "SettlesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SettlesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites1_statement(GromacsPTParser::Virtual_sites1_statementContext *ctx){
    if(!Virtual_sites1_statementContext_cls) Virtual_sites1_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites1_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites1_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites1(GromacsPTParser::Virtual_sites1Context *ctx){
    if(!Virtual_sites1Context_cls) Virtual_sites1Context_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites1Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites1Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites2_statement(GromacsPTParser::Virtual_sites2_statementContext *ctx){
    if(!Virtual_sites2_statementContext_cls) Virtual_sites2_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites2_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites2_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites2(GromacsPTParser::Virtual_sites2Context *ctx){
    if(!Virtual_sites2Context_cls) Virtual_sites2Context_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites2Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites2Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites3_statement(GromacsPTParser::Virtual_sites3_statementContext *ctx){
    if(!Virtual_sites3_statementContext_cls) Virtual_sites3_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites3_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites3_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites3(GromacsPTParser::Virtual_sites3Context *ctx){
    if(!Virtual_sites3Context_cls) Virtual_sites3Context_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites3Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites3Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites4_statement(GromacsPTParser::Virtual_sites4_statementContext *ctx){
    if(!Virtual_sites4_statementContext_cls) Virtual_sites4_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites4_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites4_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sites4(GromacsPTParser::Virtual_sites4Context *ctx){
    if(!Virtual_sites4Context_cls) Virtual_sites4Context_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sites4Context");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sites4Context_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sitesn_statement(GromacsPTParser::Virtual_sitesn_statementContext *ctx){
    if(!Virtual_sitesn_statementContext_cls) Virtual_sitesn_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sitesn_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sitesn_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitVirtual_sitesn(GromacsPTParser::Virtual_sitesnContext *ctx){
    if(!Virtual_sitesnContext_cls) Virtual_sitesnContext_cls = PyObject_GetAttrString(translator->parser_cls, "Virtual_sitesnContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Virtual_sitesnContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitSystem_statement(GromacsPTParser::System_statementContext *ctx){
    if(!System_statementContext_cls) System_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "System_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, System_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitMolecules_statement(GromacsPTParser::Molecules_statementContext *ctx){
    if(!Molecules_statementContext_cls) Molecules_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Molecules_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Molecules_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitMolecules(GromacsPTParser::MoleculesContext *ctx){
    if(!MoleculesContext_cls) MoleculesContext_cls = PyObject_GetAttrString(translator->parser_cls, "MoleculesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, MoleculesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitNumber(GromacsPTParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPosition_restraints(GromacsPTParser::Position_restraintsContext *ctx){
    if(!Position_restraintsContext_cls) Position_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Position_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Position_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_GromacsPTTranslator::visitPosition_restraint(GromacsPTParser::Position_restraintContext *ctx){
    if(!Position_restraintContext_cls) Position_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Position_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Position_restraintContext_cls);
    return py_ctx;
}
