/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "GromacsPTParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_GromacsPTTranslator : public GromacsPTParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Gromacs_ptContext_cls = NULL;
    PyObject *Default_statementContext_cls = NULL;
    PyObject *Moleculetype_statementContext_cls = NULL;
    PyObject *MoleculetypeContext_cls = NULL;
    PyObject *Atomtypes_statementContext_cls = NULL;
    PyObject *AtomtypesContext_cls = NULL;
    PyObject *Pairtypes_statementContext_cls = NULL;
    PyObject *PairtypesContext_cls = NULL;
    PyObject *Bondtypes_statementContext_cls = NULL;
    PyObject *BondtypesContext_cls = NULL;
    PyObject *Angletypes_statementContext_cls = NULL;
    PyObject *AngletypesContext_cls = NULL;
    PyObject *Dihedraltypes_statementContext_cls = NULL;
    PyObject *DihedraltypesContext_cls = NULL;
    PyObject *Constrainttypes_statementContext_cls = NULL;
    PyObject *ConstrainttypesContext_cls = NULL;
    PyObject *Nonbonded_params_statementContext_cls = NULL;
    PyObject *Nonbonded_paramsContext_cls = NULL;
    PyObject *Atoms_statementContext_cls = NULL;
    PyObject *AtomsContext_cls = NULL;
    PyObject *Bonds_statementContext_cls = NULL;
    PyObject *BondsContext_cls = NULL;
    PyObject *Pairs_statementContext_cls = NULL;
    PyObject *PairsContext_cls = NULL;
    PyObject *Pairs_nb_statementContext_cls = NULL;
    PyObject *Pairs_nbContext_cls = NULL;
    PyObject *Angles_statementContext_cls = NULL;
    PyObject *AnglesContext_cls = NULL;
    PyObject *Dihedrals_statementContext_cls = NULL;
    PyObject *DihedralsContext_cls = NULL;
    PyObject *Exclusions_statementContext_cls = NULL;
    PyObject *ExclusionsContext_cls = NULL;
    PyObject *Constraints_statementContext_cls = NULL;
    PyObject *ConstraintsContext_cls = NULL;
    PyObject *Settles_statementContext_cls = NULL;
    PyObject *SettlesContext_cls = NULL;
    PyObject *Virtual_sites1_statementContext_cls = NULL;
    PyObject *Virtual_sites1Context_cls = NULL;
    PyObject *Virtual_sites2_statementContext_cls = NULL;
    PyObject *Virtual_sites2Context_cls = NULL;
    PyObject *Virtual_sites3_statementContext_cls = NULL;
    PyObject *Virtual_sites3Context_cls = NULL;
    PyObject *Virtual_sites4_statementContext_cls = NULL;
    PyObject *Virtual_sites4Context_cls = NULL;
    PyObject *Virtual_sitesn_statementContext_cls = NULL;
    PyObject *Virtual_sitesnContext_cls = NULL;
    PyObject *System_statementContext_cls = NULL;
    PyObject *Molecules_statementContext_cls = NULL;
    PyObject *MoleculesContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Position_restraintsContext_cls = NULL;
    PyObject *Position_restraintContext_cls = NULL;

    public:
    SA_GromacsPTTranslator(speedy_antlr::Translator *translator);
    ~SA_GromacsPTTranslator();
    antlrcpp::Any visitGromacs_pt(GromacsPTParser::Gromacs_ptContext *ctx);

    antlrcpp::Any visitDefault_statement(GromacsPTParser::Default_statementContext *ctx);

    antlrcpp::Any visitMoleculetype_statement(GromacsPTParser::Moleculetype_statementContext *ctx);

    antlrcpp::Any visitMoleculetype(GromacsPTParser::MoleculetypeContext *ctx);

    antlrcpp::Any visitAtomtypes_statement(GromacsPTParser::Atomtypes_statementContext *ctx);

    antlrcpp::Any visitAtomtypes(GromacsPTParser::AtomtypesContext *ctx);

    antlrcpp::Any visitPairtypes_statement(GromacsPTParser::Pairtypes_statementContext *ctx);

    antlrcpp::Any visitPairtypes(GromacsPTParser::PairtypesContext *ctx);

    antlrcpp::Any visitBondtypes_statement(GromacsPTParser::Bondtypes_statementContext *ctx);

    antlrcpp::Any visitBondtypes(GromacsPTParser::BondtypesContext *ctx);

    antlrcpp::Any visitAngletypes_statement(GromacsPTParser::Angletypes_statementContext *ctx);

    antlrcpp::Any visitAngletypes(GromacsPTParser::AngletypesContext *ctx);

    antlrcpp::Any visitDihedraltypes_statement(GromacsPTParser::Dihedraltypes_statementContext *ctx);

    antlrcpp::Any visitDihedraltypes(GromacsPTParser::DihedraltypesContext *ctx);

    antlrcpp::Any visitConstrainttypes_statement(GromacsPTParser::Constrainttypes_statementContext *ctx);

    antlrcpp::Any visitConstrainttypes(GromacsPTParser::ConstrainttypesContext *ctx);

    antlrcpp::Any visitNonbonded_params_statement(GromacsPTParser::Nonbonded_params_statementContext *ctx);

    antlrcpp::Any visitNonbonded_params(GromacsPTParser::Nonbonded_paramsContext *ctx);

    antlrcpp::Any visitAtoms_statement(GromacsPTParser::Atoms_statementContext *ctx);

    antlrcpp::Any visitAtoms(GromacsPTParser::AtomsContext *ctx);

    antlrcpp::Any visitBonds_statement(GromacsPTParser::Bonds_statementContext *ctx);

    antlrcpp::Any visitBonds(GromacsPTParser::BondsContext *ctx);

    antlrcpp::Any visitPairs_statement(GromacsPTParser::Pairs_statementContext *ctx);

    antlrcpp::Any visitPairs(GromacsPTParser::PairsContext *ctx);

    antlrcpp::Any visitPairs_nb_statement(GromacsPTParser::Pairs_nb_statementContext *ctx);

    antlrcpp::Any visitPairs_nb(GromacsPTParser::Pairs_nbContext *ctx);

    antlrcpp::Any visitAngles_statement(GromacsPTParser::Angles_statementContext *ctx);

    antlrcpp::Any visitAngles(GromacsPTParser::AnglesContext *ctx);

    antlrcpp::Any visitDihedrals_statement(GromacsPTParser::Dihedrals_statementContext *ctx);

    antlrcpp::Any visitDihedrals(GromacsPTParser::DihedralsContext *ctx);

    antlrcpp::Any visitExclusions_statement(GromacsPTParser::Exclusions_statementContext *ctx);

    antlrcpp::Any visitExclusions(GromacsPTParser::ExclusionsContext *ctx);

    antlrcpp::Any visitConstraints_statement(GromacsPTParser::Constraints_statementContext *ctx);

    antlrcpp::Any visitConstraints(GromacsPTParser::ConstraintsContext *ctx);

    antlrcpp::Any visitSettles_statement(GromacsPTParser::Settles_statementContext *ctx);

    antlrcpp::Any visitSettles(GromacsPTParser::SettlesContext *ctx);

    antlrcpp::Any visitVirtual_sites1_statement(GromacsPTParser::Virtual_sites1_statementContext *ctx);

    antlrcpp::Any visitVirtual_sites1(GromacsPTParser::Virtual_sites1Context *ctx);

    antlrcpp::Any visitVirtual_sites2_statement(GromacsPTParser::Virtual_sites2_statementContext *ctx);

    antlrcpp::Any visitVirtual_sites2(GromacsPTParser::Virtual_sites2Context *ctx);

    antlrcpp::Any visitVirtual_sites3_statement(GromacsPTParser::Virtual_sites3_statementContext *ctx);

    antlrcpp::Any visitVirtual_sites3(GromacsPTParser::Virtual_sites3Context *ctx);

    antlrcpp::Any visitVirtual_sites4_statement(GromacsPTParser::Virtual_sites4_statementContext *ctx);

    antlrcpp::Any visitVirtual_sites4(GromacsPTParser::Virtual_sites4Context *ctx);

    antlrcpp::Any visitVirtual_sitesn_statement(GromacsPTParser::Virtual_sitesn_statementContext *ctx);

    antlrcpp::Any visitVirtual_sitesn(GromacsPTParser::Virtual_sitesnContext *ctx);

    antlrcpp::Any visitSystem_statement(GromacsPTParser::System_statementContext *ctx);

    antlrcpp::Any visitMolecules_statement(GromacsPTParser::Molecules_statementContext *ctx);

    antlrcpp::Any visitMolecules(GromacsPTParser::MoleculesContext *ctx);

    antlrcpp::Any visitNumber(GromacsPTParser::NumberContext *ctx);

    antlrcpp::Any visitPosition_restraints(GromacsPTParser::Position_restraintsContext *ctx);

    antlrcpp::Any visitPosition_restraint(GromacsPTParser::Position_restraintContext *ctx);

};