/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_isdmr_translator.h"


SA_IsdMRTranslator::SA_IsdMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_IsdMRTranslator::~SA_IsdMRTranslator() {
    Py_XDECREF(Isd_mrContext_cls);
    Py_XDECREF(Distance_restraintsContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
}


antlrcpp::Any SA_IsdMRTranslator::visitIsd_mr(IsdMRParser::Isd_mrContext *ctx){
    if(!Isd_mrContext_cls) Isd_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Isd_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Isd_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_IsdMRTranslator::visitDistance_restraints(IsdMRParser::Distance_restraintsContext *ctx){
    if(!Distance_restraintsContext_cls) Distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_IsdMRTranslator::visitDistance_restraint(IsdMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}
