/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "IsdMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_IsdMRTranslator : public IsdMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Isd_mrContext_cls = NULL;
    PyObject *Distance_restraintsContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;

    public:
    SA_IsdMRTranslator(speedy_antlr::Translator *translator);
    ~SA_IsdMRTranslator();
    antlrcpp::Any visitIsd_mr(IsdMRParser::Isd_mrContext *ctx);

    antlrcpp::Any visitDistance_restraints(IsdMRParser::Distance_restraintsContext *ctx);

    antlrcpp::Any visitDistance_restraint(IsdMRParser::Distance_restraintContext *ctx);

};