/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_nmrviewnpk_translator.h"


SA_NmrViewNPKTranslator::SA_NmrViewNPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_NmrViewNPKTranslator::~SA_NmrViewNPKTranslator() {
    Py_XDECREF(Nmrview_npkContext_cls);
    Py_XDECREF(Data_labelContext_cls);
    Py_XDECREF(LabelsContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Peak_list_wo_eju_2dContext_cls);
    Py_XDECREF(Peak_wo_eju_2dContext_cls);
    Py_XDECREF(Peak_list_wo_eju_3dContext_cls);
    Py_XDECREF(Peak_wo_eju_3dContext_cls);
    Py_XDECREF(Peak_list_wo_eju_4dContext_cls);
    Py_XDECREF(Peak_wo_eju_4dContext_cls);
    Py_XDECREF(LabelContext_cls);
    Py_XDECREF(JcouplingContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_NmrViewNPKTranslator::visitNmrview_npk(NmrViewNPKParser::Nmrview_npkContext *ctx){
    if(!Nmrview_npkContext_cls) Nmrview_npkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nmrview_npkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nmrview_npkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitData_label(NmrViewNPKParser::Data_labelContext *ctx){
    if(!Data_labelContext_cls) Data_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitLabels(NmrViewNPKParser::LabelsContext *ctx){
    if(!LabelsContext_cls) LabelsContext_cls = PyObject_GetAttrString(translator->parser_cls, "LabelsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LabelsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_2d(NmrViewNPKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_2d(NmrViewNPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_3d(NmrViewNPKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_3d(NmrViewNPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_4d(NmrViewNPKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_4d(NmrViewNPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_wo_eju_2d(NmrViewNPKParser::Peak_list_wo_eju_2dContext *ctx){
    if(!Peak_list_wo_eju_2dContext_cls) Peak_list_wo_eju_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_eju_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_eju_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_wo_eju_2d(NmrViewNPKParser::Peak_wo_eju_2dContext *ctx){
    if(!Peak_wo_eju_2dContext_cls) Peak_wo_eju_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_eju_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_eju_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_wo_eju_3d(NmrViewNPKParser::Peak_list_wo_eju_3dContext *ctx){
    if(!Peak_list_wo_eju_3dContext_cls) Peak_list_wo_eju_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_eju_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_eju_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_wo_eju_3d(NmrViewNPKParser::Peak_wo_eju_3dContext *ctx){
    if(!Peak_wo_eju_3dContext_cls) Peak_wo_eju_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_eju_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_eju_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_list_wo_eju_4d(NmrViewNPKParser::Peak_list_wo_eju_4dContext *ctx){
    if(!Peak_list_wo_eju_4dContext_cls) Peak_list_wo_eju_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_wo_eju_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_wo_eju_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitPeak_wo_eju_4d(NmrViewNPKParser::Peak_wo_eju_4dContext *ctx){
    if(!Peak_wo_eju_4dContext_cls) Peak_wo_eju_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_eju_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_eju_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitLabel(NmrViewNPKParser::LabelContext *ctx){
    if(!LabelContext_cls) LabelContext_cls = PyObject_GetAttrString(translator->parser_cls, "LabelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LabelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitJcoupling(NmrViewNPKParser::JcouplingContext *ctx){
    if(!JcouplingContext_cls) JcouplingContext_cls = PyObject_GetAttrString(translator->parser_cls, "JcouplingContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, JcouplingContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrViewNPKTranslator::visitNumber(NmrViewNPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
