/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_nmrpipecs_translator.h"


SA_NmrPipeCSTranslator::SA_NmrPipeCSTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_NmrPipeCSTranslator::~SA_NmrPipeCSTranslator() {
    Py_XDECREF(Nmrpipe_csContext_cls);
    Py_XDECREF(SequenceContext_cls);
    Py_XDECREF(Chemical_shiftsContext_cls);
    Py_XDECREF(Chemical_shiftContext_cls);
    Py_XDECREF(Chemical_shifts_sw_segidContext_cls);
    Py_XDECREF(Chemical_shift_sw_segidContext_cls);
    Py_XDECREF(Chemical_shifts_ew_segidContext_cls);
    Py_XDECREF(Chemical_shift_ew_segidContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_NmrPipeCSTranslator::visitNmrpipe_cs(NmrPipeCSParser::Nmrpipe_csContext *ctx){
    if(!Nmrpipe_csContext_cls) Nmrpipe_csContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nmrpipe_csContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nmrpipe_csContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitSequence(NmrPipeCSParser::SequenceContext *ctx){
    if(!SequenceContext_cls) SequenceContext_cls = PyObject_GetAttrString(translator->parser_cls, "SequenceContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SequenceContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shifts(NmrPipeCSParser::Chemical_shiftsContext *ctx){
    if(!Chemical_shiftsContext_cls) Chemical_shiftsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shiftsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shiftsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shift(NmrPipeCSParser::Chemical_shiftContext *ctx){
    if(!Chemical_shiftContext_cls) Chemical_shiftContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shiftContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shiftContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shifts_sw_segid(NmrPipeCSParser::Chemical_shifts_sw_segidContext *ctx){
    if(!Chemical_shifts_sw_segidContext_cls) Chemical_shifts_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shifts_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shifts_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shift_sw_segid(NmrPipeCSParser::Chemical_shift_sw_segidContext *ctx){
    if(!Chemical_shift_sw_segidContext_cls) Chemical_shift_sw_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shift_sw_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shift_sw_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shifts_ew_segid(NmrPipeCSParser::Chemical_shifts_ew_segidContext *ctx){
    if(!Chemical_shifts_ew_segidContext_cls) Chemical_shifts_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shifts_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shifts_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitChemical_shift_ew_segid(NmrPipeCSParser::Chemical_shift_ew_segidContext *ctx){
    if(!Chemical_shift_ew_segidContext_cls) Chemical_shift_ew_segidContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shift_ew_segidContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shift_ew_segidContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipeCSTranslator::visitNumber(NmrPipeCSParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
