/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "NmrViewNPKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_NmrViewNPKTranslator : public NmrViewNPKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Nmrview_npkContext_cls = NULL;
    PyObject *Data_labelContext_cls = NULL;
    PyObject *LabelsContext_cls = NULL;
    PyObject *Peak_list_2dContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_list_3dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_list_4dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *Peak_list_wo_eju_2dContext_cls = NULL;
    PyObject *Peak_wo_eju_2dContext_cls = NULL;
    PyObject *Peak_list_wo_eju_3dContext_cls = NULL;
    PyObject *Peak_wo_eju_3dContext_cls = NULL;
    PyObject *Peak_list_wo_eju_4dContext_cls = NULL;
    PyObject *Peak_wo_eju_4dContext_cls = NULL;
    PyObject *LabelContext_cls = NULL;
    PyObject *JcouplingContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_NmrViewNPKTranslator(speedy_antlr::Translator *translator);
    ~SA_NmrViewNPKTranslator();
    antlrcpp::Any visitNmrview_npk(NmrViewNPKParser::Nmrview_npkContext *ctx);

    antlrcpp::Any visitData_label(NmrViewNPKParser::Data_labelContext *ctx);

    antlrcpp::Any visitLabels(NmrViewNPKParser::LabelsContext *ctx);

    antlrcpp::Any visitPeak_list_2d(NmrViewNPKParser::Peak_list_2dContext *ctx);

    antlrcpp::Any visitPeak_2d(NmrViewNPKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_list_3d(NmrViewNPKParser::Peak_list_3dContext *ctx);

    antlrcpp::Any visitPeak_3d(NmrViewNPKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_list_4d(NmrViewNPKParser::Peak_list_4dContext *ctx);

    antlrcpp::Any visitPeak_4d(NmrViewNPKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_eju_2d(NmrViewNPKParser::Peak_list_wo_eju_2dContext *ctx);

    antlrcpp::Any visitPeak_wo_eju_2d(NmrViewNPKParser::Peak_wo_eju_2dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_eju_3d(NmrViewNPKParser::Peak_list_wo_eju_3dContext *ctx);

    antlrcpp::Any visitPeak_wo_eju_3d(NmrViewNPKParser::Peak_wo_eju_3dContext *ctx);

    antlrcpp::Any visitPeak_list_wo_eju_4d(NmrViewNPKParser::Peak_list_wo_eju_4dContext *ctx);

    antlrcpp::Any visitPeak_wo_eju_4d(NmrViewNPKParser::Peak_wo_eju_4dContext *ctx);

    antlrcpp::Any visitLabel(NmrViewNPKParser::LabelContext *ctx);

    antlrcpp::Any visitJcoupling(NmrViewNPKParser::JcouplingContext *ctx);

    antlrcpp::Any visitNumber(NmrViewNPKParser::NumberContext *ctx);

};