/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "NmrPipeCSParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_NmrPipeCSTranslator : public NmrPipeCSParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Nmrpipe_csContext_cls = NULL;
    PyObject *SequenceContext_cls = NULL;
    PyObject *Chemical_shiftsContext_cls = NULL;
    PyObject *Chemical_shiftContext_cls = NULL;
    PyObject *Chemical_shifts_sw_segidContext_cls = NULL;
    PyObject *Chemical_shift_sw_segidContext_cls = NULL;
    PyObject *Chemical_shifts_ew_segidContext_cls = NULL;
    PyObject *Chemical_shift_ew_segidContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_NmrPipeCSTranslator(speedy_antlr::Translator *translator);
    ~SA_NmrPipeCSTranslator();
    antlrcpp::Any visitNmrpipe_cs(NmrPipeCSParser::Nmrpipe_csContext *ctx);

    antlrcpp::Any visitSequence(NmrPipeCSParser::SequenceContext *ctx);

    antlrcpp::Any visitChemical_shifts(NmrPipeCSParser::Chemical_shiftsContext *ctx);

    antlrcpp::Any visitChemical_shift(NmrPipeCSParser::Chemical_shiftContext *ctx);

    antlrcpp::Any visitChemical_shifts_sw_segid(NmrPipeCSParser::Chemical_shifts_sw_segidContext *ctx);

    antlrcpp::Any visitChemical_shift_sw_segid(NmrPipeCSParser::Chemical_shift_sw_segidContext *ctx);

    antlrcpp::Any visitChemical_shifts_ew_segid(NmrPipeCSParser::Chemical_shifts_ew_segidContext *ctx);

    antlrcpp::Any visitChemical_shift_ew_segid(NmrPipeCSParser::Chemical_shift_ew_segidContext *ctx);

    antlrcpp::Any visitNumber(NmrPipeCSParser::NumberContext *ctx);

};