/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "NmrStar2CSParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_NmrStar2CSTranslator : public NmrStar2CSParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Nmrstar2_csContext_cls = NULL;
    PyObject *Seq_loopContext_cls = NULL;
    PyObject *Seq_tagsContext_cls = NULL;
    PyObject *Seq_dataContext_cls = NULL;
    PyObject *Cs_loopContext_cls = NULL;
    PyObject *Cs_tagsContext_cls = NULL;
    PyObject *Cs_dataContext_cls = NULL;
    PyObject *AnyContext_cls = NULL;

    public:
    SA_NmrStar2CSTranslator(speedy_antlr::Translator *translator);
    ~SA_NmrStar2CSTranslator();
    antlrcpp::Any visitNmrstar2_cs(NmrStar2CSParser::Nmrstar2_csContext *ctx);

    antlrcpp::Any visitSeq_loop(NmrStar2CSParser::Seq_loopContext *ctx);

    antlrcpp::Any visitSeq_tags(NmrStar2CSParser::Seq_tagsContext *ctx);

    antlrcpp::Any visitSeq_data(NmrStar2CSParser::Seq_dataContext *ctx);

    antlrcpp::Any visitCs_loop(NmrStar2CSParser::Cs_loopContext *ctx);

    antlrcpp::Any visitCs_tags(NmrStar2CSParser::Cs_tagsContext *ctx);

    antlrcpp::Any visitCs_data(NmrStar2CSParser::Cs_dataContext *ctx);

    antlrcpp::Any visitAny(NmrStar2CSParser::AnyContext *ctx);

};