/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_nmrpipepk_translator.h"


SA_NmrPipePKTranslator::SA_NmrPipePKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_NmrPipePKTranslator::~SA_NmrPipePKTranslator() {
    Py_XDECREF(Nmrpipe_pkContext_cls);
    Py_XDECREF(Data_labelContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Pipp_labelContext_cls);
    Py_XDECREF(Pipp_axisContext_cls);
    Py_XDECREF(Pipp_peak_list_2dContext_cls);
    Py_XDECREF(Pipp_peak_2dContext_cls);
    Py_XDECREF(Pipp_peak_list_3dContext_cls);
    Py_XDECREF(Pipp_peak_3dContext_cls);
    Py_XDECREF(Pipp_peak_list_4dContext_cls);
    Py_XDECREF(Pipp_peak_4dContext_cls);
    Py_XDECREF(Pipp_row_peak_list_2dContext_cls);
    Py_XDECREF(Pipp_row_peak_2dContext_cls);
    Py_XDECREF(Pipp_row_peak_list_3dContext_cls);
    Py_XDECREF(Pipp_row_peak_3dContext_cls);
    Py_XDECREF(Pipp_row_peak_list_4dContext_cls);
    Py_XDECREF(Pipp_row_peak_4dContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_NmrPipePKTranslator::visitNmrpipe_pk(NmrPipePKParser::Nmrpipe_pkContext *ctx){
    if(!Nmrpipe_pkContext_cls) Nmrpipe_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nmrpipe_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nmrpipe_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitData_label(NmrPipePKParser::Data_labelContext *ctx){
    if(!Data_labelContext_cls) Data_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_list_2d(NmrPipePKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_2d(NmrPipePKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_list_3d(NmrPipePKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_3d(NmrPipePKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_list_4d(NmrPipePKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPeak_4d(NmrPipePKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_label(NmrPipePKParser::Pipp_labelContext *ctx){
    if(!Pipp_labelContext_cls) Pipp_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_axis(NmrPipePKParser::Pipp_axisContext *ctx){
    if(!Pipp_axisContext_cls) Pipp_axisContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_axisContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_axisContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_list_2d(NmrPipePKParser::Pipp_peak_list_2dContext *ctx){
    if(!Pipp_peak_list_2dContext_cls) Pipp_peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_2d(NmrPipePKParser::Pipp_peak_2dContext *ctx){
    if(!Pipp_peak_2dContext_cls) Pipp_peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_list_3d(NmrPipePKParser::Pipp_peak_list_3dContext *ctx){
    if(!Pipp_peak_list_3dContext_cls) Pipp_peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_3d(NmrPipePKParser::Pipp_peak_3dContext *ctx){
    if(!Pipp_peak_3dContext_cls) Pipp_peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_list_4d(NmrPipePKParser::Pipp_peak_list_4dContext *ctx){
    if(!Pipp_peak_list_4dContext_cls) Pipp_peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_peak_4d(NmrPipePKParser::Pipp_peak_4dContext *ctx){
    if(!Pipp_peak_4dContext_cls) Pipp_peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_list_2d(NmrPipePKParser::Pipp_row_peak_list_2dContext *ctx){
    if(!Pipp_row_peak_list_2dContext_cls) Pipp_row_peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_2d(NmrPipePKParser::Pipp_row_peak_2dContext *ctx){
    if(!Pipp_row_peak_2dContext_cls) Pipp_row_peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_list_3d(NmrPipePKParser::Pipp_row_peak_list_3dContext *ctx){
    if(!Pipp_row_peak_list_3dContext_cls) Pipp_row_peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_3d(NmrPipePKParser::Pipp_row_peak_3dContext *ctx){
    if(!Pipp_row_peak_3dContext_cls) Pipp_row_peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_list_4d(NmrPipePKParser::Pipp_row_peak_list_4dContext *ctx){
    if(!Pipp_row_peak_list_4dContext_cls) Pipp_row_peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitPipp_row_peak_4d(NmrPipePKParser::Pipp_row_peak_4dContext *ctx){
    if(!Pipp_row_peak_4dContext_cls) Pipp_row_peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Pipp_row_peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Pipp_row_peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrPipePKTranslator::visitNumber(NmrPipePKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
