/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_nmrstar2cs_translator.h"


SA_NmrStar2CSTranslator::SA_NmrStar2CSTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_NmrStar2CSTranslator::~SA_NmrStar2CSTranslator() {
    Py_XDECREF(Nmrstar2_csContext_cls);
    Py_XDECREF(Seq_loopContext_cls);
    Py_XDECREF(Seq_tagsContext_cls);
    Py_XDECREF(Seq_dataContext_cls);
    Py_XDECREF(Cs_loopContext_cls);
    Py_XDECREF(Cs_tagsContext_cls);
    Py_XDECREF(Cs_dataContext_cls);
    Py_XDECREF(AnyContext_cls);
}


antlrcpp::Any SA_NmrStar2CSTranslator::visitNmrstar2_cs(NmrStar2CSParser::Nmrstar2_csContext *ctx){
    if(!Nmrstar2_csContext_cls) Nmrstar2_csContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nmrstar2_csContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nmrstar2_csContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitSeq_loop(NmrStar2CSParser::Seq_loopContext *ctx){
    if(!Seq_loopContext_cls) Seq_loopContext_cls = PyObject_GetAttrString(translator->parser_cls, "Seq_loopContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Seq_loopContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitSeq_tags(NmrStar2CSParser::Seq_tagsContext *ctx){
    if(!Seq_tagsContext_cls) Seq_tagsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Seq_tagsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Seq_tagsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitSeq_data(NmrStar2CSParser::Seq_dataContext *ctx){
    if(!Seq_dataContext_cls) Seq_dataContext_cls = PyObject_GetAttrString(translator->parser_cls, "Seq_dataContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Seq_dataContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitCs_loop(NmrStar2CSParser::Cs_loopContext *ctx){
    if(!Cs_loopContext_cls) Cs_loopContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cs_loopContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cs_loopContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitCs_tags(NmrStar2CSParser::Cs_tagsContext *ctx){
    if(!Cs_tagsContext_cls) Cs_tagsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cs_tagsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cs_tagsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitCs_data(NmrStar2CSParser::Cs_dataContext *ctx){
    if(!Cs_dataContext_cls) Cs_dataContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cs_dataContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cs_dataContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_NmrStar2CSTranslator::visitAny(NmrStar2CSParser::AnyContext *ctx){
    if(!AnyContext_cls) AnyContext_cls = PyObject_GetAttrString(translator->parser_cls, "AnyContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AnyContext_cls);
    return py_ctx;
}
