/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "NmrPipePKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_NmrPipePKTranslator : public NmrPipePKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Nmrpipe_pkContext_cls = NULL;
    PyObject *Data_labelContext_cls = NULL;
    PyObject *Peak_list_2dContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_list_3dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_list_4dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *Pipp_labelContext_cls = NULL;
    PyObject *Pipp_axisContext_cls = NULL;
    PyObject *Pipp_peak_list_2dContext_cls = NULL;
    PyObject *Pipp_peak_2dContext_cls = NULL;
    PyObject *Pipp_peak_list_3dContext_cls = NULL;
    PyObject *Pipp_peak_3dContext_cls = NULL;
    PyObject *Pipp_peak_list_4dContext_cls = NULL;
    PyObject *Pipp_peak_4dContext_cls = NULL;
    PyObject *Pipp_row_peak_list_2dContext_cls = NULL;
    PyObject *Pipp_row_peak_2dContext_cls = NULL;
    PyObject *Pipp_row_peak_list_3dContext_cls = NULL;
    PyObject *Pipp_row_peak_3dContext_cls = NULL;
    PyObject *Pipp_row_peak_list_4dContext_cls = NULL;
    PyObject *Pipp_row_peak_4dContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_NmrPipePKTranslator(speedy_antlr::Translator *translator);
    ~SA_NmrPipePKTranslator();
    antlrcpp::Any visitNmrpipe_pk(NmrPipePKParser::Nmrpipe_pkContext *ctx);

    antlrcpp::Any visitData_label(NmrPipePKParser::Data_labelContext *ctx);

    antlrcpp::Any visitPeak_list_2d(NmrPipePKParser::Peak_list_2dContext *ctx);

    antlrcpp::Any visitPeak_2d(NmrPipePKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_list_3d(NmrPipePKParser::Peak_list_3dContext *ctx);

    antlrcpp::Any visitPeak_3d(NmrPipePKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_list_4d(NmrPipePKParser::Peak_list_4dContext *ctx);

    antlrcpp::Any visitPeak_4d(NmrPipePKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitPipp_label(NmrPipePKParser::Pipp_labelContext *ctx);

    antlrcpp::Any visitPipp_axis(NmrPipePKParser::Pipp_axisContext *ctx);

    antlrcpp::Any visitPipp_peak_list_2d(NmrPipePKParser::Pipp_peak_list_2dContext *ctx);

    antlrcpp::Any visitPipp_peak_2d(NmrPipePKParser::Pipp_peak_2dContext *ctx);

    antlrcpp::Any visitPipp_peak_list_3d(NmrPipePKParser::Pipp_peak_list_3dContext *ctx);

    antlrcpp::Any visitPipp_peak_3d(NmrPipePKParser::Pipp_peak_3dContext *ctx);

    antlrcpp::Any visitPipp_peak_list_4d(NmrPipePKParser::Pipp_peak_list_4dContext *ctx);

    antlrcpp::Any visitPipp_peak_4d(NmrPipePKParser::Pipp_peak_4dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_list_2d(NmrPipePKParser::Pipp_row_peak_list_2dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_2d(NmrPipePKParser::Pipp_row_peak_2dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_list_3d(NmrPipePKParser::Pipp_row_peak_list_3dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_3d(NmrPipePKParser::Pipp_row_peak_3dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_list_4d(NmrPipePKParser::Pipp_row_peak_list_4dContext *ctx);

    antlrcpp::Any visitPipp_row_peak_4d(NmrPipePKParser::Pipp_row_peak_4dContext *ctx);

    antlrcpp::Any visitNumber(NmrPipePKParser::NumberContext *ctx);

};