/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_oliviacs_translator.h"


SA_OliviaCSTranslator::SA_OliviaCSTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_OliviaCSTranslator::~SA_OliviaCSTranslator() {
    Py_XDECREF(Olivia_csContext_cls);
    Py_XDECREF(SequenceContext_cls);
    Py_XDECREF(ResidueContext_cls);
    Py_XDECREF(Chemical_shiftsContext_cls);
    Py_XDECREF(Chemical_shiftContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(CommentContext_cls);
}


antlrcpp::Any SA_OliviaCSTranslator::visitOlivia_cs(OliviaCSParser::Olivia_csContext *ctx){
    if(!Olivia_csContext_cls) Olivia_csContext_cls = PyObject_GetAttrString(translator->parser_cls, "Olivia_csContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Olivia_csContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitSequence(OliviaCSParser::SequenceContext *ctx){
    if(!SequenceContext_cls) SequenceContext_cls = PyObject_GetAttrString(translator->parser_cls, "SequenceContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SequenceContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitResidue(OliviaCSParser::ResidueContext *ctx){
    if(!ResidueContext_cls) ResidueContext_cls = PyObject_GetAttrString(translator->parser_cls, "ResidueContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ResidueContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitChemical_shifts(OliviaCSParser::Chemical_shiftsContext *ctx){
    if(!Chemical_shiftsContext_cls) Chemical_shiftsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shiftsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shiftsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitChemical_shift(OliviaCSParser::Chemical_shiftContext *ctx){
    if(!Chemical_shiftContext_cls) Chemical_shiftContext_cls = PyObject_GetAttrString(translator->parser_cls, "Chemical_shiftContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Chemical_shiftContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitNumber(OliviaCSParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaCSTranslator::visitComment(OliviaCSParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}
