/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_oliviapk_translator.h"


SA_OliviaPKTranslator::SA_OliviaPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_OliviaPKTranslator::~SA_OliviaPKTranslator() {
    Py_XDECREF(Olivia_pkContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(Idx_peak_list_2dContext_cls);
    Py_XDECREF(Idx_peak_2dContext_cls);
    Py_XDECREF(Idx_peak_list_3dContext_cls);
    Py_XDECREF(Idx_peak_3dContext_cls);
    Py_XDECREF(Idx_peak_list_4dContext_cls);
    Py_XDECREF(Idx_peak_4dContext_cls);
    Py_XDECREF(Ass_peak_list_2dContext_cls);
    Py_XDECREF(Ass_peak_2dContext_cls);
    Py_XDECREF(Ass_peak_list_3dContext_cls);
    Py_XDECREF(Ass_peak_3dContext_cls);
    Py_XDECREF(Ass_peak_list_4dContext_cls);
    Py_XDECREF(Ass_peak_4dContext_cls);
    Py_XDECREF(Def_2d_axis_order_ppmContext_cls);
    Py_XDECREF(Tp_2d_axis_order_ppmContext_cls);
    Py_XDECREF(Def_2d_axis_order_hzContext_cls);
    Py_XDECREF(Tp_2d_axis_order_hzContext_cls);
    Py_XDECREF(Def_3d_axis_order_ppmContext_cls);
    Py_XDECREF(Tp_3d_axis_order_ppmContext_cls);
    Py_XDECREF(Def_3d_axis_order_hzContext_cls);
    Py_XDECREF(Tp_3d_axis_order_hzContext_cls);
    Py_XDECREF(Def_4d_axis_order_ppmContext_cls);
    Py_XDECREF(Tp_4d_axis_order_ppmContext_cls);
    Py_XDECREF(Def_4d_axis_order_hzContext_cls);
    Py_XDECREF(Tp_4d_axis_order_hzContext_cls);
    Py_XDECREF(StringContext_cls);
    Py_XDECREF(IntegerContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(MemoContext_cls);
}


antlrcpp::Any SA_OliviaPKTranslator::visitOlivia_pk(OliviaPKParser::Olivia_pkContext *ctx){
    if(!Olivia_pkContext_cls) Olivia_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Olivia_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Olivia_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitComment(OliviaPKParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_list_2d(OliviaPKParser::Idx_peak_list_2dContext *ctx){
    if(!Idx_peak_list_2dContext_cls) Idx_peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_2d(OliviaPKParser::Idx_peak_2dContext *ctx){
    if(!Idx_peak_2dContext_cls) Idx_peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_list_3d(OliviaPKParser::Idx_peak_list_3dContext *ctx){
    if(!Idx_peak_list_3dContext_cls) Idx_peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_3d(OliviaPKParser::Idx_peak_3dContext *ctx){
    if(!Idx_peak_3dContext_cls) Idx_peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_list_4d(OliviaPKParser::Idx_peak_list_4dContext *ctx){
    if(!Idx_peak_list_4dContext_cls) Idx_peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitIdx_peak_4d(OliviaPKParser::Idx_peak_4dContext *ctx){
    if(!Idx_peak_4dContext_cls) Idx_peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Idx_peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Idx_peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_list_2d(OliviaPKParser::Ass_peak_list_2dContext *ctx){
    if(!Ass_peak_list_2dContext_cls) Ass_peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_2d(OliviaPKParser::Ass_peak_2dContext *ctx){
    if(!Ass_peak_2dContext_cls) Ass_peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_list_3d(OliviaPKParser::Ass_peak_list_3dContext *ctx){
    if(!Ass_peak_list_3dContext_cls) Ass_peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_3d(OliviaPKParser::Ass_peak_3dContext *ctx){
    if(!Ass_peak_3dContext_cls) Ass_peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_list_4d(OliviaPKParser::Ass_peak_list_4dContext *ctx){
    if(!Ass_peak_list_4dContext_cls) Ass_peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitAss_peak_4d(OliviaPKParser::Ass_peak_4dContext *ctx){
    if(!Ass_peak_4dContext_cls) Ass_peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ass_peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ass_peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_2d_axis_order_ppm(OliviaPKParser::Def_2d_axis_order_ppmContext *ctx){
    if(!Def_2d_axis_order_ppmContext_cls) Def_2d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_2d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_2d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_2d_axis_order_ppm(OliviaPKParser::Tp_2d_axis_order_ppmContext *ctx){
    if(!Tp_2d_axis_order_ppmContext_cls) Tp_2d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_2d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_2d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_2d_axis_order_hz(OliviaPKParser::Def_2d_axis_order_hzContext *ctx){
    if(!Def_2d_axis_order_hzContext_cls) Def_2d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_2d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_2d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_2d_axis_order_hz(OliviaPKParser::Tp_2d_axis_order_hzContext *ctx){
    if(!Tp_2d_axis_order_hzContext_cls) Tp_2d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_2d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_2d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_3d_axis_order_ppm(OliviaPKParser::Def_3d_axis_order_ppmContext *ctx){
    if(!Def_3d_axis_order_ppmContext_cls) Def_3d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_3d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_3d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_3d_axis_order_ppm(OliviaPKParser::Tp_3d_axis_order_ppmContext *ctx){
    if(!Tp_3d_axis_order_ppmContext_cls) Tp_3d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_3d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_3d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_3d_axis_order_hz(OliviaPKParser::Def_3d_axis_order_hzContext *ctx){
    if(!Def_3d_axis_order_hzContext_cls) Def_3d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_3d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_3d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_3d_axis_order_hz(OliviaPKParser::Tp_3d_axis_order_hzContext *ctx){
    if(!Tp_3d_axis_order_hzContext_cls) Tp_3d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_3d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_3d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_4d_axis_order_ppm(OliviaPKParser::Def_4d_axis_order_ppmContext *ctx){
    if(!Def_4d_axis_order_ppmContext_cls) Def_4d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_4d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_4d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_4d_axis_order_ppm(OliviaPKParser::Tp_4d_axis_order_ppmContext *ctx){
    if(!Tp_4d_axis_order_ppmContext_cls) Tp_4d_axis_order_ppmContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_4d_axis_order_ppmContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_4d_axis_order_ppmContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitDef_4d_axis_order_hz(OliviaPKParser::Def_4d_axis_order_hzContext *ctx){
    if(!Def_4d_axis_order_hzContext_cls) Def_4d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Def_4d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Def_4d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitTp_4d_axis_order_hz(OliviaPKParser::Tp_4d_axis_order_hzContext *ctx){
    if(!Tp_4d_axis_order_hzContext_cls) Tp_4d_axis_order_hzContext_cls = PyObject_GetAttrString(translator->parser_cls, "Tp_4d_axis_order_hzContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Tp_4d_axis_order_hzContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitString(OliviaPKParser::StringContext *ctx){
    if(!StringContext_cls) StringContext_cls = PyObject_GetAttrString(translator->parser_cls, "StringContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, StringContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitInteger(OliviaPKParser::IntegerContext *ctx){
    if(!IntegerContext_cls) IntegerContext_cls = PyObject_GetAttrString(translator->parser_cls, "IntegerContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, IntegerContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitNumber(OliviaPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_OliviaPKTranslator::visitMemo(OliviaPKParser::MemoContext *ctx){
    if(!MemoContext_cls) MemoContext_cls = PyObject_GetAttrString(translator->parser_cls, "MemoContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, MemoContext_cls);
    return py_ctx;
}
