/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_ppmcs_translator.h"


SA_PpmCSTranslator::SA_PpmCSTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_PpmCSTranslator::~SA_PpmCSTranslator() {
    Py_XDECREF(Ppm_csContext_cls);
    Py_XDECREF(Ppm_listContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_PpmCSTranslator::visitPpm_cs(PpmCSParser::Ppm_csContext *ctx){
    if(!Ppm_csContext_cls) Ppm_csContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ppm_csContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ppm_csContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PpmCSTranslator::visitPpm_list(PpmCSParser::Ppm_listContext *ctx){
    if(!Ppm_listContext_cls) Ppm_listContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ppm_listContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ppm_listContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PpmCSTranslator::visitNumber(PpmCSParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
