/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "PippCSParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_PippCSTranslator : public PippCSParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Pipp_csContext_cls = NULL;
    PyObject *Pipp_formatContext_cls = NULL;
    PyObject *Ext_peak_pick_tblContext_cls = NULL;
    PyObject *Ext_peak_pick_tbl_rowContext_cls = NULL;
    PyObject *Residue_listContext_cls = NULL;
    PyObject *Shift_listContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_PippCSTranslator(speedy_antlr::Translator *translator);
    ~SA_PippCSTranslator();
    antlrcpp::Any visitPipp_cs(PippCSParser::Pipp_csContext *ctx);

    antlrcpp::Any visitPipp_format(PippCSParser::Pipp_formatContext *ctx);

    antlrcpp::Any visitExt_peak_pick_tbl(PippCSParser::Ext_peak_pick_tblContext *ctx);

    antlrcpp::Any visitExt_peak_pick_tbl_row(PippCSParser::Ext_peak_pick_tbl_rowContext *ctx);

    antlrcpp::Any visitResidue_list(PippCSParser::Residue_listContext *ctx);

    antlrcpp::Any visitShift_list(PippCSParser::Shift_listContext *ctx);

    antlrcpp::Any visitNumber(PippCSParser::NumberContext *ctx);

};