/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_ponderosapk_translator.h"


SA_PonderosaPKTranslator::SA_PonderosaPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_PonderosaPKTranslator::~SA_PonderosaPKTranslator() {
    Py_XDECREF(Ponderosa_pkContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_PonderosaPKTranslator::visitPonderosa_pk(PonderosaPKParser::Ponderosa_pkContext *ctx){
    if(!Ponderosa_pkContext_cls) Ponderosa_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ponderosa_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ponderosa_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_list_2d(PonderosaPKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_2d(PonderosaPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_list_3d(PonderosaPKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_3d(PonderosaPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_list_4d(PonderosaPKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitPeak_4d(PonderosaPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_PonderosaPKTranslator::visitNumber(PonderosaPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
