/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_rosettamr_translator.h"


SA_RosettaMRTranslator::SA_RosettaMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_RosettaMRTranslator::~SA_RosettaMRTranslator() {
    Py_XDECREF(Rosetta_mrContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(Atom_pair_restraintsContext_cls);
    Py_XDECREF(Atom_pair_restraintContext_cls);
    Py_XDECREF(Angle_restraintsContext_cls);
    Py_XDECREF(Angle_restraintContext_cls);
    Py_XDECREF(Dihedral_restraintsContext_cls);
    Py_XDECREF(Dihedral_restraintContext_cls);
    Py_XDECREF(Dihedral_pair_restraintsContext_cls);
    Py_XDECREF(Dihedral_pair_restraintContext_cls);
    Py_XDECREF(Coordinate_restraintsContext_cls);
    Py_XDECREF(Coordinate_restraintContext_cls);
    Py_XDECREF(Local_coordinate_restraintsContext_cls);
    Py_XDECREF(Local_coordinate_restraintContext_cls);
    Py_XDECREF(Site_restraintsContext_cls);
    Py_XDECREF(Site_restraintContext_cls);
    Py_XDECREF(Site_residues_restraintsContext_cls);
    Py_XDECREF(Site_residues_restraintContext_cls);
    Py_XDECREF(Min_residue_atomic_distance_restraintsContext_cls);
    Py_XDECREF(Min_residue_atomic_distance_restraintContext_cls);
    Py_XDECREF(Big_bin_restraintsContext_cls);
    Py_XDECREF(Big_bin_restraintContext_cls);
    Py_XDECREF(Nested_restraintsContext_cls);
    Py_XDECREF(Nested_restraintContext_cls);
    Py_XDECREF(Any_restraintContext_cls);
    Py_XDECREF(Func_type_defContext_cls);
    Py_XDECREF(Rdc_restraintsContext_cls);
    Py_XDECREF(Rdc_restraintContext_cls);
    Py_XDECREF(Disulfide_bond_linkagesContext_cls);
    Py_XDECREF(Disulfide_bond_linkageContext_cls);
    Py_XDECREF(Atom_pair_w_chain_restraintsContext_cls);
    Py_XDECREF(Atom_pair_w_chain_restraintContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Number_fContext_cls);
    Py_XDECREF(Gen_res_numContext_cls);
    Py_XDECREF(Gen_simple_nameContext_cls);
}


antlrcpp::Any SA_RosettaMRTranslator::visitRosetta_mr(RosettaMRParser::Rosetta_mrContext *ctx){
    if(!Rosetta_mrContext_cls) Rosetta_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rosetta_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rosetta_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitComment(RosettaMRParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAtom_pair_restraints(RosettaMRParser::Atom_pair_restraintsContext *ctx){
    if(!Atom_pair_restraintsContext_cls) Atom_pair_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_pair_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_pair_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAtom_pair_restraint(RosettaMRParser::Atom_pair_restraintContext *ctx){
    if(!Atom_pair_restraintContext_cls) Atom_pair_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_pair_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_pair_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAngle_restraints(RosettaMRParser::Angle_restraintsContext *ctx){
    if(!Angle_restraintsContext_cls) Angle_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAngle_restraint(RosettaMRParser::Angle_restraintContext *ctx){
    if(!Angle_restraintContext_cls) Angle_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDihedral_restraints(RosettaMRParser::Dihedral_restraintsContext *ctx){
    if(!Dihedral_restraintsContext_cls) Dihedral_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDihedral_restraint(RosettaMRParser::Dihedral_restraintContext *ctx){
    if(!Dihedral_restraintContext_cls) Dihedral_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDihedral_pair_restraints(RosettaMRParser::Dihedral_pair_restraintsContext *ctx){
    if(!Dihedral_pair_restraintsContext_cls) Dihedral_pair_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_pair_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_pair_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDihedral_pair_restraint(RosettaMRParser::Dihedral_pair_restraintContext *ctx){
    if(!Dihedral_pair_restraintContext_cls) Dihedral_pair_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_pair_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_pair_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitCoordinate_restraints(RosettaMRParser::Coordinate_restraintsContext *ctx){
    if(!Coordinate_restraintsContext_cls) Coordinate_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coordinate_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coordinate_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitCoordinate_restraint(RosettaMRParser::Coordinate_restraintContext *ctx){
    if(!Coordinate_restraintContext_cls) Coordinate_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Coordinate_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Coordinate_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitLocal_coordinate_restraints(RosettaMRParser::Local_coordinate_restraintsContext *ctx){
    if(!Local_coordinate_restraintsContext_cls) Local_coordinate_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Local_coordinate_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Local_coordinate_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitLocal_coordinate_restraint(RosettaMRParser::Local_coordinate_restraintContext *ctx){
    if(!Local_coordinate_restraintContext_cls) Local_coordinate_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Local_coordinate_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Local_coordinate_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitSite_restraints(RosettaMRParser::Site_restraintsContext *ctx){
    if(!Site_restraintsContext_cls) Site_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Site_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Site_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitSite_restraint(RosettaMRParser::Site_restraintContext *ctx){
    if(!Site_restraintContext_cls) Site_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Site_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Site_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitSite_residues_restraints(RosettaMRParser::Site_residues_restraintsContext *ctx){
    if(!Site_residues_restraintsContext_cls) Site_residues_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Site_residues_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Site_residues_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitSite_residues_restraint(RosettaMRParser::Site_residues_restraintContext *ctx){
    if(!Site_residues_restraintContext_cls) Site_residues_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Site_residues_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Site_residues_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitMin_residue_atomic_distance_restraints(RosettaMRParser::Min_residue_atomic_distance_restraintsContext *ctx){
    if(!Min_residue_atomic_distance_restraintsContext_cls) Min_residue_atomic_distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Min_residue_atomic_distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Min_residue_atomic_distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitMin_residue_atomic_distance_restraint(RosettaMRParser::Min_residue_atomic_distance_restraintContext *ctx){
    if(!Min_residue_atomic_distance_restraintContext_cls) Min_residue_atomic_distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Min_residue_atomic_distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Min_residue_atomic_distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitBig_bin_restraints(RosettaMRParser::Big_bin_restraintsContext *ctx){
    if(!Big_bin_restraintsContext_cls) Big_bin_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Big_bin_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Big_bin_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitBig_bin_restraint(RosettaMRParser::Big_bin_restraintContext *ctx){
    if(!Big_bin_restraintContext_cls) Big_bin_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Big_bin_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Big_bin_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitNested_restraints(RosettaMRParser::Nested_restraintsContext *ctx){
    if(!Nested_restraintsContext_cls) Nested_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nested_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nested_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitNested_restraint(RosettaMRParser::Nested_restraintContext *ctx){
    if(!Nested_restraintContext_cls) Nested_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Nested_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Nested_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAny_restraint(RosettaMRParser::Any_restraintContext *ctx){
    if(!Any_restraintContext_cls) Any_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Any_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Any_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitFunc_type_def(RosettaMRParser::Func_type_defContext *ctx){
    if(!Func_type_defContext_cls) Func_type_defContext_cls = PyObject_GetAttrString(translator->parser_cls, "Func_type_defContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Func_type_defContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitRdc_restraints(RosettaMRParser::Rdc_restraintsContext *ctx){
    if(!Rdc_restraintsContext_cls) Rdc_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitRdc_restraint(RosettaMRParser::Rdc_restraintContext *ctx){
    if(!Rdc_restraintContext_cls) Rdc_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Rdc_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Rdc_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDisulfide_bond_linkages(RosettaMRParser::Disulfide_bond_linkagesContext *ctx){
    if(!Disulfide_bond_linkagesContext_cls) Disulfide_bond_linkagesContext_cls = PyObject_GetAttrString(translator->parser_cls, "Disulfide_bond_linkagesContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Disulfide_bond_linkagesContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitDisulfide_bond_linkage(RosettaMRParser::Disulfide_bond_linkageContext *ctx){
    if(!Disulfide_bond_linkageContext_cls) Disulfide_bond_linkageContext_cls = PyObject_GetAttrString(translator->parser_cls, "Disulfide_bond_linkageContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Disulfide_bond_linkageContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAtom_pair_w_chain_restraints(RosettaMRParser::Atom_pair_w_chain_restraintsContext *ctx){
    if(!Atom_pair_w_chain_restraintsContext_cls) Atom_pair_w_chain_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_pair_w_chain_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_pair_w_chain_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitAtom_pair_w_chain_restraint(RosettaMRParser::Atom_pair_w_chain_restraintContext *ctx){
    if(!Atom_pair_w_chain_restraintContext_cls) Atom_pair_w_chain_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Atom_pair_w_chain_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Atom_pair_w_chain_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitNumber(RosettaMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitNumber_f(RosettaMRParser::Number_fContext *ctx){
    if(!Number_fContext_cls) Number_fContext_cls = PyObject_GetAttrString(translator->parser_cls, "Number_fContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Number_fContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitGen_res_num(RosettaMRParser::Gen_res_numContext *ctx){
    if(!Gen_res_numContext_cls) Gen_res_numContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gen_res_numContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gen_res_numContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_RosettaMRTranslator::visitGen_simple_name(RosettaMRParser::Gen_simple_nameContext *ctx){
    if(!Gen_simple_nameContext_cls) Gen_simple_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Gen_simple_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Gen_simple_nameContext_cls);
    return py_ctx;
}
