/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "RosettaMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_RosettaMRTranslator : public RosettaMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Rosetta_mrContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *Atom_pair_restraintsContext_cls = NULL;
    PyObject *Atom_pair_restraintContext_cls = NULL;
    PyObject *Angle_restraintsContext_cls = NULL;
    PyObject *Angle_restraintContext_cls = NULL;
    PyObject *Dihedral_restraintsContext_cls = NULL;
    PyObject *Dihedral_restraintContext_cls = NULL;
    PyObject *Dihedral_pair_restraintsContext_cls = NULL;
    PyObject *Dihedral_pair_restraintContext_cls = NULL;
    PyObject *Coordinate_restraintsContext_cls = NULL;
    PyObject *Coordinate_restraintContext_cls = NULL;
    PyObject *Local_coordinate_restraintsContext_cls = NULL;
    PyObject *Local_coordinate_restraintContext_cls = NULL;
    PyObject *Site_restraintsContext_cls = NULL;
    PyObject *Site_restraintContext_cls = NULL;
    PyObject *Site_residues_restraintsContext_cls = NULL;
    PyObject *Site_residues_restraintContext_cls = NULL;
    PyObject *Min_residue_atomic_distance_restraintsContext_cls = NULL;
    PyObject *Min_residue_atomic_distance_restraintContext_cls = NULL;
    PyObject *Big_bin_restraintsContext_cls = NULL;
    PyObject *Big_bin_restraintContext_cls = NULL;
    PyObject *Nested_restraintsContext_cls = NULL;
    PyObject *Nested_restraintContext_cls = NULL;
    PyObject *Any_restraintContext_cls = NULL;
    PyObject *Func_type_defContext_cls = NULL;
    PyObject *Rdc_restraintsContext_cls = NULL;
    PyObject *Rdc_restraintContext_cls = NULL;
    PyObject *Disulfide_bond_linkagesContext_cls = NULL;
    PyObject *Disulfide_bond_linkageContext_cls = NULL;
    PyObject *Atom_pair_w_chain_restraintsContext_cls = NULL;
    PyObject *Atom_pair_w_chain_restraintContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *Number_fContext_cls = NULL;
    PyObject *Gen_res_numContext_cls = NULL;
    PyObject *Gen_simple_nameContext_cls = NULL;

    public:
    SA_RosettaMRTranslator(speedy_antlr::Translator *translator);
    ~SA_RosettaMRTranslator();
    antlrcpp::Any visitRosetta_mr(RosettaMRParser::Rosetta_mrContext *ctx);

    antlrcpp::Any visitComment(RosettaMRParser::CommentContext *ctx);

    antlrcpp::Any visitAtom_pair_restraints(RosettaMRParser::Atom_pair_restraintsContext *ctx);

    antlrcpp::Any visitAtom_pair_restraint(RosettaMRParser::Atom_pair_restraintContext *ctx);

    antlrcpp::Any visitAngle_restraints(RosettaMRParser::Angle_restraintsContext *ctx);

    antlrcpp::Any visitAngle_restraint(RosettaMRParser::Angle_restraintContext *ctx);

    antlrcpp::Any visitDihedral_restraints(RosettaMRParser::Dihedral_restraintsContext *ctx);

    antlrcpp::Any visitDihedral_restraint(RosettaMRParser::Dihedral_restraintContext *ctx);

    antlrcpp::Any visitDihedral_pair_restraints(RosettaMRParser::Dihedral_pair_restraintsContext *ctx);

    antlrcpp::Any visitDihedral_pair_restraint(RosettaMRParser::Dihedral_pair_restraintContext *ctx);

    antlrcpp::Any visitCoordinate_restraints(RosettaMRParser::Coordinate_restraintsContext *ctx);

    antlrcpp::Any visitCoordinate_restraint(RosettaMRParser::Coordinate_restraintContext *ctx);

    antlrcpp::Any visitLocal_coordinate_restraints(RosettaMRParser::Local_coordinate_restraintsContext *ctx);

    antlrcpp::Any visitLocal_coordinate_restraint(RosettaMRParser::Local_coordinate_restraintContext *ctx);

    antlrcpp::Any visitSite_restraints(RosettaMRParser::Site_restraintsContext *ctx);

    antlrcpp::Any visitSite_restraint(RosettaMRParser::Site_restraintContext *ctx);

    antlrcpp::Any visitSite_residues_restraints(RosettaMRParser::Site_residues_restraintsContext *ctx);

    antlrcpp::Any visitSite_residues_restraint(RosettaMRParser::Site_residues_restraintContext *ctx);

    antlrcpp::Any visitMin_residue_atomic_distance_restraints(RosettaMRParser::Min_residue_atomic_distance_restraintsContext *ctx);

    antlrcpp::Any visitMin_residue_atomic_distance_restraint(RosettaMRParser::Min_residue_atomic_distance_restraintContext *ctx);

    antlrcpp::Any visitBig_bin_restraints(RosettaMRParser::Big_bin_restraintsContext *ctx);

    antlrcpp::Any visitBig_bin_restraint(RosettaMRParser::Big_bin_restraintContext *ctx);

    antlrcpp::Any visitNested_restraints(RosettaMRParser::Nested_restraintsContext *ctx);

    antlrcpp::Any visitNested_restraint(RosettaMRParser::Nested_restraintContext *ctx);

    antlrcpp::Any visitAny_restraint(RosettaMRParser::Any_restraintContext *ctx);

    antlrcpp::Any visitFunc_type_def(RosettaMRParser::Func_type_defContext *ctx);

    antlrcpp::Any visitRdc_restraints(RosettaMRParser::Rdc_restraintsContext *ctx);

    antlrcpp::Any visitRdc_restraint(RosettaMRParser::Rdc_restraintContext *ctx);

    antlrcpp::Any visitDisulfide_bond_linkages(RosettaMRParser::Disulfide_bond_linkagesContext *ctx);

    antlrcpp::Any visitDisulfide_bond_linkage(RosettaMRParser::Disulfide_bond_linkageContext *ctx);

    antlrcpp::Any visitAtom_pair_w_chain_restraints(RosettaMRParser::Atom_pair_w_chain_restraintsContext *ctx);

    antlrcpp::Any visitAtom_pair_w_chain_restraint(RosettaMRParser::Atom_pair_w_chain_restraintContext *ctx);

    antlrcpp::Any visitNumber(RosettaMRParser::NumberContext *ctx);

    antlrcpp::Any visitNumber_f(RosettaMRParser::Number_fContext *ctx);

    antlrcpp::Any visitGen_res_num(RosettaMRParser::Gen_res_numContext *ctx);

    antlrcpp::Any visitGen_simple_name(RosettaMRParser::Gen_simple_nameContext *ctx);

};