/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_sparkyspk_translator.h"


SA_SparkySPKTranslator::SA_SparkySPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_SparkySPKTranslator::~SA_SparkySPKTranslator() {
    Py_XDECREF(Sparky_spkContext_cls);
    Py_XDECREF(User_blockContext_cls);
    Py_XDECREF(User_statementContext_cls);
    Py_XDECREF(Spectrum_blockContext_cls);
    Py_XDECREF(Spectrum_statementContext_cls);
    Py_XDECREF(Spectrum_nameContext_cls);
    Py_XDECREF(Attached_dataContext_cls);
    Py_XDECREF(Attached_data_statementContext_cls);
    Py_XDECREF(ViewContext_cls);
    Py_XDECREF(View_statementContext_cls);
    Py_XDECREF(View_nameContext_cls);
    Py_XDECREF(View_numberContext_cls);
    Py_XDECREF(ParamsContext_cls);
    Py_XDECREF(Params_statementContext_cls);
    Py_XDECREF(OrnamentContext_cls);
    Py_XDECREF(Ornament_statementContext_cls);
    Py_XDECREF(Ornament_positionContext_cls);
    Py_XDECREF(LabelContext_cls);
    Py_XDECREF(Label_statementContext_cls);
    Py_XDECREF(Label_positionContext_cls);
}


antlrcpp::Any SA_SparkySPKTranslator::visitSparky_spk(SparkySPKParser::Sparky_spkContext *ctx){
    if(!Sparky_spkContext_cls) Sparky_spkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Sparky_spkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Sparky_spkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitUser_block(SparkySPKParser::User_blockContext *ctx){
    if(!User_blockContext_cls) User_blockContext_cls = PyObject_GetAttrString(translator->parser_cls, "User_blockContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, User_blockContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitUser_statement(SparkySPKParser::User_statementContext *ctx){
    if(!User_statementContext_cls) User_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "User_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, User_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitSpectrum_block(SparkySPKParser::Spectrum_blockContext *ctx){
    if(!Spectrum_blockContext_cls) Spectrum_blockContext_cls = PyObject_GetAttrString(translator->parser_cls, "Spectrum_blockContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Spectrum_blockContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitSpectrum_statement(SparkySPKParser::Spectrum_statementContext *ctx){
    if(!Spectrum_statementContext_cls) Spectrum_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Spectrum_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Spectrum_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitSpectrum_name(SparkySPKParser::Spectrum_nameContext *ctx){
    if(!Spectrum_nameContext_cls) Spectrum_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "Spectrum_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Spectrum_nameContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitAttached_data(SparkySPKParser::Attached_dataContext *ctx){
    if(!Attached_dataContext_cls) Attached_dataContext_cls = PyObject_GetAttrString(translator->parser_cls, "Attached_dataContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Attached_dataContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitAttached_data_statement(SparkySPKParser::Attached_data_statementContext *ctx){
    if(!Attached_data_statementContext_cls) Attached_data_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Attached_data_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Attached_data_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitView(SparkySPKParser::ViewContext *ctx){
    if(!ViewContext_cls) ViewContext_cls = PyObject_GetAttrString(translator->parser_cls, "ViewContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ViewContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitView_statement(SparkySPKParser::View_statementContext *ctx){
    if(!View_statementContext_cls) View_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "View_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, View_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitView_name(SparkySPKParser::View_nameContext *ctx){
    if(!View_nameContext_cls) View_nameContext_cls = PyObject_GetAttrString(translator->parser_cls, "View_nameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, View_nameContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitView_number(SparkySPKParser::View_numberContext *ctx){
    if(!View_numberContext_cls) View_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "View_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, View_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitParams(SparkySPKParser::ParamsContext *ctx){
    if(!ParamsContext_cls) ParamsContext_cls = PyObject_GetAttrString(translator->parser_cls, "ParamsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ParamsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitParams_statement(SparkySPKParser::Params_statementContext *ctx){
    if(!Params_statementContext_cls) Params_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Params_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Params_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitOrnament(SparkySPKParser::OrnamentContext *ctx){
    if(!OrnamentContext_cls) OrnamentContext_cls = PyObject_GetAttrString(translator->parser_cls, "OrnamentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, OrnamentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitOrnament_statement(SparkySPKParser::Ornament_statementContext *ctx){
    if(!Ornament_statementContext_cls) Ornament_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ornament_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ornament_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitOrnament_position(SparkySPKParser::Ornament_positionContext *ctx){
    if(!Ornament_positionContext_cls) Ornament_positionContext_cls = PyObject_GetAttrString(translator->parser_cls, "Ornament_positionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Ornament_positionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitLabel(SparkySPKParser::LabelContext *ctx){
    if(!LabelContext_cls) LabelContext_cls = PyObject_GetAttrString(translator->parser_cls, "LabelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LabelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitLabel_statement(SparkySPKParser::Label_statementContext *ctx){
    if(!Label_statementContext_cls) Label_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Label_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Label_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkySPKTranslator::visitLabel_position(SparkySPKParser::Label_positionContext *ctx){
    if(!Label_positionContext_cls) Label_positionContext_cls = PyObject_GetAttrString(translator->parser_cls, "Label_positionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Label_positionContext_cls);
    return py_ctx;
}
