/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "SparkyNPKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_SparkyNPKTranslator : public SparkyNPKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Sparky_npkContext_cls = NULL;
    PyObject *Data_labelContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *Peak_2d_poContext_cls = NULL;
    PyObject *Peak_3d_poContext_cls = NULL;
    PyObject *Peak_4d_poContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *NoteContext_cls = NULL;

    public:
    SA_SparkyNPKTranslator(speedy_antlr::Translator *translator);
    ~SA_SparkyNPKTranslator();
    antlrcpp::Any visitSparky_npk(SparkyNPKParser::Sparky_npkContext *ctx);

    antlrcpp::Any visitData_label(SparkyNPKParser::Data_labelContext *ctx);

    antlrcpp::Any visitPeak_2d(SparkyNPKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_3d(SparkyNPKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_4d(SparkyNPKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitPeak_2d_po(SparkyNPKParser::Peak_2d_poContext *ctx);

    antlrcpp::Any visitPeak_3d_po(SparkyNPKParser::Peak_3d_poContext *ctx);

    antlrcpp::Any visitPeak_4d_po(SparkyNPKParser::Peak_4d_poContext *ctx);

    antlrcpp::Any visitNumber(SparkyNPKParser::NumberContext *ctx);

    antlrcpp::Any visitNote(SparkyNPKParser::NoteContext *ctx);

};