/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_sparkynpk_translator.h"


SA_SparkyNPKTranslator::SA_SparkyNPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_SparkyNPKTranslator::~SA_SparkyNPKTranslator() {
    Py_XDECREF(Sparky_npkContext_cls);
    Py_XDECREF(Data_labelContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Peak_2d_poContext_cls);
    Py_XDECREF(Peak_3d_poContext_cls);
    Py_XDECREF(Peak_4d_poContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(NoteContext_cls);
}


antlrcpp::Any SA_SparkyNPKTranslator::visitSparky_npk(SparkyNPKParser::Sparky_npkContext *ctx){
    if(!Sparky_npkContext_cls) Sparky_npkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Sparky_npkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Sparky_npkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitData_label(SparkyNPKParser::Data_labelContext *ctx){
    if(!Data_labelContext_cls) Data_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_2d(SparkyNPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_3d(SparkyNPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_4d(SparkyNPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_2d_po(SparkyNPKParser::Peak_2d_poContext *ctx){
    if(!Peak_2d_poContext_cls) Peak_2d_poContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2d_poContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2d_poContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_3d_po(SparkyNPKParser::Peak_3d_poContext *ctx){
    if(!Peak_3d_poContext_cls) Peak_3d_poContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3d_poContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3d_poContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitPeak_4d_po(SparkyNPKParser::Peak_4d_poContext *ctx){
    if(!Peak_4d_poContext_cls) Peak_4d_poContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4d_poContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4d_poContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitNumber(SparkyNPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyNPKTranslator::visitNote(SparkyNPKParser::NoteContext *ctx){
    if(!NoteContext_cls) NoteContext_cls = PyObject_GetAttrString(translator->parser_cls, "NoteContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NoteContext_cls);
    return py_ctx;
}
