/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_schrodingermr_translator.h"


SA_SchrodingerMRTranslator::SA_SchrodingerMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_SchrodingerMRTranslator::~SA_SchrodingerMRTranslator() {
    Py_XDECREF(Schrodinger_mrContext_cls);
    Py_XDECREF(Import_structureContext_cls);
    Py_XDECREF(Struct_statementContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
    Py_XDECREF(Dihedral_angle_restraintContext_cls);
    Py_XDECREF(Angle_restraintContext_cls);
    Py_XDECREF(Distance_statementContext_cls);
    Py_XDECREF(Distance_assignContext_cls);
    Py_XDECREF(Distance_assign_by_numberContext_cls);
    Py_XDECREF(Dihedral_angle_statementContext_cls);
    Py_XDECREF(Dihedral_angle_assignContext_cls);
    Py_XDECREF(Dihedral_angle_assign_by_numberContext_cls);
    Py_XDECREF(Angle_statementContext_cls);
    Py_XDECREF(Angle_assignContext_cls);
    Py_XDECREF(Angle_assign_by_numberContext_cls);
    Py_XDECREF(Fxdi_statementContext_cls);
    Py_XDECREF(Fxdi_assignContext_cls);
    Py_XDECREF(Fxdi_assign_by_numberContext_cls);
    Py_XDECREF(Fxta_statementContext_cls);
    Py_XDECREF(Fxta_assignContext_cls);
    Py_XDECREF(Fxta_assign_by_numberContext_cls);
    Py_XDECREF(Fxba_statementContext_cls);
    Py_XDECREF(Fxba_assignContext_cls);
    Py_XDECREF(Fxba_assign_by_numberContext_cls);
    Py_XDECREF(Fxhb_statementContext_cls);
    Py_XDECREF(Fxhb_assignContext_cls);
    Py_XDECREF(Fxhb_assign_by_numberContext_cls);
    Py_XDECREF(SelectionContext_cls);
    Py_XDECREF(Selection_expressionContext_cls);
    Py_XDECREF(TermContext_cls);
    Py_XDECREF(FactorContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Number_fContext_cls);
    Py_XDECREF(Parameter_statementContext_cls);
}


antlrcpp::Any SA_SchrodingerMRTranslator::visitSchrodinger_mr(SchrodingerMRParser::Schrodinger_mrContext *ctx){
    if(!Schrodinger_mrContext_cls) Schrodinger_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Schrodinger_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Schrodinger_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitImport_structure(SchrodingerMRParser::Import_structureContext *ctx){
    if(!Import_structureContext_cls) Import_structureContext_cls = PyObject_GetAttrString(translator->parser_cls, "Import_structureContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Import_structureContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitStruct_statement(SchrodingerMRParser::Struct_statementContext *ctx){
    if(!Struct_statementContext_cls) Struct_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Struct_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Struct_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDistance_restraint(SchrodingerMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDihedral_angle_restraint(SchrodingerMRParser::Dihedral_angle_restraintContext *ctx){
    if(!Dihedral_angle_restraintContext_cls) Dihedral_angle_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_angle_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_angle_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitAngle_restraint(SchrodingerMRParser::Angle_restraintContext *ctx){
    if(!Angle_restraintContext_cls) Angle_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDistance_statement(SchrodingerMRParser::Distance_statementContext *ctx){
    if(!Distance_statementContext_cls) Distance_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDistance_assign(SchrodingerMRParser::Distance_assignContext *ctx){
    if(!Distance_assignContext_cls) Distance_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDistance_assign_by_number(SchrodingerMRParser::Distance_assign_by_numberContext *ctx){
    if(!Distance_assign_by_numberContext_cls) Distance_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDihedral_angle_statement(SchrodingerMRParser::Dihedral_angle_statementContext *ctx){
    if(!Dihedral_angle_statementContext_cls) Dihedral_angle_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_angle_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_angle_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDihedral_angle_assign(SchrodingerMRParser::Dihedral_angle_assignContext *ctx){
    if(!Dihedral_angle_assignContext_cls) Dihedral_angle_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_angle_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_angle_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitDihedral_angle_assign_by_number(SchrodingerMRParser::Dihedral_angle_assign_by_numberContext *ctx){
    if(!Dihedral_angle_assign_by_numberContext_cls) Dihedral_angle_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Dihedral_angle_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Dihedral_angle_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitAngle_statement(SchrodingerMRParser::Angle_statementContext *ctx){
    if(!Angle_statementContext_cls) Angle_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitAngle_assign(SchrodingerMRParser::Angle_assignContext *ctx){
    if(!Angle_assignContext_cls) Angle_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitAngle_assign_by_number(SchrodingerMRParser::Angle_assign_by_numberContext *ctx){
    if(!Angle_assign_by_numberContext_cls) Angle_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Angle_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Angle_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxdi_statement(SchrodingerMRParser::Fxdi_statementContext *ctx){
    if(!Fxdi_statementContext_cls) Fxdi_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxdi_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxdi_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxdi_assign(SchrodingerMRParser::Fxdi_assignContext *ctx){
    if(!Fxdi_assignContext_cls) Fxdi_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxdi_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxdi_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxdi_assign_by_number(SchrodingerMRParser::Fxdi_assign_by_numberContext *ctx){
    if(!Fxdi_assign_by_numberContext_cls) Fxdi_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxdi_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxdi_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxta_statement(SchrodingerMRParser::Fxta_statementContext *ctx){
    if(!Fxta_statementContext_cls) Fxta_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxta_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxta_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxta_assign(SchrodingerMRParser::Fxta_assignContext *ctx){
    if(!Fxta_assignContext_cls) Fxta_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxta_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxta_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxta_assign_by_number(SchrodingerMRParser::Fxta_assign_by_numberContext *ctx){
    if(!Fxta_assign_by_numberContext_cls) Fxta_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxta_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxta_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxba_statement(SchrodingerMRParser::Fxba_statementContext *ctx){
    if(!Fxba_statementContext_cls) Fxba_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxba_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxba_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxba_assign(SchrodingerMRParser::Fxba_assignContext *ctx){
    if(!Fxba_assignContext_cls) Fxba_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxba_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxba_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxba_assign_by_number(SchrodingerMRParser::Fxba_assign_by_numberContext *ctx){
    if(!Fxba_assign_by_numberContext_cls) Fxba_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxba_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxba_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxhb_statement(SchrodingerMRParser::Fxhb_statementContext *ctx){
    if(!Fxhb_statementContext_cls) Fxhb_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxhb_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxhb_statementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxhb_assign(SchrodingerMRParser::Fxhb_assignContext *ctx){
    if(!Fxhb_assignContext_cls) Fxhb_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxhb_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxhb_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFxhb_assign_by_number(SchrodingerMRParser::Fxhb_assign_by_numberContext *ctx){
    if(!Fxhb_assign_by_numberContext_cls) Fxhb_assign_by_numberContext_cls = PyObject_GetAttrString(translator->parser_cls, "Fxhb_assign_by_numberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Fxhb_assign_by_numberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitSelection(SchrodingerMRParser::SelectionContext *ctx){
    if(!SelectionContext_cls) SelectionContext_cls = PyObject_GetAttrString(translator->parser_cls, "SelectionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SelectionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitSelection_expression(SchrodingerMRParser::Selection_expressionContext *ctx){
    if(!Selection_expressionContext_cls) Selection_expressionContext_cls = PyObject_GetAttrString(translator->parser_cls, "Selection_expressionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Selection_expressionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitTerm(SchrodingerMRParser::TermContext *ctx){
    if(!TermContext_cls) TermContext_cls = PyObject_GetAttrString(translator->parser_cls, "TermContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, TermContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitFactor(SchrodingerMRParser::FactorContext *ctx){
    if(!FactorContext_cls) FactorContext_cls = PyObject_GetAttrString(translator->parser_cls, "FactorContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, FactorContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitNumber(SchrodingerMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitNumber_f(SchrodingerMRParser::Number_fContext *ctx){
    if(!Number_fContext_cls) Number_fContext_cls = PyObject_GetAttrString(translator->parser_cls, "Number_fContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Number_fContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SchrodingerMRTranslator::visitParameter_statement(SchrodingerMRParser::Parameter_statementContext *ctx){
    if(!Parameter_statementContext_cls) Parameter_statementContext_cls = PyObject_GetAttrString(translator->parser_cls, "Parameter_statementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Parameter_statementContext_cls);
    return py_ctx;
}
