/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_sparkyrpk_translator.h"


SA_SparkyRPKTranslator::SA_SparkyRPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_SparkyRPKTranslator::~SA_SparkyRPKTranslator() {
    Py_XDECREF(Sparky_rpkContext_cls);
    Py_XDECREF(Data_labelContext_cls);
    Py_XDECREF(Data_label_wo_assignContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(Peak_wo_assignContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(NoteContext_cls);
}


antlrcpp::Any SA_SparkyRPKTranslator::visitSparky_rpk(SparkyRPKParser::Sparky_rpkContext *ctx){
    if(!Sparky_rpkContext_cls) Sparky_rpkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Sparky_rpkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Sparky_rpkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitData_label(SparkyRPKParser::Data_labelContext *ctx){
    if(!Data_labelContext_cls) Data_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitData_label_wo_assign(SparkyRPKParser::Data_label_wo_assignContext *ctx){
    if(!Data_label_wo_assignContext_cls) Data_label_wo_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_label_wo_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_label_wo_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitPeak_2d(SparkyRPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitPeak_3d(SparkyRPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitPeak_4d(SparkyRPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitPeak_wo_assign(SparkyRPKParser::Peak_wo_assignContext *ctx){
    if(!Peak_wo_assignContext_cls) Peak_wo_assignContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_wo_assignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_wo_assignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitNumber(SparkyRPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SparkyRPKTranslator::visitNote(SparkyRPKParser::NoteContext *ctx){
    if(!NoteContext_cls) NoteContext_cls = PyObject_GetAttrString(translator->parser_cls, "NoteContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NoteContext_cls);
    return py_ctx;
}
