/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "SybylMRParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_SybylMRTranslator : public SybylMRParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Sybyl_mrContext_cls = NULL;
    PyObject *Distance_restraintsContext_cls = NULL;
    PyObject *Distance_restraintContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_SybylMRTranslator(speedy_antlr::Translator *translator);
    ~SA_SybylMRTranslator();
    antlrcpp::Any visitSybyl_mr(SybylMRParser::Sybyl_mrContext *ctx);

    antlrcpp::Any visitDistance_restraints(SybylMRParser::Distance_restraintsContext *ctx);

    antlrcpp::Any visitDistance_restraint(SybylMRParser::Distance_restraintContext *ctx);

    antlrcpp::Any visitNumber(SybylMRParser::NumberContext *ctx);

};