/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_sybylmr_translator.h"


SA_SybylMRTranslator::SA_SybylMRTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_SybylMRTranslator::~SA_SybylMRTranslator() {
    Py_XDECREF(Sybyl_mrContext_cls);
    Py_XDECREF(Distance_restraintsContext_cls);
    Py_XDECREF(Distance_restraintContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_SybylMRTranslator::visitSybyl_mr(SybylMRParser::Sybyl_mrContext *ctx){
    if(!Sybyl_mrContext_cls) Sybyl_mrContext_cls = PyObject_GetAttrString(translator->parser_cls, "Sybyl_mrContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Sybyl_mrContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SybylMRTranslator::visitDistance_restraints(SybylMRParser::Distance_restraintsContext *ctx){
    if(!Distance_restraintsContext_cls) Distance_restraintsContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SybylMRTranslator::visitDistance_restraint(SybylMRParser::Distance_restraintContext *ctx){
    if(!Distance_restraintContext_cls) Distance_restraintContext_cls = PyObject_GetAttrString(translator->parser_cls, "Distance_restraintContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Distance_restraintContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_SybylMRTranslator::visitNumber(SybylMRParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
