/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_vnmrpk_translator.h"


SA_VnmrPKTranslator::SA_VnmrPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_VnmrPKTranslator::~SA_VnmrPKTranslator() {
    Py_XDECREF(Vnmr_pkContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(FormatContext_cls);
    Py_XDECREF(Peak_ll2dContext_cls);
    Py_XDECREF(Peak_ll3dContext_cls);
    Py_XDECREF(Peak_ll4dContext_cls);
    Py_XDECREF(Data_labelContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(NumberContext_cls);
}


antlrcpp::Any SA_VnmrPKTranslator::visitVnmr_pk(VnmrPKParser::Vnmr_pkContext *ctx){
    if(!Vnmr_pkContext_cls) Vnmr_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Vnmr_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Vnmr_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitComment(VnmrPKParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitFormat(VnmrPKParser::FormatContext *ctx){
    if(!FormatContext_cls) FormatContext_cls = PyObject_GetAttrString(translator->parser_cls, "FormatContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, FormatContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_ll2d(VnmrPKParser::Peak_ll2dContext *ctx){
    if(!Peak_ll2dContext_cls) Peak_ll2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_ll2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_ll2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_ll3d(VnmrPKParser::Peak_ll3dContext *ctx){
    if(!Peak_ll3dContext_cls) Peak_ll3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_ll3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_ll3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_ll4d(VnmrPKParser::Peak_ll4dContext *ctx){
    if(!Peak_ll4dContext_cls) Peak_ll4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_ll4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_ll4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitData_label(VnmrPKParser::Data_labelContext *ctx){
    if(!Data_labelContext_cls) Data_labelContext_cls = PyObject_GetAttrString(translator->parser_cls, "Data_labelContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Data_labelContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_2d(VnmrPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_3d(VnmrPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitPeak_4d(VnmrPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_VnmrPKTranslator::visitNumber(VnmrPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}
