/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "VnmrPKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_VnmrPKTranslator : public VnmrPKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Vnmr_pkContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *FormatContext_cls = NULL;
    PyObject *Peak_ll2dContext_cls = NULL;
    PyObject *Peak_ll3dContext_cls = NULL;
    PyObject *Peak_ll4dContext_cls = NULL;
    PyObject *Data_labelContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;

    public:
    SA_VnmrPKTranslator(speedy_antlr::Translator *translator);
    ~SA_VnmrPKTranslator();
    antlrcpp::Any visitVnmr_pk(VnmrPKParser::Vnmr_pkContext *ctx);

    antlrcpp::Any visitComment(VnmrPKParser::CommentContext *ctx);

    antlrcpp::Any visitFormat(VnmrPKParser::FormatContext *ctx);

    antlrcpp::Any visitPeak_ll2d(VnmrPKParser::Peak_ll2dContext *ctx);

    antlrcpp::Any visitPeak_ll3d(VnmrPKParser::Peak_ll3dContext *ctx);

    antlrcpp::Any visitPeak_ll4d(VnmrPKParser::Peak_ll4dContext *ctx);

    antlrcpp::Any visitData_label(VnmrPKParser::Data_labelContext *ctx);

    antlrcpp::Any visitPeak_2d(VnmrPKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_3d(VnmrPKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_4d(VnmrPKParser::Peak_4dContext *ctx);

    antlrcpp::Any visitNumber(VnmrPKParser::NumberContext *ctx);

};