/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "XeasyPROTParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_XeasyPROTTranslator : public XeasyPROTParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Xeasy_protContext_cls = NULL;
    PyObject *ProtContext_cls = NULL;
    PyObject *ResidueContext_cls = NULL;

    public:
    SA_XeasyPROTTranslator(speedy_antlr::Translator *translator);
    ~SA_XeasyPROTTranslator();
    antlrcpp::Any visitXeasy_prot(XeasyPROTParser::Xeasy_protContext *ctx);

    antlrcpp::Any visitProt(XeasyPROTParser::ProtContext *ctx);

    antlrcpp::Any visitResidue(XeasyPROTParser::ResidueContext *ctx);

};