/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_xwinnmrpk_translator.h"


SA_XwinNmrPKTranslator::SA_XwinNmrPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_XwinNmrPKTranslator::~SA_XwinNmrPKTranslator() {
    Py_XDECREF(Xwinnmr_pkContext_cls);
    Py_XDECREF(CommentContext_cls);
    Py_XDECREF(DimensionContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
}


antlrcpp::Any SA_XwinNmrPKTranslator::visitXwinnmr_pk(XwinNmrPKParser::Xwinnmr_pkContext *ctx){
    if(!Xwinnmr_pkContext_cls) Xwinnmr_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Xwinnmr_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Xwinnmr_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XwinNmrPKTranslator::visitComment(XwinNmrPKParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XwinNmrPKTranslator::visitDimension(XwinNmrPKParser::DimensionContext *ctx){
    if(!DimensionContext_cls) DimensionContext_cls = PyObject_GetAttrString(translator->parser_cls, "DimensionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, DimensionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XwinNmrPKTranslator::visitPeak_2d(XwinNmrPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XwinNmrPKTranslator::visitPeak_3d(XwinNmrPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XwinNmrPKTranslator::visitPeak_4d(XwinNmrPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}
