/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_xeasyprot_translator.h"


SA_XeasyPROTTranslator::SA_XeasyPROTTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_XeasyPROTTranslator::~SA_XeasyPROTTranslator() {
    Py_XDECREF(Xeasy_protContext_cls);
    Py_XDECREF(ProtContext_cls);
    Py_XDECREF(ResidueContext_cls);
}


antlrcpp::Any SA_XeasyPROTTranslator::visitXeasy_prot(XeasyPROTParser::Xeasy_protContext *ctx){
    if(!Xeasy_protContext_cls) Xeasy_protContext_cls = PyObject_GetAttrString(translator->parser_cls, "Xeasy_protContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Xeasy_protContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPROTTranslator::visitProt(XeasyPROTParser::ProtContext *ctx){
    if(!ProtContext_cls) ProtContext_cls = PyObject_GetAttrString(translator->parser_cls, "ProtContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ProtContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPROTTranslator::visitResidue(XeasyPROTParser::ResidueContext *ctx){
    if(!ResidueContext_cls) ResidueContext_cls = PyObject_GetAttrString(translator->parser_cls, "ResidueContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ResidueContext_cls);
    return py_ctx;
}
