/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include <cstring>
#include <any>

#include "antlr4-runtime.h"
#include "XMLLexer.h"
#include "XMLParser.h"
#include "speedy_antlr.h"
#include "latin1_input_stream.h"  // wwPDB

#include "sa_xml_translator.h"
antlr4::tree::ParseTree* get_parse_tree_document(XMLParser *parser) {return parser->document();}

antlr4::tree::ParseTree* get_parse_tree(XMLParser *parser, const char *entry_rule_name) {
    static std::map<std::string, antlr4::tree::ParseTree* (*)(XMLParser*)> table
    {
        {"document", &get_parse_tree_document}
    };

    auto entry = table.find(entry_rule_name);
    if (entry != table.end()) {
        return (*(entry->second))(parser);
    } else {
        PyErr_SetString(PyExc_ValueError, "Invalid entry_rule_name");
        throw speedy_antlr::PythonException();
    }
}

/*
 * Python function prototype:
 *  do_parse(
 *      parser_cls:antlr4.Parser,
 *      stream:antlr4.InputStream,
 *      entry_rule_name:str,
 *      sa_err_listener:SA_ErrorListener
 *  )
 */
PyObject* do_parse(PyObject *self, PyObject *args) {
    PyObject *strdata = NULL;
    PyObject *strdata_as_bytes = NULL;
    PyObject *result = NULL;
    PyObject *token_module = NULL;

    try {
        // Get args
        PyObject *parser_cls = NULL;
        PyObject *stream = NULL;
        const char *entry_rule_name = NULL;
        PyObject *sa_err_listener = NULL;
        int use_sll = 0;  // wwPDB: PredictionMode.SLL when true
        if(!PyArg_ParseTuple(args,
            "OOsOp:do_parse",
            &parser_cls, &stream, &entry_rule_name, &sa_err_listener, &use_sll
        )) {
            return NULL;
        }

        // Extract input stream's string
        strdata = PyObject_GetAttrString(stream, "strdata");
        if(!strdata) throw speedy_antlr::PythonException();
        if(!PyUnicode_Check(strdata)) {
            PyErr_SetString(PyExc_TypeError, "InputStream.strdata must be a str");
            throw speedy_antlr::PythonException();
        }

        // Create an antlr InputStream object. wwPDB: a str stored one byte per
        // character is lexed in place (strdata is held until the end of the parse);
        // any other goes through the UTF-32 copy of ANTLRInputStream as before.
        std::unique_ptr<antlr4::CharStream> cpp_stream_holder;
        if(PyUnicode_KIND(strdata) == PyUnicode_1BYTE_KIND) {
            cpp_stream_holder.reset(new wwpdb::Latin1InputStream(
                reinterpret_cast<const unsigned char *>(PyUnicode_1BYTE_DATA(strdata)),
                static_cast<size_t>(PyUnicode_GET_LENGTH(strdata))));
        } else {
            char *cstrdata;
            Py_ssize_t bufsize;
            strdata_as_bytes = PyCodec_Encode(strdata, "utf-8", NULL);
            if(!strdata_as_bytes) throw speedy_antlr::PythonException();
            if(PyBytes_AsStringAndSize(strdata_as_bytes, &cstrdata, &bufsize) < 0)
                throw speedy_antlr::PythonException();
            cpp_stream_holder.reset(new antlr4::ANTLRInputStream(cstrdata, bufsize));
        }
        antlr4::CharStream &cpp_stream = *cpp_stream_holder;

        // in case error listener is overridden
        token_module = PyImport_ImportModule("antlr4.Token");
        if(!token_module) throw speedy_antlr::PythonException();
        speedy_antlr::Translator translator(parser_cls, stream);
        speedy_antlr::ErrorTranslatorListener err_listener(&translator, sa_err_listener);

        // Lex
        XMLLexer lexer(&cpp_stream);
        if(sa_err_listener != Py_None){
            lexer.removeErrorListeners();
            lexer.addErrorListener(&err_listener);
        }
        antlr4::CommonTokenStream token_stream(&lexer);
        token_stream.fill();

        // Parse
        XMLParser parser(&token_stream);
        if(sa_err_listener != Py_None){
            parser.removeErrorListeners();
            parser.addErrorListener(&err_listener);
        }
        // wwPDB: mirror the Python driver's prediction mode, or the two
        // paths accept different inputs and report different errors.
        if (use_sll) {
            parser.getInterpreter<antlr4::atn::ParserATNSimulator>()
                ->setPredictionMode(antlr4::atn::PredictionMode::SLL);
        }
        antlr4::tree::ParseTree *parse_tree;
        parse_tree = get_parse_tree(&parser, entry_rule_name);

        // Translate Parse tree to Python
        SA_XMLTranslator visitor(&translator);
        result = std::any_cast<PyObject *>(visitor.visit(parse_tree));

        // Clean up data
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);
        Py_XDECREF(strdata_as_bytes);

        return result;

    } catch(speedy_antlr::PythonException &e) {
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);
        Py_XDECREF(strdata_as_bytes);
        Py_XDECREF(result);

        // Python exception already has error indicator set
        return NULL;
    } catch(...) {
        Py_XDECREF(token_module);
        Py_XDECREF(strdata);
        Py_XDECREF(strdata_as_bytes);
        Py_XDECREF(result);

        // An internal C++ exception was thrown.
        // Set error indicator to a generic runtime error
        PyErr_SetString(PyExc_RuntimeError, "Internal error");
        return NULL;
    }
}


extern "C" {

    static PyObject* c_do_parse(PyObject *self, PyObject *args) {
        return do_parse(self, args);
    }

    static PyMethodDef methods[] = {
        {
            "do_parse",  c_do_parse, METH_VARARGS,
            "Run parser"
        },
        {NULL, NULL, 0, NULL} /* Sentinel */
    };

    static struct PyModuleDef module = {
        PyModuleDef_HEAD_INIT,
        "sa_xml_cpp_parser",   /* name of module */
        NULL, /* module documentation, may be NULL */
        -1,       /* size of per-interpreter state of the module,
                    or -1 if the module keeps state in global variables. */
        methods
    };
}


PyMODINIT_FUNC
PyInit_sa_xml_cpp_parser(void) {
    PyObject *m = PyModule_Create(&module);
    return m;
}