/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_xeasypk_translator.h"


SA_XeasyPKTranslator::SA_XeasyPKTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_XeasyPKTranslator::~SA_XeasyPKTranslator() {
    Py_XDECREF(Xeasy_pkContext_cls);
    Py_XDECREF(DimensionContext_cls);
    Py_XDECREF(PeakContext_cls);
    Py_XDECREF(FormatContext_cls);
    Py_XDECREF(InameContext_cls);
    Py_XDECREF(Cyana_formatContext_cls);
    Py_XDECREF(SpectrumContext_cls);
    Py_XDECREF(ToleranceContext_cls);
    Py_XDECREF(Peak_list_2dContext_cls);
    Py_XDECREF(Peak_2dContext_cls);
    Py_XDECREF(Peak_list_3dContext_cls);
    Py_XDECREF(Peak_3dContext_cls);
    Py_XDECREF(Peak_list_4dContext_cls);
    Py_XDECREF(Peak_4dContext_cls);
    Py_XDECREF(PositionContext_cls);
    Py_XDECREF(NumberContext_cls);
    Py_XDECREF(Type_codeContext_cls);
    Py_XDECREF(AssignContext_cls);
    Py_XDECREF(CommentContext_cls);
}


antlrcpp::Any SA_XeasyPKTranslator::visitXeasy_pk(XeasyPKParser::Xeasy_pkContext *ctx){
    if(!Xeasy_pkContext_cls) Xeasy_pkContext_cls = PyObject_GetAttrString(translator->parser_cls, "Xeasy_pkContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Xeasy_pkContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitDimension(XeasyPKParser::DimensionContext *ctx){
    if(!DimensionContext_cls) DimensionContext_cls = PyObject_GetAttrString(translator->parser_cls, "DimensionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, DimensionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak(XeasyPKParser::PeakContext *ctx){
    if(!PeakContext_cls) PeakContext_cls = PyObject_GetAttrString(translator->parser_cls, "PeakContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PeakContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitFormat(XeasyPKParser::FormatContext *ctx){
    if(!FormatContext_cls) FormatContext_cls = PyObject_GetAttrString(translator->parser_cls, "FormatContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, FormatContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitIname(XeasyPKParser::InameContext *ctx){
    if(!InameContext_cls) InameContext_cls = PyObject_GetAttrString(translator->parser_cls, "InameContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, InameContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitCyana_format(XeasyPKParser::Cyana_formatContext *ctx){
    if(!Cyana_formatContext_cls) Cyana_formatContext_cls = PyObject_GetAttrString(translator->parser_cls, "Cyana_formatContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Cyana_formatContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitSpectrum(XeasyPKParser::SpectrumContext *ctx){
    if(!SpectrumContext_cls) SpectrumContext_cls = PyObject_GetAttrString(translator->parser_cls, "SpectrumContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, SpectrumContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitTolerance(XeasyPKParser::ToleranceContext *ctx){
    if(!ToleranceContext_cls) ToleranceContext_cls = PyObject_GetAttrString(translator->parser_cls, "ToleranceContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ToleranceContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_list_2d(XeasyPKParser::Peak_list_2dContext *ctx){
    if(!Peak_list_2dContext_cls) Peak_list_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_2d(XeasyPKParser::Peak_2dContext *ctx){
    if(!Peak_2dContext_cls) Peak_2dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_2dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_2dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_list_3d(XeasyPKParser::Peak_list_3dContext *ctx){
    if(!Peak_list_3dContext_cls) Peak_list_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_3d(XeasyPKParser::Peak_3dContext *ctx){
    if(!Peak_3dContext_cls) Peak_3dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_3dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_3dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_list_4d(XeasyPKParser::Peak_list_4dContext *ctx){
    if(!Peak_list_4dContext_cls) Peak_list_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_list_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_list_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPeak_4d(XeasyPKParser::Peak_4dContext *ctx){
    if(!Peak_4dContext_cls) Peak_4dContext_cls = PyObject_GetAttrString(translator->parser_cls, "Peak_4dContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Peak_4dContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitPosition(XeasyPKParser::PositionContext *ctx){
    if(!PositionContext_cls) PositionContext_cls = PyObject_GetAttrString(translator->parser_cls, "PositionContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, PositionContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitNumber(XeasyPKParser::NumberContext *ctx){
    if(!NumberContext_cls) NumberContext_cls = PyObject_GetAttrString(translator->parser_cls, "NumberContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, NumberContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitType_code(XeasyPKParser::Type_codeContext *ctx){
    if(!Type_codeContext_cls) Type_codeContext_cls = PyObject_GetAttrString(translator->parser_cls, "Type_codeContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, Type_codeContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitAssign(XeasyPKParser::AssignContext *ctx){
    if(!AssignContext_cls) AssignContext_cls = PyObject_GetAttrString(translator->parser_cls, "AssignContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AssignContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_XeasyPKTranslator::visitComment(XeasyPKParser::CommentContext *ctx){
    if(!CommentContext_cls) CommentContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommentContext_cls);
    return py_ctx;
}
