/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "XMLParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_XMLTranslator : public XMLParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *DocumentContext_cls = NULL;
    PyObject *PrologContext_cls = NULL;
    PyObject *ContentContext_cls = NULL;
    PyObject *ElementContext_cls = NULL;
    PyObject *ReferenceContext_cls = NULL;
    PyObject *AttributeContext_cls = NULL;
    PyObject *ChardataContext_cls = NULL;
    PyObject *MiscContext_cls = NULL;

    public:
    SA_XMLTranslator(speedy_antlr::Translator *translator);
    ~SA_XMLTranslator();
    antlrcpp::Any visitDocument(XMLParser::DocumentContext *ctx);

    antlrcpp::Any visitProlog(XMLParser::PrologContext *ctx);

    antlrcpp::Any visitContent(XMLParser::ContentContext *ctx);

    antlrcpp::Any visitElement(XMLParser::ElementContext *ctx);

    antlrcpp::Any visitReference(XMLParser::ReferenceContext *ctx);

    antlrcpp::Any visitAttribute(XMLParser::AttributeContext *ctx);

    antlrcpp::Any visitChardata(XMLParser::ChardataContext *ctx);

    antlrcpp::Any visitMisc(XMLParser::MiscContext *ctx);

};