/*
 * This file was auto-generated by speedy-antlr-tool v1.4.4
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "XwinNmrPKParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_XwinNmrPKTranslator : public XwinNmrPKParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Xwinnmr_pkContext_cls = NULL;
    PyObject *CommentContext_cls = NULL;
    PyObject *DimensionContext_cls = NULL;
    PyObject *Peak_2dContext_cls = NULL;
    PyObject *Peak_3dContext_cls = NULL;
    PyObject *Peak_4dContext_cls = NULL;

    public:
    SA_XwinNmrPKTranslator(speedy_antlr::Translator *translator);
    ~SA_XwinNmrPKTranslator();
    antlrcpp::Any visitXwinnmr_pk(XwinNmrPKParser::Xwinnmr_pkContext *ctx);

    antlrcpp::Any visitComment(XwinNmrPKParser::CommentContext *ctx);

    antlrcpp::Any visitDimension(XwinNmrPKParser::DimensionContext *ctx);

    antlrcpp::Any visitPeak_2d(XwinNmrPKParser::Peak_2dContext *ctx);

    antlrcpp::Any visitPeak_3d(XwinNmrPKParser::Peak_3dContext *ctx);

    antlrcpp::Any visitPeak_4d(XwinNmrPKParser::Peak_4dContext *ctx);

};